-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "sequent_backend"."keys_ceremony" add column "is_default" Boolean
--  null default 'true';
