-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "sequent_backend"."support_material" add column "is_hidden" boolean
--  null;
