// SPDX-FileCopyrightText: 2023 Felix Robles <felix@sequentech.io>
//
// SPDX-License-Identifier: AGPL-3.0-only
use wasm_bindgen::prelude::*;

#[wasm_bindgen(typescript_custom_section)]
const IPERMISSIONS: &'static str = r#"
export enum IPermissions {
    TENANT_CREATE = "tenant-create",
    TENANT_READ = "tenant-read",
    TENANT_WRITE = "tenant-write",
    ELECTION_EVENT_CREATE = "election-event-create",
    ELECTION_EVENT_READ = "election-event-read",
    ELECTION_EVENT_WRITE = "election-event-write",
    ELECTION_EVENT_DELETE = "election-event-delete",
    VOTER_CREATE  = "voter-create",
    VOTER_READ = "voter-read",
    VOTER_WRITE = "voter-write",
    USER_CREATE = "user-create",
    USER_READ = "user-read",
    USER_WRITE = "user-write",
    USER_PERMISSION_CREATE = "user-permission-create",
    USER_PERMISSION_READ = "user-permission-read",
    USER_PERMISSION_WRITE = "user-permission-write",
    ROLE_CREATE = "role-create",
    ROLE_READ = "role-read",
    ROLE_WRITE = "role-write",
    ROLE_ASSIGN = "role-assign",
    template_CREATE = "communication-template-create",
    template_READ = "communication-template-read",
    template_WRITE = "communication-template-write",
    NOTIFICATION_READ = "notification-read",
    NOTIFICATION_WRITE = "notification-write",
    NOTIFICATION_SEND = "notification-send",
    AREA_READ = "area-read",
    AREA_WRITE = "area-write",
    ELECTION_STATE_WRITE = "election-state-write",
    ELECTION_TYPE_CREATE = "election-type-create",
    ELECTION_TYPE_READ = "election-type-read",
    ELECTION_TYPE_WRITE = "election-type-write",
    VOTING_CHANNEL_READ = "voting-channel-read",
    VOTING_CHANNEL_WRITE = "voting-channel-write",
    TRUSTEE_CREATE = "trustee-create",
    TRUSTEE_READ = "trustee-read",
    TRUSTEE_WRITE = "trustee-write",
    TRUSTEE_CEREMONY = "trustee-ceremony",
    TALLY_READ = "tally-read",
    TALLY_START = "tally-start",
    TALLY_WRITE = "tally-write",
    TALLY_RESULTS_READ = "tally-results-read",
    PUBLISH_READ = "publish-read",
    PUBLISH_WRITE = "publish-write",
    LOGS_READ = "logs-read",
    TASKS_READ = "tasks-read",
    KEYS_READ = "keys-read",
    DOCUMENT_UPLOAD = "document-upload",
    DOCUMENT_DOWNLOAD = "document-download",
    ADMIN_CEREMONY = "admin-ceremony",
    ADMIN_DASHBOARD_VIEW = "admin-dashboard-view",
}
"#;
