use anyhow::Result;

use board_messages::grpc::GetMessagesReply;
use board_messages::grpc::GrpcB3Message;
use rusqlite::params;
use rusqlite::Connection;
use std::path::PathBuf;
use tracing::{info, warn};

use board_messages::grpc::client::B3Client;
use board_messages::braid::message::Message;

use strand::serialization::StrandDeserialize;


impl super::Board for GrpcB3 {
    type Factory = GrpcB3BoardParams;

    async fn get_messages(&mut self, last_id: Option<i64>) -> Result<Vec<(Message, i64)>> {
        let messages = self.client.get_messages(&self.board_name, last_id.unwrap_or(-1)).await?;
        let messages = messages.get_ref();

        messages.messages
            .iter()
            .map(|m| {
                let message = Message::strand_deserialize(&m.message)?;
                let id = m.id;
                Ok((message, id))
            })
            .collect::<Result<Vec<(Message, i64)>>>()
    }

    async fn insert_messages(&mut self, messages: Vec<Message>) -> Result<()> {
        let _ = self.client.put_messages(&self.board_name, &messages).await?;
        
        Ok(())
    }

}

pub struct GrpcB3 {
    client: B3Client,
    board_name: String,
    store_root: Option<PathBuf>,
}
impl GrpcB3 {
    pub fn new(url: &'static str, board_name: &str, store_root: Option<PathBuf>) -> GrpcB3 {
        let client = B3Client::new(url);

        GrpcB3 {
            client,
            board_name: board_name.to_string(),
            store_root,
        }
    }
    
    fn get_store(&self) -> Result<Connection> {
        let db_path = self
            .store_root
            .as_ref()
            .expect("only called when store_root is some")
            .join(&self.board_name);
        let connection = Connection::open(&db_path)?;
        // The autogenerated id column is used to establish an order that cannot be manipulated by the external board. Once a retrieved message is
        // stored and assigned a local id, it is not possible for later messages to have an earlier id.
        // The external_id column is used to retrieve _new_ messages as defined by the external board (to optimize bandwidth).
        connection.execute("CREATE TABLE if not exists MESSAGES(id INTEGER PRIMARY KEY AUTOINCREMENT, external_id INT, message BLOB NOT NULL UNIQUE)", [])?;

        Ok(connection)
    }

    async fn store_and_return_messages(
        &mut self,
        last_id: Option<i64>,
    ) -> Result<Vec<(Message, i64)>> {
        let connection = self.get_store()?;

        let external_last_id =
            connection.query_row("SELECT max(external_id) FROM messages;", [], |row| {
                row.get(0)
            });

        if external_last_id.is_err() {
            warn!(
                "sql error retrieving external_last_id {:?}",
                external_last_id
            );
        }

        // When querying for all messages we use -1 as default lower limit (this requests uses the > comparator in sql)
        let messages = self
            .get_remote_messages(external_last_id.unwrap_or(-1))
            .await?;

        info!(
            "Retrieved {} messages remotely, storing locally",
            messages.len()
        );

        // FIXME verify message signatures before inserting in local store
        let mut statement =
            connection.prepare("INSERT INTO MESSAGES(external_id, message) VALUES(?1, ?2)")?;
        connection.execute("BEGIN TRANSACTION", [])?;
        for message in messages {
            statement.execute(params![message.id, message.message])?;
        }
        connection.execute("END TRANSACTION", [])?;

        let mut stmt =
            connection.prepare("SELECT id,message FROM MESSAGES where id > ?1 order by id asc")?;
        // When querying for all messages in the store we use -1 as a lower limit
        let rows = stmt.query_map([last_id.unwrap_or(-1)], |row| {
            Ok(MessageRow {
                id: row.get(0)?,
                message: row.get(1)?,
            })
        })?;

        info!("Deserializing rows into Message structs..");
        let messages: Result<Vec<(Message, i64)>> = rows
            .map(|mr| {
                let row = mr?;
                let id = row.id;
                let message = Message::strand_deserialize(&row.message)?;
                Ok((message, id))
            })
            .collect();

        messages
    }

    // Returns all messages whose id > last_id.
    async fn get_remote_messages(&mut self, last_id: i64) -> Result<Vec<GrpcB3Message>> {
        let messages = self
            .client
            .get_messages(&self.board_name, last_id)
            .await?;

        let messages = messages.into_inner();

        Ok(messages.messages)
    }
}


pub struct GrpcB3BoardParams {
    url: &'static str,
    board_name: String,
    store_root: Option<PathBuf>,
}
impl GrpcB3BoardParams {
    pub(crate) fn new(url: &'static str, board_name: &str, store_root: Option<PathBuf>) -> GrpcB3BoardParams {
        GrpcB3BoardParams {
            url, board_name: board_name.to_string(), store_root
        }
    }
}

impl super::BoardFactory<GrpcB3> for GrpcB3BoardParams {
    async fn get_board(&self) -> Result<GrpcB3> {
        Ok(GrpcB3::new(self.url, &self.board_name, self.store_root.clone()))
    }
}

struct MessageRow {
    id: i64,
    message: Vec<u8>,
}

#[cfg(test)]
pub(crate) mod tests {

    use board_messages::grpc::B3Client;
    use board_messages::grpc::GetMessagesRequest;
    use serial_test::serial;

    #[tokio::test]
    #[ignore]
    #[serial]
    async fn test_grpc_client() {
        let mut client = B3Client::connect("http://[::1]:50051").await.unwrap();

        let request = tonic::Request::new(GetMessagesRequest {
            board: "default".to_string(),
            last_id: -1,
        });

        let response = client.get_messages(request).await.unwrap();

        println!("RESPONSE={:?}", response.into_inner().messages);
    }
}
