// SPDX-FileCopyrightText: 2023 Eduardo Robles <edu@sequentech.io>
//
// SPDX-License-Identifier: AGPL-3.0-only

use anyhow::Result;
use board_messages::braid::message::Message;
use board_messages::grpc::pgsql::{B3MessageRow, PgsqlDbConnectionParams, XPgsqlB3Client};
use rusqlite::params;
use rusqlite::Connection;
use std::path::PathBuf;

use tracing::{info, warn};

use strand::serialization::StrandDeserialize;

/// A bulletin board implemented on postgresql
pub struct PgsqlBoard {
    pub(crate) board_client: XPgsqlB3Client,
    pub(crate) board_name: String,
    pub(crate) store_root: Option<PathBuf>,
}

impl PgsqlBoard {
    pub async fn new(
        connection: &PgsqlDbConnectionParams,
        board_name: String,
        store_root: Option<PathBuf>,
    ) -> Result<PgsqlBoard> {
        let board_client = XPgsqlB3Client::new(connection).await?;
        Ok(PgsqlBoard {
            board_client,
            board_name: board_name.to_string(),
            store_root,
        })
    }

    // Returns all messages whose id > last_id.
    async fn get_remote_messages(&mut self, last_id: i64) -> Result<Vec<B3MessageRow>> {
        let messages = self
            .board_client
            .get_messages(&self.board_name, last_id)
            .await?;

        Ok(messages)
    }

    fn get_store(&self) -> Result<Connection> {
        let db_path = self
            .store_root
            .as_ref()
            .expect("only called when store_root is some")
            .join(&self.board_name);
        let connection = Connection::open(&db_path)?;
        // The autogenerated id column is used to establish an order that cannot be manipulated by the external board. Once a retrieved message is
        // stored and assigned a local id, it is not possible for later messages to have an earlier id.
        // The external_id column is used to retrieve _new_ messages as defined by the external board (to optimize bandwidth).
        connection.execute("CREATE TABLE if not exists MESSAGES(id INTEGER PRIMARY KEY AUTOINCREMENT, external_id INT, message BLOB NOT NULL UNIQUE)", [])?;

        Ok(connection)
    }

    async fn store_and_return_messages(
        &mut self,
        last_id: Option<i64>,
    ) -> Result<Vec<(Message, i64)>> {
        let connection = self.get_store()?;

        let external_last_id =
            connection.query_row("SELECT max(external_id) FROM messages;", [], |row| {
                row.get(0)
            });

        if external_last_id.is_err() {
            warn!(
                "sql error retrieving external_last_id {:?}",
                external_last_id
            );
        }

        // When querying for all messages we use -1 as default lower limit (this requests uses the > comparator in sql)
        let messages = self
            .get_remote_messages(external_last_id.unwrap_or(-1))
            .await?;

        info!(
            "Retrieved {} messages remotely, storing locally",
            messages.len()
        );

        // FIXME verify message signatures before inserting in local store
        let mut statement =
            connection.prepare("INSERT INTO MESSAGES(external_id, message) VALUES(?1, ?2)")?;
        connection.execute("BEGIN TRANSACTION", [])?;
        for message in messages {
            statement.execute(params![message.id, message.message])?;
        }
        connection.execute("END TRANSACTION", [])?;

        let mut stmt =
            connection.prepare("SELECT id,message FROM MESSAGES where id > ?1 order by id asc")?;
        // When querying for all messages in the store we use -1 as a lower limit
        let rows = stmt.query_map([last_id.unwrap_or(-1)], |row| {
            Ok(MessageRow {
                id: row.get(0)?,
                message: row.get(1)?,
            })
        })?;

        info!("Deserializing rows into Message structs..");
        let messages: Result<Vec<(Message, i64)>> = rows
            .map(|mr| {
                let row = mr?;
                let id = row.id;
                let message = Message::strand_deserialize(&row.message)?;
                Ok((message, id))
            })
            .collect();

        messages
    }
}

impl super::Board for PgsqlBoard {
    type Factory = PgsqlBoardParams;

    // Returns all messages whose id > last_id. If last_id is None, all messages will be returned.
    // If a store is used only the messages not previously received will be requested.
    async fn get_messages(&mut self, last_id: Option<i64>) -> Result<Vec<(Message, i64)>> {
        let messages = if self.store_root.is_some() {
            // When using a store, only the messages not previously received will be requested
            self.store_and_return_messages(last_id).await?
        } else {
            // If last_id is None, use -1 as last_id
            let messages = self.get_remote_messages(last_id.unwrap_or(-1)).await?;

            messages
                .iter()
                .map(|m| {
                    let message = Message::strand_deserialize(&m.message)?;
                    let id = m.id;
                    Ok((message, id))
                })
                .collect::<Result<Vec<(Message, i64)>>>()?
        };

        Ok(messages)
    }

    async fn insert_messages(&mut self, messages: Vec<Message>) -> Result<()> {
        if messages.len() > 0 {
            let bm: Result<Vec<B3MessageRow>> =
                messages.into_iter().map(|m| m.try_into()).collect();
            self.board_client
                .insert_messages(&self.board_name, &bm?)
                .await
        } else {
            Ok(())
        }
    }
}

pub struct PgsqlBoardParams {
    connection: PgsqlDbConnectionParams,
    board_name: String,
    store_root: Option<PathBuf>,
}
impl PgsqlBoardParams {
    pub fn new(
        connection: &PgsqlDbConnectionParams,
        board_name: String,
        store_root: Option<PathBuf>,
    ) -> PgsqlBoardParams {
        PgsqlBoardParams {
            connection: connection.clone(),
            board_name,
            store_root,
        }
    }
}

impl super::BoardFactory<PgsqlBoard> for PgsqlBoardParams {
    async fn get_board(&self) -> Result<PgsqlBoard> {
        PgsqlBoard::new(
            &self.connection,
            self.board_name.clone(),
            self.store_root.clone(),
        )
        .await
    }
}

struct MessageRow {
    id: i64,
    message: Vec<u8>,
}
