-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "sequent_backend"."ballot_style" add column "deleted_at" timestamptz
--  null;
