// SPDX-FileCopyrightText: 2025 Sequent Tech Inc <legal@sequentech.io>
//
// SPDX-License-Identifier: AGPL-3.0-only
#![allow(non_camel_case_types)]

use borsh::{BorshDeserialize, BorshSerialize};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::default::Default;
use strum_macros::{Display, EnumString};

/// Represents the status of the keys ceremony execution.
#[derive(
    Display,
    Serialize,
    Deserialize,
    Debug,
    PartialEq,
    Eq,
    Clone,
    EnumString,
    Default,
)]
pub enum KeysCeremonyExecutionStatus {
    /// User can configure the ceremony at this step
    USER_CONFIGURATION,
    /// Process starts but the config message hasn't been added to the board.
    #[default]
    STARTED,
    /// Config message has been added to the board and trustees are working.
    IN_PROGRESS,
    /// Successful completion.
    SUCCESS,
    /// Ceremony was cancelled.
    CANCELLED,
}

/// Audit/event log entry for ceremonies, used for timestamped messages in ceremony workflows.
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct Log {
    /// Date the log was created.
    pub created_date: String,
    /// Log message text.
    pub log_text: String,
}

/// Represents the status of a trustee in the keys ceremony.
#[derive(
    Display, Serialize, Deserialize, Debug, PartialEq, Eq, Clone, EnumString,
)]
pub enum TrusteeStatus {
    /// Trustee is waiting to act.
    WAITING,
    /// Trustee has generated their key.
    KEY_GENERATED,
    /// Trustee has retrieved their key.
    KEY_RETRIEVED,
    /// Trustee has checked their key.
    KEY_CHECKED,
}

/// Represents a participant in the keys ceremony.
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct Trustee {
    /// Name of the trustee.
    pub name: String,
    /// Status of the trustee.
    pub status: TrusteeStatus,
}

/// Represents the state of a keys ceremony.
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct KeysCeremonyStatus {
    /// Date the ceremony was stopped, if any.
    pub stop_date: Option<String>,
    /// Public key generated by the ceremony, if any.
    pub public_key: Option<String>,
    /// Logs for the ceremony.
    pub logs: Vec<Log>,
    /// Trustees participating in the ceremony.
    pub trustees: Vec<Trustee>,
}

/// Represents the status of the tally execution.
#[derive(
    Display,
    Serialize,
    Deserialize,
    Debug,
    PartialEq,
    Eq,
    Clone,
    EnumString,
    Default,
    JsonSchema,
)]
pub enum TallyExecutionStatus {
    /// Tally process has started.
    #[default]
    STARTED,
    /// Tally process is connected.
    CONNECTED,
    /// Tally process is in progress.
    IN_PROGRESS,
    /// Tally process is waiting for election officials selection for winner determination.
    AWAITING_INPUT,
    /// Tally process completed successfully.
    SUCCESS,
    /// Tally process was cancelled.
    CANCELLED,
}

/// Status of a trustee in the tally ceremony
#[derive(
    Display,
    Serialize,
    Deserialize,
    Debug,
    PartialEq,
    Eq,
    Clone,
    EnumString,
    Default,
)]
pub enum TallyTrusteeStatus {
    /// Trustee is waiting to act.
    #[default]
    WAITING,
    /// Trustee has restored their key.
    KEY_RESTORED,
}

/// Represents a participant in the tally ceremony.
#[derive(Serialize, Deserialize, Debug, Clone, Default)]
pub struct TallyTrustee {
    /// Name of the trustee.
    pub name: String,
    /// Status of the trustee.
    pub status: TallyTrusteeStatus,
}

/// Status of the tally execution for an election (waiting, mixing, decrypting, success, error).
#[derive(
    Display,
    Serialize,
    Deserialize,
    Debug,
    PartialEq,
    Eq,
    Clone,
    EnumString,
    Default,
)]
pub enum TallyElectionStatus {
    /// Tally is waiting to start.
    #[default]
    WAITING,
    /// Tally is mixing ballots.
    MIXING,
    /// Tally is decrypting results.
    DECRYPTING,
    /// Tally completed successfully.
    SUCCESS,
    /// Tally encountered an error.
    ERROR,
}

/// Represents the status of an election in a tally ceremony.
#[derive(Serialize, Deserialize, Debug, Clone, Default)]
pub struct TallyElection {
    /// Election identifier.
    pub election_id: String,
    /// Status of the election tally.
    pub status: TallyElectionStatus,
    /// Progress of the election tally (0.0 to 1.0).
    pub progress: f64,
}

/// Represents the state of a tally ceremony
#[derive(Serialize, Deserialize, Debug, Clone, Default)]
pub struct TallyCeremonyStatus {
    /// Date the ceremony was stopped, if any.
    pub stop_date: Option<String>,
    /// Logs for the ceremony.
    pub logs: Vec<Log>,
    /// Trustees participating in the ceremony.
    pub trustees: Vec<TallyTrustee>,
    /// Status of each election in the ceremony.
    pub elections_status: Vec<TallyElection>,
}

/// Distinguishes the type of tally report generated
#[derive(
    Display,
    Serialize,
    Deserialize,
    Debug,
    PartialEq,
    Eq,
    Clone,
    EnumString,
    Default,
    JsonSchema,
)]
pub enum TallyType {
    /// Electoral results report.
    #[default]
    #[strum(serialize = "ELECTORAL_RESULTS")]
    ELECTORAL_RESULTS,
    /// Initialization report.
    #[strum(serialize = "INITIALIZATION_REPORT")]
    INITIALIZATION_REPORT,
}

/// Holds paths to output documentss generated during a tally session
#[derive(Serialize, Deserialize, Debug, Clone, Default, PartialEq, Eq)]
pub struct TallySessionDocuments {
    /// Path to the `sqlite` document, if any.
    pub sqlite: Option<String>,
    /// Path to the `xlsx` document, if any.
    pub xlsx: Option<String>,
}

/// Configures whether ceremonies are conducted manually or automatically.
#[derive(
    BorshSerialize,
    BorshDeserialize,
    Display,
    Serialize,
    Deserialize,
    Debug,
    PartialEq,
    Eq,
    Clone,
    EnumString,
    Default,
    JsonSchema,
)]
pub enum CeremoniesPolicy {
    /// Ceremonies are conducted manually.
    #[default]
    #[strum(serialize = "manual-ceremonies")]
    #[serde(rename = "manual-ceremonies")]
    MANUAL_CEREMONIES,
    /// Ceremonies are conducted automatically.
    #[strum(serialize = "automated-ceremonies")]
    #[serde(rename = "automated-ceremonies")]
    AUTOMATED_CEREMONIES,
}

/// Specifies the operation performed during tallying.
#[derive(
    Debug,
    Display,
    EnumString,
    Clone,
    Copy,
    PartialEq,
    Eq,
    Serialize,
    Deserialize,
    BorshSerialize,
    BorshDeserialize,
)]
pub enum TallyOperation {
    /// Process ballots to calculate candidate results and participation statistics.
    #[strum(serialize = "process-ballots-all")]
    #[serde(rename = "process-ballots-all")]
    ProcessBallotsAll,
    /// Aggregate results that have been processed in every area.
    #[strum(serialize = "aggregate-results")]
    #[serde(rename = "aggregate-results")]
    AggregateResults,
    /// Calculate participation statistics without candidate results.
    #[strum(serialize = "skip-candidate-results")]
    #[serde(rename = "skip-candidate-results")]
    SkipCandidateResults,
}

/// Specifies whether a tally operation is scoped to an area or a contest.
#[derive(Debug, Display)]
pub enum ScopeOperation {
    /// Operation for an area.
    Area(TallyOperation),
    /// Operation for a contest.
    Contest(TallyOperation),
}

/// Specifies the counting algorithm used for tallying votes in an election.
#[derive(
    Debug,
    Clone,
    Serialize,
    Deserialize,
    BorshSerialize,
    BorshDeserialize,
    JsonSchema,
    PartialEq,
    Eq,
)]
pub enum TieBreakingMethod {
    Random,
    ExternalProcedure,
}

#[derive(
    Debug,
    Clone,
    Serialize,
    Deserialize,
    BorshSerialize,
    BorshDeserialize,
    JsonSchema,
    PartialEq,
    Eq,
)]
pub struct TallySessionResolutionData {
    pub round_number: Option<u64>,
    pub tied_candidate_ids: Vec<String>,
    pub vote_count: u64,
    pub method_used: TieBreakingMethod,
    pub resolved_by_candidate_id: Option<String>,
}

#[derive(
    Debug, Clone, Serialize, Deserialize, PartialEq, Display, EnumString,
)]
#[serde(rename_all = "snake_case")]
#[strum(serialize_all = "snake_case")]
pub enum TallySessionResolutionType {
    IrvTieBreak,
}

#[derive(
    Debug, Clone, Serialize, Deserialize, PartialEq, Display, EnumString,
)]
#[serde(rename_all = "lowercase")]
#[strum(serialize_all = "lowercase")]
pub enum TallySessionResolutionStatus {
    Pending,
    Resolved,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TallySessionResolution {
    pub id: String,
    pub tenant_id: String,
    pub election_event_id: String,
    pub tally_session_id: String,
    pub contest_id: Option<String>,
    pub created_at: Option<chrono::DateTime<chrono::Utc>>,
    pub last_updated_at: Option<chrono::DateTime<chrono::Utc>>,
    pub resolution_type: TallySessionResolutionType,
    pub status: TallySessionResolutionStatus,
    pub resolution_data: Option<TallySessionResolutionData>,
    pub resolved_by_user: Option<String>,
    pub resolved_at: Option<chrono::DateTime<chrono::Utc>>,
    pub labels: Option<Value>,
    pub annotations: Option<Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TallyResolution {
    pub contest_id: String,
    pub selected_candidate_id: String,
}

#[derive(
    Eq,
    PartialEq,
    Debug,
    EnumString,
    Display,
    Default,
    Serialize,
    Deserialize,
    BorshSerialize,
    BorshDeserialize,
    JsonSchema,
    Clone,
    Copy,
)]
pub enum CountingAlgType {
    /// Plurality-at-large voting.
    #[strum(serialize = "plurality-at-large")]
    #[serde(rename = "plurality-at-large")]
    #[default]
    PluralityAtLarge,
    /// Instant-runoff voting (ranked-choice).
    #[strum(serialize = "instant-runoff")]
    #[serde(rename = "instant-runoff")]
    InstantRunoff,
    /// Borda count (Nauru variant).
    #[strum(serialize = "borda-nauru")]
    #[serde(rename = "borda-nauru")]
    BordaNauru,
    /// Borda count.
    #[strum(serialize = "borda")]
    #[serde(rename = "borda")]
    Borda,
    /// Borda count (Mas Madrid variant).
    #[strum(serialize = "borda-mas-madrid")]
    #[serde(rename = "borda-mas-madrid")]
    BordaMasMadrid,
    /// Pairwise beta method.
    #[strum(serialize = "pairwise-beta")]
    #[serde(rename = "pairwise-beta")]
    PairwiseBeta,
    /// Desborda3 method.
    #[strum(serialize = "desborda3")]
    #[serde(rename = "desborda3")]
    Desborda3,
    /// Desborda2 method.
    #[strum(serialize = "desborda2")]
    #[serde(rename = "desborda2")]
    Desborda2,
    /// Desborda method.
    #[strum(serialize = "desborda")]
    #[serde(rename = "desborda")]
    Desborda,
    /// Cumulative voting.
    #[strum(serialize = "cumulative")]
    #[serde(rename = "cumulative")]
    Cumulative,
}

impl CountingAlgType {
    /// Returns true if the counting algorithm is preferential (ranked-choice).
    #[must_use]
    pub const fn is_preferential(&self) -> bool {
        matches!(
            self,
            CountingAlgType::InstantRunoff
                | CountingAlgType::Borda
                | CountingAlgType::BordaNauru
                | CountingAlgType::BordaMasMadrid
                | CountingAlgType::PairwiseBeta
                | CountingAlgType::Desborda
                | CountingAlgType::Desborda2
                | CountingAlgType::Desborda3
        )
    }

    /// Returns the default tally operation for a contest based on the algorithm.
    #[must_use]
    pub const fn get_default_tally_operation_for_contest(
        &self,
    ) -> TallyOperation {
        if self.is_preferential() {
            TallyOperation::ProcessBallotsAll
        } else {
            TallyOperation::AggregateResults
        }
    }

    /// Returns the default tally operation for an area based on the algorithm.
    #[must_use]
    pub const fn get_default_tally_operation_for_area(&self) -> TallyOperation {
        if self.is_preferential() {
            TallyOperation::SkipCandidateResults
        } else {
            TallyOperation::ProcessBallotsAll
        }
    }
}
