name: pdf-renderer
version: 1.0.0
runtime: rust:1.70
main: src/main.rs

environment:
  CHROME_PATH: "/usr/bin/chromium"
  PDF_TRANSPORT_NAME: "orare-openwhisk"
  OPENWHISK_ACTION: "true"
  OPENWHISK_ACTION_NAME: "pdf-renderer"
  OPENWHISK_ACTION_VERSION: "1.0.0"

parameters:
  html:
    type: string
    description: HTML content to render
    required: true
  pdf_options:
    type: object
    description: PDF rendering options
    required: false
    properties:
      landscape:
        type: boolean
      scale:
        type: number
      paper_width:
        type: number
      paper_height:
        type: number
      margin_top:
        type: number
      margin_bottom:
        type: number
      margin_left:
        type: number
      margin_right:
        type: number
      print_background:
        type: boolean
      display_header_footer:
        type: boolean
      prefer_css_page_size:
        type: boolean

annotations:
  provide-api-key: true
  web-export: true
  raw-http: true
  final: true

limits:
  timeout: 60000
  memory: 512
  logs: 10
  concurrency: 1 