AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  doc_renderer

Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  DocRendererFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: !Sub ${AccountIDParameter}.dkr.ecr.us-east-1.amazonaws.com/doc-renderer:${EnvironmentParameter}
      Events:
        DocRenderer:
          Type: Api
          Properties:
            Path: /
            Method: get
