// SPDX-FileCopyrightText: 2026 Sequent Tech <legal@sequentech.io>
//
// SPDX-License-Identifier: AGPL-3.0-only

//! Round-trip every byte tree in a real Verificatum proof directory.
//!
//! This is the acceptance test for Stage 1 of the plan in `VERIFICATUM.md`: we
//! must be able to parse VMN's own `.bt` files and re-emit them **byte for
//! byte**. Anything less means our encoder and VMN's disagree somewhere, which
//! would surface later as an unverifiable proof with no useful diagnostic.
//!
//! The corpus is generated by VMN itself and is not checked in (it is throwaway
//! demo key material). Point the test at one with:
//!
//! ```text
//! VCOMPAT_CORPUS=/path/to/nizkp/default cargo test -p vcompat --test corpus_roundtrip
//! ```
//!
//! Without that variable the test reports what it would have done and passes,
//! so the suite stays green on machines with no corpus.

use std::path::{Path, PathBuf};

use vcompat::arithm;
use vcompat::bytetree::ByteTree;
use vcompat::marshal;

fn corpus_dir() -> Option<PathBuf> {
    let raw = std::env::var("VCOMPAT_CORPUS").ok()?;
    let path = PathBuf::from(raw);
    if path.is_dir() {
        Some(path)
    } else {
        panic!("VCOMPAT_CORPUS is set but {} is not a directory", path.display());
    }
}

/// Every `.bt` file under `dir`, recursively.
fn byte_tree_files(dir: &Path) -> Vec<PathBuf> {
    let mut found = Vec::new();
    let mut stack = vec![dir.to_path_buf()];
    while let Some(current) = stack.pop() {
        let entries = match std::fs::read_dir(&current) {
            Ok(e) => e,
            Err(_) => continue,
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                stack.push(path);
            } else if path.extension().map(|e| e == "bt").unwrap_or(false) {
                found.push(path);
            }
        }
    }
    found.sort();
    found
}

#[test]
fn every_corpus_byte_tree_roundtrips_exactly() {
    let Some(dir) = corpus_dir() else {
        eprintln!("skipping: set VCOMPAT_CORPUS to a VMN nizkp directory to run this test");
        return;
    };

    let files = byte_tree_files(&dir);
    assert!(!files.is_empty(), "no .bt files under {}", dir.display());

    for path in &files {
        let original = std::fs::read(path).expect("read corpus file");
        let tree = ByteTree::from_bytes(&original)
            .unwrap_or_else(|e| panic!("{}: parse failed: {e}", path.display()));

        assert_eq!(
            tree.serialized_len(),
            original.len(),
            "{}: serialized_len disagrees with the file size",
            path.display()
        );
        assert_eq!(
            tree.to_bytes(),
            original,
            "{}: re-encoding is not byte-identical",
            path.display()
        );
    }

    eprintln!("round-tripped {} byte trees from {}", files.len(), dir.display());
}

/// Structural checks against the documented layout (VMNV §9.1), not just byte
/// equality: this is what catches a parser that round-trips garbage faithfully.
#[test]
fn corpus_structures_match_the_specification() {
    let Some(dir) = corpus_dir() else {
        eprintln!("skipping: set VCOMPAT_CORPUS to a VMN nizkp directory to run this test");
        return;
    };
    let width = marshal::p256::WIDTH;

    // FullPublicKey.bt is pk = (g, y), and g must be the standard P-256 base
    // point -- an end-to-end check of the coordinate encoding.
    let pk = ByteTree::from_bytes(&std::fs::read(dir.join("FullPublicKey.bt")).unwrap()).unwrap();
    let parts = pk.as_node_of(2).expect("pk = (g, y)");
    assert_eq!(parts[0], marshal::p256::generator(), "pk's g is the P-256 generator");
    let y = parts[1].as_node_of(2).expect("y is an affine point");
    assert_eq!(y[0].as_leaf().unwrap().len(), width);

    // Ciphertexts.bt is an array of width-2 ciphertexts: node(u_arrays, v_arrays),
    // each side transposed into `width` component arrays of N elements.
    let ciphs =
        ByteTree::from_bytes(&std::fs::read(dir.join("Ciphertexts.bt")).unwrap()).unwrap();
    let sides = ciphs.as_node_of(2).expect("ciphertext = (u, v)");
    let u_rows = arithm::product_array_rows(&sides[0]).expect("u side transposes");
    let v_rows = arithm::product_array_rows(&sides[1]).expect("v side transposes");
    assert_eq!(u_rows.len(), v_rows.len(), "u and v have the same count");
    let n = u_rows.len();
    assert!(n > 0);
    assert_eq!(u_rows[0].len(), 2, "width 2");

    // tau^pos: node(B, A', B', C', D', F') with |B| = |B'| = N (VMNV §8.3).
    let tau = ByteTree::from_bytes(
        &std::fs::read(dir.join("proofs/PoSCommitment01.bt")).unwrap(),
    )
    .unwrap();
    let tau = tau.as_node_of(6).expect("tau^pos has 6 components");
    assert_eq!(tau[0].as_node().unwrap().len(), n, "B has N entries");
    assert_eq!(tau[2].as_node().unwrap().len(), n, "B' has N entries");

    // sigma^pos: node(k_A, k_B, k_C, k_D, k_E, k_F) with |k_B| = |k_E| = N,
    // scalars at the fixed width, and k_F of width omega.
    let sigma =
        ByteTree::from_bytes(&std::fs::read(dir.join("proofs/PoSReply01.bt")).unwrap()).unwrap();
    let sigma = sigma.as_node_of(6).expect("sigma^pos has 6 components");
    assert_eq!(sigma[0].as_leaf().unwrap().len(), width, "k_A is a fixed-width scalar");
    assert_eq!(sigma[1].as_node().unwrap().len(), n, "k_B has N entries");
    assert_eq!(sigma[4].as_node().unwrap().len(), n, "k_E has N entries");
    assert_eq!(sigma[5].as_node().unwrap().len(), 2, "k_F has omega entries");

    // The permutation commitment is a flat array of N group elements.
    let mu = ByteTree::from_bytes(
        &std::fs::read(dir.join("proofs/PermutationCommitment01.bt")).unwrap(),
    )
    .unwrap();
    assert_eq!(mu.as_node().unwrap().len(), n, "mu has N Pedersen commitments");

    // CorrectIndices.bt is a boolean array of length k+1 whose true entries are
    // the set Delta (VMNV §9.1 point 20).
    let indices = ByteTree::from_bytes(
        &std::fs::read(dir.join("proofs/CorrectIndices.bt")).unwrap(),
    )
    .unwrap();
    let flags = arithm::bool_array_values(&indices).expect("boolean array");
    assert!(flags.iter().any(|&b| b), "at least one party decrypted");

    eprintln!("structural checks passed for N={n}, width=2, P-256");
}
