/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 */
const documents = {
    "\n    mutation createBallotReceipt(\n        $ballot_id: String!\n        $ballot_tracker_url: String!\n        $election_event_id: uuid!\n        $tenant_id: uuid!\n        $election_id: uuid!\n    ) {\n        create_ballot_receipt(\n            ballot_id: $ballot_id\n            ballot_tracker_url: $ballot_tracker_url\n            election_event_id: $election_event_id\n            tenant_id: $tenant_id\n            election_id: $election_id\n        ) {\n            id\n            ballot_id\n            status\n        }\n    }\n": types.CreateBallotReceiptDocument,
    "\n    query FetchDocument($electionEventId: String!, $documentId: String!) {\n        fetchDocument(election_event_id: $electionEventId, document_id: $documentId) {\n            url\n        }\n    }\n": types.FetchDocumentDocument,
    "\n    query GetBallotStyles {\n        sequent_backend_ballot_style(where: {deleted_at: {_is_null: true}}) {\n            id\n            election_id\n            election_event_id\n            status\n            tenant_id\n            ballot_eml\n            ballot_signature\n            created_at\n            area_id\n            annotations\n            labels\n            last_updated_at\n            deleted_at\n        }\n    }\n": types.GetBallotStylesDocument,
    "\n    query GetCastVote(\n        $tenantId: uuid\n        $electionEventId: uuid\n        $electionId: uuid\n        $ballotId: String!\n    ) {\n        sequent_backend_cast_vote(\n            where: {\n                _and: {\n                    tenant_id: {_eq: $tenantId}\n                    election_event_id: {_eq: $electionEventId}\n                    election_id: {_eq: $electionId}\n                    ballot_id: {_eq: $ballotId}\n                }\n            }\n        ) {\n            ballot_id\n            content\n        }\n    }\n": types.GetCastVoteDocument,
    "\n    query GetCastVotes {\n        sequent_backend_cast_vote {\n            id\n            tenant_id\n            election_id\n            area_id\n            created_at\n            last_updated_at\n            labels\n            annotations\n            content\n            cast_ballot_signature\n            voter_id_string\n            election_event_id\n        }\n    }\n": types.GetCastVotesDocument,
    "\n    query GetDocument($ids: [uuid!], $tenantId: uuid, $electionEventId: uuid) {\n        sequent_backend_document(\n            where: {\n                _and: {\n                    tenant_id: {_eq: $tenantId}\n                    election_event_id: {_eq: $electionEventId}\n                    id: {_in: $ids}\n                }\n            }\n        ) {\n            id\n            tenant_id\n            election_event_id\n            name\n            media_type\n            size\n            labels\n            annotations\n            created_at\n            last_updated_at\n            is_public\n        }\n    }\n": types.GetDocumentDocument,
    "\n    query GetElectionEvent($electionEventId: uuid!, $tenantId: uuid!) {\n        sequent_backend_election_event(\n            where: {_and: {id: {_eq: $electionEventId}, tenant_id: {_eq: $tenantId}}}\n        ) {\n            id\n            presentation\n            status\n        }\n    }\n": types.GetElectionEventDocument,
    "\n    query GetElections($electionIds: [uuid!]!) {\n        sequent_backend_election(where: {id: {_in: $electionIds}}) {\n            annotations\n            created_at\n            description\n            election_event_id\n            eml\n            id\n            is_consolidated_ballot_encoding\n            labels\n            last_updated_at\n            name\n            num_allowed_revotes\n            presentation\n            spoil_ballot_option\n            status\n            tenant_id\n            alias\n        }\n    }\n": types.GetElectionsDocument,
    "\n    query GetSupportMaterials($electionEventId: uuid!, $tenantId: uuid!) {\n        sequent_backend_support_material(\n            where: {\n                _and: {\n                    is_hidden: {_eq: false}\n                    election_event_id: {_eq: $electionEventId}\n                    tenant_id: {_eq: $tenantId}\n                }\n            }\n        ) {\n            data\n            document_id\n            id\n            annotations\n            created_at\n            election_event_id\n            kind\n            labels\n            last_updated_at\n            tenant_id\n        }\n    }\n": types.GetSupportMaterialsDocument,
    "\n    mutation InsertCastVote($electionId: uuid!, $ballotId: String!, $content: String!) {\n        insert_cast_vote(election_id: $electionId, ballot_id: $ballotId, content: $content) {\n            id\n            ballot_id\n            election_id\n            election_event_id\n            tenant_id\n            election_id\n            area_id\n            created_at\n            last_updated_at\n            labels\n            annotations\n            content\n            cast_ballot_signature\n            voter_id_string\n            election_event_id\n        }\n    }\n": types.InsertCastVoteDocument,
    "\n    query listCastVoteMessages(\n        $tenantId: String!\n        $electionEventId: String!\n        $electionId: String\n        $ballotId: String!\n        $limit: Int\n        $offset: Int\n        $orderBy: ElectoralLogOrderBy\n    ) {\n        list_cast_vote_messages(\n            tenant_id: $tenantId\n            election_event_id: $electionEventId\n            election_id: $electionId\n            ballot_id: $ballotId\n            limit: $limit\n            offset: $offset\n            order_by: $orderBy\n        ) {\n            list {\n                statement_timestamp\n                statement_kind\n                ballot_id\n                username\n            }\n            total\n        }\n    }\n": types.ListCastVoteMessagesDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation createBallotReceipt(\n        $ballot_id: String!\n        $ballot_tracker_url: String!\n        $election_event_id: uuid!\n        $tenant_id: uuid!\n        $election_id: uuid!\n    ) {\n        create_ballot_receipt(\n            ballot_id: $ballot_id\n            ballot_tracker_url: $ballot_tracker_url\n            election_event_id: $election_event_id\n            tenant_id: $tenant_id\n            election_id: $election_id\n        ) {\n            id\n            ballot_id\n            status\n        }\n    }\n"): (typeof documents)["\n    mutation createBallotReceipt(\n        $ballot_id: String!\n        $ballot_tracker_url: String!\n        $election_event_id: uuid!\n        $tenant_id: uuid!\n        $election_id: uuid!\n    ) {\n        create_ballot_receipt(\n            ballot_id: $ballot_id\n            ballot_tracker_url: $ballot_tracker_url\n            election_event_id: $election_event_id\n            tenant_id: $tenant_id\n            election_id: $election_id\n        ) {\n            id\n            ballot_id\n            status\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query FetchDocument($electionEventId: String!, $documentId: String!) {\n        fetchDocument(election_event_id: $electionEventId, document_id: $documentId) {\n            url\n        }\n    }\n"): (typeof documents)["\n    query FetchDocument($electionEventId: String!, $documentId: String!) {\n        fetchDocument(election_event_id: $electionEventId, document_id: $documentId) {\n            url\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetBallotStyles {\n        sequent_backend_ballot_style(where: {deleted_at: {_is_null: true}}) {\n            id\n            election_id\n            election_event_id\n            status\n            tenant_id\n            ballot_eml\n            ballot_signature\n            created_at\n            area_id\n            annotations\n            labels\n            last_updated_at\n            deleted_at\n        }\n    }\n"): (typeof documents)["\n    query GetBallotStyles {\n        sequent_backend_ballot_style(where: {deleted_at: {_is_null: true}}) {\n            id\n            election_id\n            election_event_id\n            status\n            tenant_id\n            ballot_eml\n            ballot_signature\n            created_at\n            area_id\n            annotations\n            labels\n            last_updated_at\n            deleted_at\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetCastVote(\n        $tenantId: uuid\n        $electionEventId: uuid\n        $electionId: uuid\n        $ballotId: String!\n    ) {\n        sequent_backend_cast_vote(\n            where: {\n                _and: {\n                    tenant_id: {_eq: $tenantId}\n                    election_event_id: {_eq: $electionEventId}\n                    election_id: {_eq: $electionId}\n                    ballot_id: {_eq: $ballotId}\n                }\n            }\n        ) {\n            ballot_id\n            content\n        }\n    }\n"): (typeof documents)["\n    query GetCastVote(\n        $tenantId: uuid\n        $electionEventId: uuid\n        $electionId: uuid\n        $ballotId: String!\n    ) {\n        sequent_backend_cast_vote(\n            where: {\n                _and: {\n                    tenant_id: {_eq: $tenantId}\n                    election_event_id: {_eq: $electionEventId}\n                    election_id: {_eq: $electionId}\n                    ballot_id: {_eq: $ballotId}\n                }\n            }\n        ) {\n            ballot_id\n            content\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetCastVotes {\n        sequent_backend_cast_vote {\n            id\n            tenant_id\n            election_id\n            area_id\n            created_at\n            last_updated_at\n            labels\n            annotations\n            content\n            cast_ballot_signature\n            voter_id_string\n            election_event_id\n        }\n    }\n"): (typeof documents)["\n    query GetCastVotes {\n        sequent_backend_cast_vote {\n            id\n            tenant_id\n            election_id\n            area_id\n            created_at\n            last_updated_at\n            labels\n            annotations\n            content\n            cast_ballot_signature\n            voter_id_string\n            election_event_id\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetDocument($ids: [uuid!], $tenantId: uuid, $electionEventId: uuid) {\n        sequent_backend_document(\n            where: {\n                _and: {\n                    tenant_id: {_eq: $tenantId}\n                    election_event_id: {_eq: $electionEventId}\n                    id: {_in: $ids}\n                }\n            }\n        ) {\n            id\n            tenant_id\n            election_event_id\n            name\n            media_type\n            size\n            labels\n            annotations\n            created_at\n            last_updated_at\n            is_public\n        }\n    }\n"): (typeof documents)["\n    query GetDocument($ids: [uuid!], $tenantId: uuid, $electionEventId: uuid) {\n        sequent_backend_document(\n            where: {\n                _and: {\n                    tenant_id: {_eq: $tenantId}\n                    election_event_id: {_eq: $electionEventId}\n                    id: {_in: $ids}\n                }\n            }\n        ) {\n            id\n            tenant_id\n            election_event_id\n            name\n            media_type\n            size\n            labels\n            annotations\n            created_at\n            last_updated_at\n            is_public\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetElectionEvent($electionEventId: uuid!, $tenantId: uuid!) {\n        sequent_backend_election_event(\n            where: {_and: {id: {_eq: $electionEventId}, tenant_id: {_eq: $tenantId}}}\n        ) {\n            id\n            presentation\n            status\n        }\n    }\n"): (typeof documents)["\n    query GetElectionEvent($electionEventId: uuid!, $tenantId: uuid!) {\n        sequent_backend_election_event(\n            where: {_and: {id: {_eq: $electionEventId}, tenant_id: {_eq: $tenantId}}}\n        ) {\n            id\n            presentation\n            status\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetElections($electionIds: [uuid!]!) {\n        sequent_backend_election(where: {id: {_in: $electionIds}}) {\n            annotations\n            created_at\n            description\n            election_event_id\n            eml\n            id\n            is_consolidated_ballot_encoding\n            labels\n            last_updated_at\n            name\n            num_allowed_revotes\n            presentation\n            spoil_ballot_option\n            status\n            tenant_id\n            alias\n        }\n    }\n"): (typeof documents)["\n    query GetElections($electionIds: [uuid!]!) {\n        sequent_backend_election(where: {id: {_in: $electionIds}}) {\n            annotations\n            created_at\n            description\n            election_event_id\n            eml\n            id\n            is_consolidated_ballot_encoding\n            labels\n            last_updated_at\n            name\n            num_allowed_revotes\n            presentation\n            spoil_ballot_option\n            status\n            tenant_id\n            alias\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetSupportMaterials($electionEventId: uuid!, $tenantId: uuid!) {\n        sequent_backend_support_material(\n            where: {\n                _and: {\n                    is_hidden: {_eq: false}\n                    election_event_id: {_eq: $electionEventId}\n                    tenant_id: {_eq: $tenantId}\n                }\n            }\n        ) {\n            data\n            document_id\n            id\n            annotations\n            created_at\n            election_event_id\n            kind\n            labels\n            last_updated_at\n            tenant_id\n        }\n    }\n"): (typeof documents)["\n    query GetSupportMaterials($electionEventId: uuid!, $tenantId: uuid!) {\n        sequent_backend_support_material(\n            where: {\n                _and: {\n                    is_hidden: {_eq: false}\n                    election_event_id: {_eq: $electionEventId}\n                    tenant_id: {_eq: $tenantId}\n                }\n            }\n        ) {\n            data\n            document_id\n            id\n            annotations\n            created_at\n            election_event_id\n            kind\n            labels\n            last_updated_at\n            tenant_id\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation InsertCastVote($electionId: uuid!, $ballotId: String!, $content: String!) {\n        insert_cast_vote(election_id: $electionId, ballot_id: $ballotId, content: $content) {\n            id\n            ballot_id\n            election_id\n            election_event_id\n            tenant_id\n            election_id\n            area_id\n            created_at\n            last_updated_at\n            labels\n            annotations\n            content\n            cast_ballot_signature\n            voter_id_string\n            election_event_id\n        }\n    }\n"): (typeof documents)["\n    mutation InsertCastVote($electionId: uuid!, $ballotId: String!, $content: String!) {\n        insert_cast_vote(election_id: $electionId, ballot_id: $ballotId, content: $content) {\n            id\n            ballot_id\n            election_id\n            election_event_id\n            tenant_id\n            election_id\n            area_id\n            created_at\n            last_updated_at\n            labels\n            annotations\n            content\n            cast_ballot_signature\n            voter_id_string\n            election_event_id\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query listCastVoteMessages(\n        $tenantId: String!\n        $electionEventId: String!\n        $electionId: String\n        $ballotId: String!\n        $limit: Int\n        $offset: Int\n        $orderBy: ElectoralLogOrderBy\n    ) {\n        list_cast_vote_messages(\n            tenant_id: $tenantId\n            election_event_id: $electionEventId\n            election_id: $electionId\n            ballot_id: $ballotId\n            limit: $limit\n            offset: $offset\n            order_by: $orderBy\n        ) {\n            list {\n                statement_timestamp\n                statement_kind\n                ballot_id\n                username\n            }\n            total\n        }\n    }\n"): (typeof documents)["\n    query listCastVoteMessages(\n        $tenantId: String!\n        $electionEventId: String!\n        $electionId: String\n        $ballotId: String!\n        $limit: Int\n        $offset: Int\n        $orderBy: ElectoralLogOrderBy\n    ) {\n        list_cast_vote_messages(\n            tenant_id: $tenantId\n            election_event_id: $electionEventId\n            election_id: $electionId\n            ballot_id: $ballotId\n            limit: $limit\n            offset: $offset\n            order_by: $orderBy\n        ) {\n            list {\n                statement_timestamp\n                statement_kind\n                ballot_id\n                username\n            }\n            total\n        }\n    }\n"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;