-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "sequent_backend"."contest" add column "winning_candidates_num" integer
--  null;
