# Nginx Reverse Proxy Configuration

# Admin Portal
server {
    listen 80;
    server_name admin-remote-test.${DOMAIN};

    location / {
        proxy_pass http://admin-portal:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}

# Voting Portal
# TODO: Uncomment when voting-portal is fixed (currently crashes with 'Command start not found')
#server {
#    listen 80;
#    server_name voting-remote-test.${DOMAIN};
#
#    location / {
#        proxy_pass http://voting-portal:3000;
#        proxy_set_header Host $host;
#        proxy_set_header X-Real-IP $remote_addr;
#        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#        proxy_set_header X-Forwarded-Proto https;
#    }
#}

# Ballot Verifier (points to voting portal)
# TODO: Uncomment when voting-portal is fixed (currently crashes with 'Command start not found')
#server {
#    listen 80;
#    server_name verifier-remote-test.${DOMAIN};
#
#    location / {
#        proxy_pass http://voting-portal:3000;
#        proxy_set_header Host $host;
#        proxy_set_header X-Real-IP $remote_addr;
#        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#        proxy_set_header X-Forwarded-Proto https;
#    }
#}

# # Hasura
server {
    listen 80;
    server_name hasura-remote-test.${DOMAIN};

    location / {
        proxy_pass http://hasura:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}

# Keycloak
server {
    listen 80;
    server_name login-remote-test.${DOMAIN};

    location / {
        proxy_pass http://keycloak:8090;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Forwarded "for=$remote_addr;host=$host;proto=https";
    }
}

# Minio
server {
    listen 80;
    server_name minio-remote-test.${DOMAIN};

    location / {
        proxy_pass http://minio-proxy:9002;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}
