// SPDX-FileCopyrightText: 2026 Sequent Tech Inc <legal@sequentech.io>
//
// SPDX-License-Identifier: AGPL-3.0-only

//! PDF signatures of signing requests (design §6), on top of
//! [`super::pades`].
//!
//! - At report generation, when the action's rule needs signatures,
//!   [`report_signature_page`] appends the signature page with one empty
//!   field per signature. That document is kept as a signing document
//!   only (never released, mailed or encrypted, see [`report_delivery`]);
//!   it is the request's, and its base revision ([`ensure_base_revision`]).
//! - [`prepare_pdf`]: a signer gets the ByteRange digest of the revision
//!   that fills the next empty field. What the revision is built from is
//!   kept; the revision itself is not. The same signer, certificate and
//!   parent revision get the same prepared revision again.
//! - On approval, [`PdfDocumentSigner`] rebuilds that revision on the
//!   latest one, under its row lock, checks the digest, verifies the CMS and
//!   keeps the signed revision. Another signer who went first makes the
//!   revision stale (409): the signer prepares again.
//! - [`latest_signed_document`] is the document as it stands, which an
//!   executed request releases.
//!
//! Election returns generated by the tally pipeline (velvet's
//! `generate_reports`, `post_tally`) don't pass through the report hook.
//!
//! The texts printed on the page are English, like the portal's
//! `signing.actions.<id>.certify` and `signing.signaturePage` strings.

use super::approve::{log_refusal, sign_refusal, DocumentSigner};
use super::certificates::CertificateIdentity;
use super::guard::effective_rule;
use super::log::Actor;
use super::pades::{
    append_signature_page, finalize, prepare_revision, rebuild_revision, signature_fields,
    CmsTrust, PadesError, SignatureAppearance, SignatureFieldSpec, SignaturePageTexts,
};
use super::requests::{
    certificate_names, expire_request, is_overdue, read_request, relock, LOG_THROTTLE_SECONDS,
};
use super::{InvalidReason, SigningCaller, SigningError, SigningResult};
use crate::postgres::document::get_document;
use crate::postgres::monitoring_config::EventRef;
use crate::postgres::signing::{list_signing_approvals, SigningRequestRow};
use crate::postgres::signing_document_revision::{
    count_recent_prepared_revisions, find_reusable_prepared_revision, get_latest_document_revision,
    get_prepared_document_revision, insert_document_revision, signing_document_access_restricted,
    DocumentRevisionRow, NewDocumentRevision, RevisionLock,
};
use crate::services::documents::{
    get_document_as_temp_file, get_document_url, upload_and_return_document,
};
use crate::services::monitoring::config_store::get_live_config;
use crate::tasks::signing_log_outbox::kick_signing_log_outbox;
use anyhow::{anyhow, Context};
use async_trait::async_trait;
use base64::engine::general_purpose::STANDARD as BASE64;
use base64::Engine;
use chrono::{DateTime, SubsecRound, Utc};
use chrono_tz::Tz;
use deadpool_postgres::{Client, Transaction};
use openssl::x509::X509;
use sequent_core::election_config::ReportType;
use sequent_core::signing::{
    CertificateCheckId, DocumentKind, DocumentRevisionState, SigningAction, SigningRequestStatus,
    SigningRule,
};
use sequent_core::util::temp_path::write_into_named_temp_file;
use serde::{Deserialize, Serialize};
use serde_json::json;
use sha2::{Digest, Sha256};
use std::sync::Arc;
use tracing::{instrument, warn};
use uuid::Uuid;

/// The certification sentence above the signature boxes, as the portal's
/// `signing.actions.<id>.certify`. Only actions with a PDF have one.
pub fn certification(action: SigningAction) -> Option<&'static str> {
    match action {
        SigningAction::GenerateElectionReturns => Some(
            "We certify that these election returns are true and correct. Each of us signed them with our digital certificate.",
        ),
        SigningAction::GenerateReports => Some(
            "We certify that this report is true and correct. Each of us signed it with our digital certificate.",
        ),
        _ => None,
    }
}

/// The action whose signatures a report needs, when the rule asks for them.
pub fn report_signing_action(report_type: &ReportType) -> Option<SigningAction> {
    match report_type {
        ReportType::ELECTORAL_RESULTS => Some(SigningAction::GenerateElectionReturns),
        ReportType::INITIALIZATION_REPORT
        | ReportType::PARTICIPATION_REPORT
        | ReportType::MANUAL_VERIFICATION => Some(SigningAction::GenerateReports),
        // The activity logs are a zip of PDFs when generated for real: not
        // signed as a PDF yet (a known gap).
        ReportType::ACTIVITY_LOGS
        | ReportType::BALLOT_IMAGES
        | ReportType::BALLOT_RECEIPT
        | ReportType::CREDENTIALS => None,
    }
}

/// The page's texts for `action`, naming the organization.
pub fn signature_page_texts(
    action: SigningAction,
    organization: &str,
) -> Option<SignaturePageTexts> {
    Some(SignaturePageTexts {
        title: format!("{organization}: digital signatures"),
        certification: certification(action)?.to_owned(),
    })
}

/// One box per signature, filled in the order people sign.
pub fn signature_field_specs(signatures: u16) -> Vec<SignatureFieldSpec> {
    (1..=signatures)
        .map(|n| SignatureFieldSpec {
            label: format!("Signature {n}"),
            tooltip: format!("Signature {n} of {signatures}"),
        })
        .collect()
}

/// The tenant's display name (`tenant.settings.display_name`), else its slug.
pub async fn organization_name(
    hasura_transaction: &Transaction<'_>,
    tenant_id: Uuid,
) -> anyhow::Result<String> {
    hasura_transaction
        .query_opt(
            "SELECT COALESCE(NULLIF(btrim(settings->>'display_name'), ''), slug)
             FROM sequent_backend.tenant WHERE id = $1",
            &[&tenant_id],
        )
        .await
        .context("Error reading the tenant's name")?
        .map(|row| row.try_get(0))
        .transpose()?
        .ok_or_else(|| anyhow!("There is no tenant {tenant_id}"))
}

/// The report with its signature page when the event's rule for `action`
/// needs signatures, else `None` (the report stays as it is). A report with
/// a signature page must not be password-encrypted: that would break the
/// signatures.
#[instrument(skip(hasura_transaction, pdf), err)]
pub async fn report_signature_page(
    hasura_transaction: &Transaction<'_>,
    tenant_id: Uuid,
    election_event_id: Uuid,
    action: SigningAction,
    pdf: &[u8],
) -> anyhow::Result<Option<Vec<u8>>> {
    let rule: SigningRule =
        effective_rule(hasura_transaction, tenant_id, election_event_id, action).await?;
    if !rule.is_required() {
        return Ok(None);
    }
    let organization = organization_name(hasura_transaction, tenant_id).await?;
    let texts = signature_page_texts(action, &organization)
        .ok_or_else(|| anyhow!("A {action} request signs no PDF"))?;
    let base = append_signature_page(pdf, &signature_field_specs(rule.required()), &texts)
        .context("Error adding the signature page")?;
    Ok(Some(base))
}

/// What becomes of a generated report.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ReportDelivery {
    /// Released as the report's document: encrypted when its policy says
    /// so, and mailed when it is a scheduled or a voter's report.
    Release { encrypt: bool, send_email: bool },
    /// Its action needs signatures: kept as a signing document only. It is
    /// not the report's document, not encrypted (that would break the
    /// signatures) and not mailed; the executed request releases the
    /// signed document.
    AwaitSignatures,
}

/// How a report is delivered: `needs_signatures` when it got its
/// signature page.
pub fn report_delivery(
    needs_signatures: bool,
    encrypt_configured: bool,
    send_email: bool,
) -> ReportDelivery {
    if needs_signatures {
        ReportDelivery::AwaitSignatures
    } else {
        ReportDelivery::Release {
            encrypt: encrypt_configured,
            send_email,
        }
    }
}

/// The base of a report that awaits signatures: the signing document a
/// request is started with.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SigningBase {
    pub action: SigningAction,
    pub document_id: Uuid,
    /// Lowercase hex SHA-256: the request subject's `document_sha256`.
    pub sha256: String,
}

/// The visible lines of a signature: the certificate's holder, the
/// account's display name when it says something else, when (in `zone`,
/// else UTC) and the signing code.
pub fn appearance_lines(
    certificate_name: &str,
    display_name: &str,
    signing_time: DateTime<Utc>,
    zone: Option<Tz>,
    code: &str,
) -> Vec<String> {
    let time = match zone {
        Some(zone) => format!(
            "{} {}",
            signing_time
                .with_timezone(&zone)
                .format("%Y-%m-%d %H:%M:%S"),
            zone.name()
        ),
        None => signing_time.format("%Y-%m-%d %H:%M:%S UTC").to_string(),
    };
    let mut lines = vec![format!("Digitally signed by {certificate_name}")];
    if display_name.trim() != certificate_name.trim() {
        lines.push(display_name.to_owned());
    }
    lines.push(format!("Date: {time}"));
    lines.push(format!("Signing code: {code}"));
    lines
}

/// The event's time zone: the one its monitoring settings name, if any.
async fn event_time_zone(
    hasura_transaction: &Transaction<'_>,
    tenant_id: Uuid,
    election_event_id: Uuid,
) -> anyhow::Result<Option<Tz>> {
    let event = EventRef {
        tenant_id,
        election_event_id,
    };
    let zone = get_live_config(hasura_transaction, event)
        .await?
        .and_then(|config| config.assembled.set.settings)
        .map(|settings| settings.time_zone);
    Ok(zone.and_then(|zone| match zone.parse() {
        Ok(zone) => Some(zone),
        Err(_) => {
            warn!("The event's time zone {zone:?} is unknown; signatures print UTC");
            None
        }
    }))
}

/// What a prepared revision prints and records, kept to rebuild it.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct StoredAppearance {
    pub signer_name: String,
    pub signing_time: DateTime<Utc>,
    pub reason: Option<String>,
    pub lines: Vec<String>,
    /// SHA-256 of the certificate the revision was prepared for.
    pub certificate_sha256: String,
}

impl StoredAppearance {
    fn pades(&self) -> SignatureAppearance {
        SignatureAppearance {
            signer_name: self.signer_name.clone(),
            signing_time: self.signing_time,
            reason: self.reason.clone(),
            lines: self.lines.clone(),
        }
    }
}

/// Where the revisions' bytes are kept.
#[async_trait]
pub trait RevisionStore: Send + Sync {
    async fn load(
        &self,
        hasura_transaction: &Transaction<'_>,
        tenant_id: Uuid,
        election_event_id: Uuid,
        document_id: Uuid,
    ) -> anyhow::Result<Vec<u8>>;

    /// The new document's id.
    async fn store(
        &self,
        hasura_transaction: &Transaction<'_>,
        tenant_id: Uuid,
        election_event_id: Uuid,
        file_name: &str,
        content: &[u8],
    ) -> anyhow::Result<Uuid>;

    /// A short-lived link to the document, and its name; `None` when there
    /// is no such document.
    async fn link(
        &self,
        hasura_transaction: &Transaction<'_>,
        tenant_id: Uuid,
        election_event_id: Uuid,
        document_id: Uuid,
    ) -> anyhow::Result<Option<DocumentLink>>;
}

/// Where a signer downloads a document from.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DocumentLink {
    /// A presigned URL that expires shortly.
    pub url: String,
    pub name: Option<String>,
}

/// Private documents in the object storage, like the reports.
#[derive(Debug, Clone, Copy, Default)]
pub struct S3RevisionStore;

#[async_trait]
impl RevisionStore for S3RevisionStore {
    async fn load(
        &self,
        hasura_transaction: &Transaction<'_>,
        tenant_id: Uuid,
        election_event_id: Uuid,
        document_id: Uuid,
    ) -> anyhow::Result<Vec<u8>> {
        let tenant_id = tenant_id.to_string();
        let document = get_document(
            hasura_transaction,
            &tenant_id,
            Some(election_event_id.to_string()),
            &document_id.to_string(),
        )
        .await?
        .ok_or_else(|| anyhow!("There is no document {document_id}"))?;
        let file = get_document_as_temp_file(&tenant_id, &document).await?;
        std::fs::read(file.path()).context("Error reading the document")
    }

    async fn store(
        &self,
        hasura_transaction: &Transaction<'_>,
        tenant_id: Uuid,
        election_event_id: Uuid,
        file_name: &str,
        content: &[u8],
    ) -> anyhow::Result<Uuid> {
        let (_temp_path, path, size) =
            write_into_named_temp_file(&content.to_vec(), "signed-revision-", ".pdf")?;
        let document = upload_and_return_document(
            hasura_transaction,
            &path,
            size,
            "application/pdf",
            &tenant_id.to_string(),
            Some(election_event_id.to_string()),
            file_name,
            None,
            false,
        )
        .await?;
        Uuid::parse_str(&document.id).context("The stored document's id is not a UUID")
    }

    async fn link(
        &self,
        hasura_transaction: &Transaction<'_>,
        tenant_id: Uuid,
        election_event_id: Uuid,
        document_id: Uuid,
    ) -> anyhow::Result<Option<DocumentLink>> {
        let (tenant_id, election_event_id, document_id) = (
            tenant_id.to_string(),
            election_event_id.to_string(),
            document_id.to_string(),
        );
        let Some(document) = get_document(
            hasura_transaction,
            &tenant_id,
            Some(election_event_id.clone()),
            &document_id,
        )
        .await?
        else {
            return Ok(None);
        };
        let url = get_document_url(
            hasura_transaction,
            &tenant_id,
            Some(&election_event_id),
            &document_id,
        )
        .await?;
        Ok(url.map(|url| DocumentLink {
            url,
            name: document.name,
        }))
    }
}

fn sha256_hex(bytes: &[u8]) -> String {
    hex::encode(Sha256::digest(bytes))
}

fn sha256_bytes(text: Option<&str>, what: &str) -> SigningResult<[u8; 32]> {
    let bytes = hex::decode(text.unwrap_or_default())
        .ok()
        .and_then(|bytes| <[u8; 32]>::try_from(bytes).ok())
        .ok_or_else(|| anyhow!("The prepared revision's {what} is not a SHA-256"))?;
    Ok(bytes)
}

/// How a PAdES failure is answered: a stale revision is prepared again, a
/// signature or revision that doesn't match is refused (`signature`).
fn pades_failure(error: PadesError) -> SigningError {
    match error {
        PadesError::StaleRevision => SigningError::StaleRevision(
            "Another signature came first: prepare the document again.".into(),
        ),
        PadesError::RevisionMismatch
        | PadesError::CmsVerification(_)
        | PadesError::CmsTooLarge { .. } => SigningError::Refused {
            check: CertificateCheckId::Signature,
            message: format!("The PDF signature was refused: {error}"),
            other_holder: None,
        },
        PadesError::FieldNotFound(name) => SigningError::invalid(
            InvalidReason::DocumentFields,
            format!(
                "The document has no signature field {name} for this signature: generate it again."
            ),
        ),
        other => SigningError::Internal(anyhow!(other)),
    }
}

/// A revision's bytes, which must be the ones it records.
async fn load_revision(
    hasura_transaction: &Transaction<'_>,
    store: &dyn RevisionStore,
    revision: &DocumentRevisionRow,
) -> SigningResult<Vec<u8>> {
    let document_id = revision
        .document_id
        .ok_or_else(|| anyhow!("Revision {} has no document", revision.revision))?;
    let bytes = store
        .load(
            hasura_transaction,
            revision.tenant_id,
            revision.election_event_id,
            document_id,
        )
        .await?;
    if sha256_hex(&bytes) != revision.sha256 {
        return Err(SigningError::Internal(anyhow!(
            "Revision {} of request {} is not the document it records",
            revision.revision,
            revision.request_id
        )));
    }
    Ok(bytes)
}

/// Refuses a document whose reading needs more than reading the request.
async fn check_document_access(
    hasura_transaction: &Transaction<'_>,
    request: &SigningRequestRow,
    document_id: Uuid,
) -> SigningResult<()> {
    if signing_document_access_restricted(
        hasura_transaction,
        request.tenant_id,
        request.election_event_id,
        document_id,
    )
    .await?
    {
        return Err(SigningError::invalid(
            InvalidReason::Document,
            "This document is password-protected or holds voter secrets: it can't be signed.",
        ));
    }
    Ok(())
}

/// The request's own document's bytes, checked against `document_sha256`.
async fn load_request_document(
    hasura_transaction: &Transaction<'_>,
    store: &dyn RevisionStore,
    request: &SigningRequestRow,
) -> SigningResult<Vec<u8>> {
    let (Some(document_id), Some(sha256)) = (request.document_id, &request.document_sha256) else {
        return Err(SigningError::invalid(
            InvalidReason::Document,
            format!("Signing request {} has no PDF to sign.", request.code),
        ));
    };
    check_document_access(hasura_transaction, request, document_id).await?;
    let bytes = store
        .load(
            hasura_transaction,
            request.tenant_id,
            request.election_event_id,
            document_id,
        )
        .await?;
    if sha256_hex(&bytes) != *sha256 {
        return Err(SigningError::Internal(anyhow!(
            "The document of request {} is not the one it signs",
            request.id
        )));
    }
    Ok(bytes)
}

/// The document's latest revision, recording the request's own document as
/// its base revision the first time. The base must have one empty
/// signature field per signature the request needs. `base` is the
/// document's bytes when the caller already has them (they are used only
/// when their SHA-256 is the request's `document_sha256`). Call it holding
/// the request's lock (or in the transaction that created the request).
#[instrument(skip_all, fields(request_id = %request.id), err)]
pub async fn ensure_base_revision(
    hasura_transaction: &Transaction<'_>,
    store: &dyn RevisionStore,
    request: &SigningRequestRow,
    base: Option<&[u8]>,
) -> SigningResult<DocumentRevisionRow> {
    if let Some(latest) = get_latest_document_revision(
        hasura_transaction,
        request.tenant_id,
        request.election_event_id,
        request.id,
        RevisionLock::ForUpdate,
    )
    .await?
    {
        return Ok(latest);
    }
    let (Some(document_id), Some(sha256)) = (request.document_id, &request.document_sha256) else {
        return Err(SigningError::invalid(
            InvalidReason::Document,
            format!("Signing request {} has no PDF to sign.", request.code),
        ));
    };
    let bytes = match base {
        Some(bytes) if sha256_hex(bytes) == *sha256 => {
            check_document_access(hasura_transaction, request, document_id).await?;
            bytes.to_vec()
        }
        _ => load_request_document(hasura_transaction, store, request).await?,
    };
    let fields = signature_fields(&bytes).map_err(pades_failure)?;
    let empty = fields.iter().filter(|field| !field.signed).count();
    let needed = usize::try_from(request.required).unwrap_or_default();
    if fields.len() != needed || empty != needed {
        return Err(SigningError::invalid(
            InvalidReason::DocumentFields,
            format!(
                "The document has {empty} empty signature fields of {}; signing request {} needs {needed}. Generate the document again.",
                fields.len(),
                request.code,
            ),
        ));
    }
    Ok(insert_document_revision(
        hasura_transaction,
        &NewDocumentRevision {
            tenant_id: request.tenant_id,
            election_event_id: request.election_event_id,
            request_id: request.id,
            document_id: Some(document_id),
            sha256: sha256.clone(),
            state: DocumentRevisionState::Base,
            prepared_for_user: None,
            byte_range: None,
            field_index: None,
            parent_sha256: None,
            digest_sha256: None,
            appearance: None,
        },
    )
    .await?)
}

/// The request's document as it stands: the latest signed revision, or the
/// base before anyone signed; `None` before the base is recorded. An
/// executed request releases this document.
pub async fn latest_signed_document(
    hasura_transaction: &Transaction<'_>,
    request: &SigningRequestRow,
) -> SigningResult<Option<DocumentRevisionRow>> {
    Ok(get_latest_document_revision(
        hasura_transaction,
        request.tenant_id,
        request.election_event_id,
        request.id,
        RevisionLock::Read,
    )
    .await?)
}

/// The document a request signs, as the signing panel shows it.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct PanelDocument {
    /// The request's own document (a PDF request's base revision, a
    /// transmission's EML): its SHA-256 is the payload's document hash.
    pub url: Option<String>,
    pub name: Option<String>,
    /// For a PDF request, the document as it stands.
    pub revision: Option<DocumentRevisionView>,
}

/// The latest revision of a PDF request's document: the latest signed one,
/// or the base before anyone signed. View only: its hash is not the
/// payload's once someone signed.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct DocumentRevisionView {
    pub revision: i32,
    /// Lowercase hex SHA-256 of the revision's bytes.
    pub sha256: String,
    pub signed_count: i32,
    /// A short-lived link to the revision.
    pub url: Option<String>,
}

/// What a signer's browser signs: the digest of the revision prepared for
/// them, which approving with `revision` completes.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct PdfPrepared {
    pub revision: i32,
    /// The ByteRange digest (SHA-256), base64: the CMS messageDigest.
    pub digest_b64: String,
    /// The time the revision records (`/M`) and prints.
    pub signing_time: DateTime<Utc>,
}

/// A chain's leaf (signing) certificate: the SHA-256 of its DER and its
/// holder's common name.
fn leaf_certificate(chain_pem: &[String]) -> SigningResult<(String, Option<String>)> {
    let invalid = |message: &str| SigningError::invalid(InvalidReason::Input, message);
    let pem = chain_pem
        .first()
        .ok_or_else(|| invalid("chain_pem is empty."))?;
    let certificate = X509::from_pem(pem.as_bytes())
        .map_err(|_| invalid("The signing certificate is not a PEM certificate."))?;
    let der = certificate
        .to_der()
        .context("Error encoding the signing certificate")?;
    Ok((sha256_hex(&der), certificate_names(pem).1))
}

/// What a prepared revision row answers again.
fn prepared_answer(row: &DocumentRevisionRow) -> Option<PdfPrepared> {
    let appearance: StoredAppearance = serde_json::from_value(row.appearance.clone()?).ok()?;
    let digest = hex::decode(row.digest_sha256.as_deref()?).ok()?;
    Some(PdfPrepared {
        revision: row.revision,
        digest_b64: BASE64.encode(digest),
        signing_time: appearance.signing_time,
    })
}

/// How a prepare ends.
enum PrepareStep {
    Prepared(PdfPrepared),
    /// Commit what was logged, then answer the error.
    Refused(SigningError),
}

/// Prepares the revision that fills the caller's signature field: the next
/// empty one, in the order people sign. Answers its digest, for the
/// browser to sign; see the module documentation. Owns its transaction on
/// `client`: a refused prepare is logged (SigningSignatureRefused, at most
/// once per throttle) and committed. `now` is the signing time it records.
#[instrument(skip(client, store, caller, chain_pem), err)]
pub async fn prepare_pdf(
    client: &mut Client,
    store: &dyn RevisionStore,
    caller: &SigningCaller,
    tenant_id: Uuid,
    request_id: Uuid,
    chain_pem: &[String],
    now: DateTime<Utc>,
) -> SigningResult<PdfPrepared> {
    let transaction = client
        .transaction()
        .await
        .context("Error starting the prepare")?;
    let step = prepare_in(
        &transaction,
        store,
        caller,
        tenant_id,
        request_id,
        chain_pem,
        now,
    )
    .await?;
    transaction
        .commit()
        .await
        .context("Error committing the prepare")?;
    match step {
        PrepareStep::Prepared(prepared) => Ok(prepared),
        PrepareStep::Refused(error) => {
            kick_signing_log_outbox();
            Err(error)
        }
    }
}

async fn prepare_in(
    hasura_transaction: &Transaction<'_>,
    store: &dyn RevisionStore,
    caller: &SigningCaller,
    tenant_id: Uuid,
    request_id: Uuid,
    chain_pem: &[String],
    now: DateTime<Utc>,
) -> SigningResult<PrepareStep> {
    // Who may sign: decided before any lock, and logged when refused.
    let found = read_request(hasura_transaction, tenant_id, request_id).await?;
    if let Some((refused, message)) = sign_refusal(hasura_transaction, caller, &found).await? {
        let request = relock(hasura_transaction, &found).await?;
        log_refusal(
            hasura_transaction,
            &request,
            caller,
            &refused.to_string(),
            message,
            None,
        )
        .await?;
        return Ok(PrepareStep::Refused(SigningError::Forbidden(
            message.into(),
        )));
    }
    if found.action.document() != DocumentKind::Pdf {
        return Err(SigningError::invalid(
            InvalidReason::Document,
            format!("A {} request signs no PDF.", found.action),
        ));
    }
    let (certificate_sha256, certificate_name) = leaf_certificate(chain_pem)?;

    // The document as it stands, downloaded before the locks; its SHA-256
    // is checked again under them.
    let early = get_latest_document_revision(
        hasura_transaction,
        tenant_id,
        found.election_event_id,
        found.id,
        RevisionLock::Read,
    )
    .await?;
    let early_bytes = match (&early, found.status) {
        (Some(revision), _) => Some(load_revision(hasura_transaction, store, revision).await?),
        (None, SigningRequestStatus::Waiting) => {
            Some(load_request_document(hasura_transaction, store, &found).await?)
        }
        (None, _) => None,
    };

    let request = relock(hasura_transaction, &found).await?;
    if request.status != SigningRequestStatus::Waiting {
        return Err(SigningError::Closed {
            status: request.status,
            message: format!(
                "Signing request {} is {}; it takes no more signatures.",
                request.code, request.status
            ),
        });
    }
    if is_overdue(hasura_transaction, &request).await? {
        expire_request(hasura_transaction, &request).await?;
        return Ok(PrepareStep::Refused(SigningError::Closed {
            status: SigningRequestStatus::Expired,
            message: format!(
                "Signing request {} expired; it takes no more signatures.",
                request.code
            ),
        }));
    }
    let approvals = list_signing_approvals(
        hasura_transaction,
        tenant_id,
        request.election_event_id,
        request.id,
    )
    .await?;
    if approvals
        .iter()
        .any(|approval| approval.user_id == caller.user_id)
    {
        let message = "You already signed this request.";
        log_refusal(
            hasura_transaction,
            &request,
            caller,
            &CertificateCheckId::AlreadySigned.to_string(),
            message,
            None,
        )
        .await?;
        return Ok(PrepareStep::Refused(SigningError::Refused {
            check: CertificateCheckId::AlreadySigned,
            message: message.into(),
            other_holder: None,
        }));
    }

    let base = match (&early, &early_bytes) {
        (None, Some(bytes)) => Some(bytes.as_slice()),
        _ => None,
    };
    let latest = ensure_base_revision(hasura_transaction, store, &request, base).await?;

    // The same signer, certificate and parent get the same revision.
    if let Some(answer) = find_reusable_prepared_revision(
        hasura_transaction,
        tenant_id,
        request.election_event_id,
        request.id,
        &caller.user_id,
        &certificate_sha256,
        &latest.sha256,
    )
    .await?
    .as_ref()
    .and_then(prepared_answer)
    {
        return Ok(PrepareStep::Prepared(answer));
    }
    // Another certificate on the same parent: not more than once per
    // throttle.
    if count_recent_prepared_revisions(
        hasura_transaction,
        tenant_id,
        request.election_event_id,
        request.id,
        &caller.user_id,
        &latest.sha256,
        LOG_THROTTLE_SECONDS,
    )
    .await?
        > 0
    {
        return Err(SigningError::Conflict(format!(
            "You prepared this document a moment ago; wait {LOG_THROTTLE_SECONDS} seconds to prepare it with another certificate."
        )));
    }

    let latest_bytes = match early_bytes {
        Some(bytes) if sha256_hex(&bytes) == latest.sha256 => bytes,
        _ => load_revision(hasura_transaction, store, &latest).await?,
    };
    let field_index = latest.field_index.map_or(0, |field| field + 1);
    let zone = event_time_zone(hasura_transaction, tenant_id, request.election_event_id).await?;
    let signing_time = now.trunc_subsecs(0);
    let signer_name = certificate_name.unwrap_or_else(|| caller.display_name.clone());
    let appearance = StoredAppearance {
        lines: appearance_lines(
            &signer_name,
            &caller.display_name,
            signing_time,
            zone,
            &request.code,
        ),
        signer_name,
        signing_time,
        reason: certification(request.action).map(str::to_owned),
        certificate_sha256,
    };
    let field = usize::try_from(field_index).context("Invalid signature field")?;
    let prepared =
        prepare_revision(&latest_bytes, field, &appearance.pades()).map_err(pades_failure)?;
    let row = insert_document_revision(
        hasura_transaction,
        &NewDocumentRevision {
            tenant_id,
            election_event_id: request.election_event_id,
            request_id: request.id,
            document_id: None,
            sha256: sha256_hex(prepared.bytes()),
            state: DocumentRevisionState::Prepared,
            prepared_for_user: Some(caller.user_id.clone()),
            byte_range: Some(json!(prepared.byte_range())),
            field_index: Some(field_index),
            parent_sha256: Some(latest.sha256.clone()),
            digest_sha256: Some(hex::encode(prepared.digest_sha256())),
            appearance: Some(
                serde_json::to_value(&appearance).context("Error keeping the appearance")?,
            ),
        },
    )
    .await?;
    Ok(PrepareStep::Prepared(PdfPrepared {
        revision: row.revision,
        digest_b64: BASE64.encode(prepared.digest_sha256()),
        signing_time,
    }))
}

/// The PDF side of approvals: prepares revisions and completes them with
/// the approval's CMS.
pub struct PdfDocumentSigner {
    store: Arc<dyn RevisionStore>,
}

impl PdfDocumentSigner {
    pub fn new(store: Arc<dyn RevisionStore>) -> Self {
        PdfDocumentSigner { store }
    }
}

#[async_trait]
impl DocumentSigner for PdfDocumentSigner {
    /// PDF documents and actions without a document; EML documents come
    /// with transmissions.
    fn supports(&self, kind: DocumentKind) -> bool {
        match kind {
            DocumentKind::Pdf | DocumentKind::NoDocument => true,
            DocumentKind::Eml => false,
        }
    }

    async fn document_bytes(
        &self,
        _hasura_transaction: &Transaction<'_>,
        _request: &SigningRequestRow,
    ) -> anyhow::Result<Option<Vec<u8>>> {
        Ok(None)
    }

    async fn prepare_pdf(
        &self,
        client: &mut Client,
        caller: &SigningCaller,
        tenant_id: Uuid,
        request_id: Uuid,
        chain_pem: &[String],
        now: DateTime<Utc>,
    ) -> SigningResult<PdfPrepared> {
        prepare_pdf(
            client,
            self.store.as_ref(),
            caller,
            tenant_id,
            request_id,
            chain_pem,
            now,
        )
        .await
    }

    /// The request's document (the base of a PDF request) and, for a PDF,
    /// its latest revision.
    async fn panel_document(
        &self,
        hasura_transaction: &Transaction<'_>,
        request: &SigningRequestRow,
    ) -> SigningResult<PanelDocument> {
        let Some(document_id) = request.document_id else {
            return Ok(PanelDocument::default());
        };
        let (tenant_id, event_id) = (request.tenant_id, request.election_event_id);
        // Never a link to a document its readers need more to read.
        if signing_document_access_restricted(hasura_transaction, tenant_id, event_id, document_id)
            .await?
        {
            return Ok(PanelDocument::default());
        }
        let base = self
            .store
            .link(hasura_transaction, tenant_id, event_id, document_id)
            .await?;
        let base_url = base.as_ref().map(|link| link.url.clone());
        let revision = match request.action.document() {
            DocumentKind::Pdf => Some(
                match latest_signed_document(hasura_transaction, request).await? {
                    Some(latest) => {
                        let url = match (latest.state, latest.document_id) {
                            (DocumentRevisionState::Base, _) | (_, None) => base_url.clone(),
                            (_, Some(id)) => self
                                .store
                                .link(hasura_transaction, tenant_id, event_id, id)
                                .await?
                                .map(|link| link.url),
                        };
                        DocumentRevisionView {
                            revision: latest.revision,
                            sha256: latest.sha256,
                            signed_count: latest.field_index.map_or(0, |field| field + 1),
                            url,
                        }
                    }
                    None => DocumentRevisionView {
                        revision: 0,
                        sha256: request.document_sha256.clone().unwrap_or_default(),
                        signed_count: 0,
                        url: base_url.clone(),
                    },
                },
            ),
            DocumentKind::Eml | DocumentKind::NoDocument => None,
        };
        Ok(PanelDocument {
            url: base_url,
            name: base.and_then(|link| link.name),
            revision,
        })
    }

    /// Completes the revision prepared for `signer` with `pdf_cms`, on the
    /// latest revision, which stays locked until the approval commits.
    #[instrument(skip_all, fields(request_id = %request.id), err)]
    async fn embed(
        &self,
        hasura_transaction: &Transaction<'_>,
        request: &SigningRequestRow,
        signer: &Actor,
        certificate: &CertificateIdentity,
        pdf_cms: Option<&[u8]>,
        revision: Option<i32>,
    ) -> SigningResult<()> {
        let invalid = |message: String| SigningError::invalid(InvalidReason::Document, message);
        if request.action.document() != DocumentKind::Pdf {
            return match pdf_cms {
                Some(_) => Err(invalid(format!(
                    "Signing request {} signs no PDF.",
                    request.code
                ))),
                None => Ok(()),
            };
        }
        if request.document_id.is_none() {
            return Err(invalid(format!(
                "Signing request {} has no PDF to sign.",
                request.code
            )));
        }
        let (Some(pdf_cms), Some(revision)) = (pdf_cms, revision) else {
            return Err(invalid(
                "A signature of this request carries the PDF signature and the revision prepared for it."
                    .into(),
            ));
        };
        let (tenant_id, event_id) = (request.tenant_id, request.election_event_id);
        let not_prepared = || SigningError::Refused {
            check: CertificateCheckId::Signature,
            message: format!("Revision {revision} was not prepared for you; prepare the document."),
            other_holder: None,
        };
        let latest = get_latest_document_revision(
            hasura_transaction,
            tenant_id,
            event_id,
            request.id,
            RevisionLock::ForUpdate,
        )
        .await?
        .ok_or_else(not_prepared)?;
        let prepared = get_prepared_document_revision(
            hasura_transaction,
            tenant_id,
            event_id,
            request.id,
            revision,
            &signer.user_id,
        )
        .await?
        .ok_or_else(not_prepared)?;
        if prepared.parent_sha256.as_deref() != Some(latest.sha256.as_str()) {
            return Err(pades_failure(PadesError::StaleRevision));
        }
        let appearance: StoredAppearance = serde_json::from_value(
            prepared
                .appearance
                .clone()
                .ok_or_else(|| anyhow!("The prepared revision has no appearance"))?,
        )
        .context("Error reading the prepared appearance")?;
        let signer_certificate = X509::from_pem(certificate.pem.as_bytes())
            .context("Error reading the approval's certificate")?;
        let signer_der = signer_certificate
            .to_der()
            .context("Error encoding the approval's certificate")?;
        if appearance.certificate_sha256 != sha256_hex(&signer_der) {
            return Err(SigningError::Refused {
                check: CertificateCheckId::Signature,
                message: "The document was prepared for another certificate.".into(),
                other_holder: None,
            });
        }
        let field_index = prepared
            .field_index
            .and_then(|field| usize::try_from(field).ok())
            .ok_or_else(|| anyhow!("The prepared revision has no signature field"))?;
        let latest_bytes = load_revision(hasura_transaction, self.store.as_ref(), &latest).await?;
        let rebuilt = rebuild_revision(
            &latest_bytes,
            sha256_bytes(prepared.parent_sha256.as_deref(), "parent")?,
            field_index,
            &appearance.pades(),
            sha256_bytes(prepared.digest_sha256.as_deref(), "digest")?,
        )
        .map_err(pades_failure)?;
        let signed = finalize(
            &rebuilt,
            &latest_bytes,
            pdf_cms,
            &signer_certificate,
            &CmsTrust::SignerOnly,
        )
        .map_err(pades_failure)?;
        let document_id = self
            .store
            .store(
                hasura_transaction,
                tenant_id,
                event_id,
                &format!("{}-signature-{}.pdf", request.code, field_index + 1),
                &signed,
            )
            .await?;
        insert_document_revision(
            hasura_transaction,
            &NewDocumentRevision {
                tenant_id,
                election_event_id: event_id,
                request_id: request.id,
                document_id: Some(document_id),
                sha256: sha256_hex(&signed),
                state: DocumentRevisionState::Signed,
                prepared_for_user: Some(signer.user_id.clone()),
                byte_range: Some(json!(rebuilt.byte_range())),
                field_index: prepared.field_index,
                parent_sha256: prepared.parent_sha256.clone(),
                digest_sha256: prepared.digest_sha256.clone(),
                appearance: prepared.appearance.clone(),
            },
        )
        .await?;
        Ok(())
    }
}
