name: Build and Deploy (Airgap)
on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-22.04 # Locked to specific version
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out repository
        run: |
          git clone "http://oauth2:${{ secrets.GITHUB_TOKEN }}@gitea.gitea:3000/${{ github.repository }}.git" .
          git checkout "${{ github.sha }}"

      - name: Login to Local Gitea Registry
        run: echo "admin123" | docker login http://gitea.gitea:3000 -u "admin" --password-stdin

      - name: Build and Push Harvest
        run: |
          docker build -f ./packages/harvest/Dockerfile.airgap -t gitea.gitea:3000/step/harvest:latest ./packages
          docker push gitea.gitea:3000/step/harvest:latest

      - name: Build and Push Windmill
        run: |
          docker build -f ./packages/windmill/Dockerfile.airgap -t gitea.gitea:3000/step/windmill:latest ./packages
          docker push gitea.gitea:3000/step/windmill:latest

      - name: Build and Push Admin Portal
        run: |
          docker build -f ./packages/Dockerfile.airgap --build-arg SPA_NAME=admin-portal -t gitea.gitea:3000/step/admin-portal:latest ./packages
          docker push gitea.gitea:3000/step/admin-portal:latest

      - name: Rollout Update
        run: |
          kubectl rollout restart deployment/harvest -n step-apps
          kubectl rollout restart deployment/windmill -n step-apps
          kubectl rollout restart deployment/admin-portal -n step-apps
