name: Build and Deploy (Airgap)
on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-22.04 # Locked to specific version
    steps:
      - name: Check out repository
        uses: http://gitea.gitea:3000/actions/checkout@v3

      - name: Login to Local Gitea Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login gitea.gitea:3000 -u "${{ github.actor }}" --password-stdin

      - name: Build and Push Harvest
        run: |
          docker build -f ./packages/harvest/Dockerfile -t gitea.gitea:3000/step/harvest:latest ./packages
          docker push gitea.gitea:3000/step/harvest:latest

      - name: Build and Push Windmill
        run: |
          docker build -f ./packages/windmill/Dockerfile -t gitea.gitea:3000/step/windmill:latest ./packages
          docker push gitea.gitea:3000/step/windmill:latest

      - name: Build and Push Admin Portal
        run: |
          docker build -f ./packages/Dockerfile.prod --build-arg SPA_NAME=admin-portal -t gitea.gitea:3000/step/admin-portal:latest ./packages
          docker push gitea.gitea:3000/step/admin-portal:latest

      - name: Rollout Update
        run: |
          kubectl rollout restart deployment/harvest -n step-apps
          kubectl rollout restart deployment/windmill -n step-apps
          kubectl rollout restart deployment/admin-portal -n step-apps
