/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 */
const documents = {
    "\n    mutation CheckPrivateKey(\n        $electionEventId: String!\n        $keysCeremonyId: String!\n        $privateKeyBase64: String!\n    ) {\n        check_private_key(\n            object: {\n                election_event_id: $electionEventId\n                keys_ceremony_id: $keysCeremonyId\n                private_key_base64: $privateKeyBase64\n            }\n        ) {\n            is_valid\n        }\n    }\n": types.CheckPrivateKeyDocument,
    "\n    mutation CreateKeysCeremony(\n        $electionEventId: String!\n        $threshold: Int!\n        $trusteeNames: [String!]\n    ) {\n        create_keys_ceremony(\n            object: {\n                election_event_id: $electionEventId\n                threshold: $threshold\n                trustee_names: $trusteeNames\n            }\n        ) {\n            keys_ceremony_id\n        }\n    }\n": types.CreateKeysCeremonyDocument,
    "\n    mutation CreateRole($tenantId: String!, $role: KeycloakRole2!) {\n        create_role(tenant_id: $tenantId, role: $role) {\n            id\n            name\n            permissions\n            access\n            attributes\n            client_roles\n        }\n    }\n": types.CreateRoleDocument,
    "\n    mutation CreateScheduledEvent(\n        $tenantId: String!\n        $electionEventId: uuid\n        $eventProcessor: String!\n        $cronConfig: String\n        $eventPayload: jsonb!\n    ) {\n        createScheduledEvent(\n            tenant_id: $tenantId\n            election_event_id: $electionEventId\n            event_processor: $eventProcessor\n            cron_config: $cronConfig\n            event_payload: $eventPayload\n        ) {\n            id\n        }\n    }\n": types.CreateScheduledEventDocument,
    "\n    mutation CreateTallyCeremony($election_event_id: uuid!, $election_ids: [uuid!]!) {\n        create_tally_ceremony(election_event_id: $election_event_id, election_ids: $election_ids) {\n            tally_session_id\n        }\n    }\n": types.CreateTallyCeremonyDocument,
    "\n    mutation CreateUser($tenantId: String!, $electionEventId: String, $user: KeycloakUser2!) {\n        create_user(tenant_id: $tenantId, election_event_id: $electionEventId, user: $user) {\n            id\n            attributes\n            email\n            email_verified\n            enabled\n            first_name\n            last_name\n            username\n        }\n    }\n": types.CreateUserDocument,
    "\n    mutation delete_area_contests($tenantId: uuid!, $area: uuid!) {\n        delete_sequent_backend_area_contest(\n            where: {_and: {area_id: {_eq: $area}, tenant_id: {_eq: $tenantId}}}\n        ) {\n            returning {\n                id\n            }\n        }\n    }\n": types.Delete_Area_ContestsDocument,
    "\n    mutation DeleteRole($tenantId: String!, $roleId: String!) {\n        delete_role(tenant_id: $tenantId, role_id: $roleId) {\n            id\n        }\n    }\n": types.DeleteRoleDocument,
    "\n    mutation DeleteRolePermission($tenantId: String!, $roleId: String!, $permissionName: String!) {\n        delete_role_permission(\n            tenant_id: $tenantId\n            role_id: $roleId\n            permission_name: $permissionName\n        ) {\n            id\n        }\n    }\n": types.DeleteRolePermissionDocument,
    "\n    mutation DeleteUser($tenantId: String!, $electionEventId: String, $userId: String!) {\n        delete_user(tenant_id: $tenantId, election_event_id: $electionEventId, user_id: $userId) {\n            id\n        }\n    }\n": types.DeleteUserDocument,
    "\n    mutation DeleteUserRole($tenantId: String!, $userId: String!, $roleId: String!) {\n        delete_user_role(tenant_id: $tenantId, user_id: $userId, role_id: $roleId) {\n            id\n        }\n    }\n": types.DeleteUserRoleDocument,
    "\n    mutation EditUser($body: EditUsersInput!) {\n        edit_user(body: $body) {\n            attributes\n            email\n            email_verified\n            enabled\n            first_name\n            groups\n            id\n            last_name\n            username\n        }\n    }\n": types.EditUserDocument,
    "\n    query FetchDocument($tenantId: String!, $electionEventId: String!, $documentId: String!) {\n        fetchDocument(\n            tenant_id: $tenantId\n            election_event_id: $electionEventId\n            document_id: $documentId\n        ) {\n            url\n        }\n    }\n": types.FetchDocumentDocument,
    "\n    mutation GenerateBallotPublication($electionEventId: uuid!, $electionId: uuid) {\n        generate_ballot_publication(election_event_id: $electionEventId, election_id: $electionId) {\n            ballot_publication_id\n        }\n    }\n": types.GenerateBallotPublicationDocument,
    "\n    query get_area_with_area_contests($areaId: uuid!, $electionEventId: uuid!) {\n        sequent_backend_area_contest(\n            where: {_and: {area_id: {_eq: $areaId}, election_event_id: {_eq: $electionEventId}}}\n        ) {\n            contest {\n                name\n            }\n            id\n        }\n    }\n": types.Get_Area_With_Area_ContestsDocument,
    "\n    query sequent_backend_area_extended($electionEventId: uuid!, $areaId: uuid!) {\n        sequent_backend_area_contest(\n            where: {_and: {election_event_id: {_eq: $electionEventId}, area_id: {_eq: $areaId}}}\n        ) {\n            contest {\n                id\n                name\n            }\n        }\n    }\n": types.Sequent_Backend_Area_ExtendedDocument,
    "\n    query GetBallotStyles {\n        sequent_backend_ballot_style {\n            id\n            election_id\n            election_event_id\n            status\n            tenant_id\n            ballot_eml\n            ballot_signature\n            created_at\n            area_id\n            annotations\n            labels\n            last_updated_at\n        }\n    }\n": types.GetBallotStylesDocument,
    "\n    query GetCastVotesByDateRange(\n        $electionEventId: uuid!\n        $tenantId: uuid!\n        $startDate: timestamptz\n        $endDate: timestamptz\n    ) {\n        sequent_backend_cast_vote(\n            where: {\n                _and: {\n                    election_event_id: {_eq: $electionEventId}\n                    tenant_id: {_eq: $tenantId}\n                    created_at: {_gte: $startDate, _lte: $endDate}\n                }\n            }\n        ) {\n            id\n            tenant_id\n            election_id\n            area_id\n            created_at\n            last_updated_at\n            election_event_id\n        }\n    }\n": types.GetCastVotesByDateRangeDocument,
    "\n    query GetCastVotes($electionEventId: uuid!, $tenantId: uuid!) {\n        sequent_backend_cast_vote(\n            where: {_and: {tenant_id: {_eq: $tenantId}, election_event_id: {_eq: $electionEventId}}}\n        ) {\n            id\n            tenant_id\n            election_id\n            area_id\n            created_at\n            last_updated_at\n            election_event_id\n        }\n    }\n": types.GetCastVotesDocument,
    "\n    query GetCastVotesForElection($electionEventId: uuid!, $electionId: uuid!, $tenantId: uuid!) {\n        sequent_backend_cast_vote(\n            where: {\n                _and: {\n                    tenant_id: {_eq: $tenantId}\n                    election_event_id: {_eq: $electionEventId}\n                    election_id: {_eq: $electionId}\n                }\n            }\n        ) {\n            id\n            tenant_id\n            election_id\n            area_id\n            created_at\n            last_updated_at\n            election_event_id\n        }\n    }\n": types.GetCastVotesForElectionDocument,
    "\n    query GetElectionEventStats($electionEventId: uuid, $tenantId: uuid) {\n        castVotes: sequent_backend_cast_vote_aggregate(\n            where: {election_event_id: {_eq: $electionEventId}, tenant_id: {_eq: $tenantId}}\n        ) {\n            aggregate {\n                count\n            }\n        }\n        elections: sequent_backend_election_aggregate(\n            where: {election_event_id: {_eq: $electionEventId}, tenant_id: {_eq: $tenantId}}\n        ) {\n            aggregate {\n                count\n            }\n        }\n        areas: sequent_backend_area_aggregate(\n            where: {election_event_id: {_eq: $electionEventId}, tenant_id: {_eq: $tenantId}}\n        ) {\n            aggregate {\n                count\n            }\n        }\n    }\n": types.GetElectionEventStatsDocument,
    "\n    query election_events_tree($tenantId: uuid!, $isArchived: Boolean!) {\n        sequent_backend_election_event(\n            where: {is_archived: {_eq: $isArchived}, _and: {tenant_id: {_eq: $tenantId}}}\n        ) {\n            id\n            name\n            is_archived\n            elections {\n                id\n                name\n                election_event_id\n                image_document_id\n                contests {\n                    id\n                    name\n                    election_event_id\n                    election_id\n                    candidates {\n                        id\n                        name\n                        contest_id\n                        election_event_id\n                    }\n                }\n            }\n        }\n    }\n": types.Election_Events_TreeDocument,
    "\n    query GetElections {\n        sequent_backend_election {\n            annotations\n            created_at\n            dates\n            description\n            election_event_id\n            eml\n            id\n            is_consolidated_ballot_encoding\n            labels\n            last_updated_at\n            name\n            num_allowed_revotes\n            presentation\n            spoil_ballot_option\n            status\n            tenant_id\n        }\n    }\n": types.GetElectionsDocument,
    "\n    query GetEventExecution($tenantId: uuid!, $scheduledEventId: uuid!) {\n        sequent_backend_event_execution(\n            where: {scheduled_event_id: {_eq: $scheduledEventId}, tenant_id: {_eq: $tenantId}}\n        ) {\n            id\n            tenant_id\n            election_event_id\n            scheduled_event_id\n            labels\n            annotations\n            execution_state\n            execution_payload\n            result_payload\n            started_at\n            ended_at\n        }\n    }\n": types.GetEventExecutionDocument,
    "\n        query getPermissions(\n            $tenant_id: String! = \"\"\n        ) {\n            get_permissions(body: {\n                tenant_id: $tenant_id\n            }) {\n                items {\n                    id\n                    attributes\n                    container_id\n                    description\n                    name\n                }\n                total {\n                    aggregate {\n                        count\n                    }\n                }\n            }\n        }\n        ": types.GetPermissionsDocument,
    "\n    mutation GetPrivateKey($electionEventId: String!, $keysCeremonyId: String!) {\n        get_private_key(\n            object: {election_event_id: $electionEventId, keys_ceremony_id: $keysCeremonyId}\n        ) {\n            private_key_base64\n        }\n    }\n": types.GetPrivateKeyDocument,
    "\n        query getRoles(\n            $tenant_id: String! = \"\"\n        ) {\n            get_roles(body: {\n                tenant_id: $tenant_id\n            }) {\n                items {\n                    id\n                    name\n                    permissions\n                    access\n                    attributes\n                    client_roles\n                }\n                total {\n                    aggregate {\n                        count\n                    }\n                }\n            }\n        }\n        ": types.GetRolesDocument,
    "\n    query TrusteeNames($trustees: [uuid!]!) {\n        sequent_backend_trustee(where: {id: {_in: $trustees}}) {\n            name\n        }\n    }\n": types.TrusteeNamesDocument,
    "\n    mutation GetUploadUrl($name: String!, $media_type: String!, $size: Int!) {\n        get_upload_url(name: $name, media_type: $media_type, size: $size) {\n            url\n            document_id\n        }\n    }\n": types.GetUploadUrlDocument,
    "\n    mutation insert_area_contests($areas: [sequent_backend_area_contest_insert_input!]!) {\n        insert_sequent_backend_area_contest(objects: $areas) {\n            returning {\n                id\n            }\n        }\n    }\n": types.Insert_Area_ContestsDocument,
    "\n    mutation InsertCastVote(\n        $id: uuid\n        $electionId: uuid\n        $electionEventId: uuid\n        $tenantId: uuid\n        $content: String!\n    ) {\n        insert_sequent_backend_cast_vote(\n            objects: {\n                id: $id\n                election_id: $electionId\n                election_event_id: $electionEventId\n                tenant_id: $tenantId\n                content: $content\n            }\n        ) {\n            returning {\n                id\n                election_id\n                election_event_id\n                tenant_id\n                voter_id_string\n            }\n        }\n    }\n": types.InsertCastVoteDocument,
    "\n    mutation CreateElectionEvent($electionEvent: CreateElectionEventInput!) {\n        insertElectionEvent(object: $electionEvent) {\n            id\n        }\n    }\n": types.CreateElectionEventDocument,
    "\n    mutation InsertTenant($slug: String!) {\n        insertTenant(slug: $slug) {\n            id\n            slug\n        }\n    }\n": types.InsertTenantDocument,
    "\n    query listPgaudit($limit: Int, $offset: Int, $order_by: PgAuditOrderBy) {\n        listPgaudit(limit: $limit, offset: $offset, order_by: $order_by) {\n            items {\n                id\n                audit_type\n                class\n                command\n                dbname\n                id\n                server_timestamp\n                session_id\n                statement\n                user\n            }\n            total {\n                aggregate {\n                    count\n                }\n            }\n        }\n    }\n": types.ListPgauditDocument,
    "\n    query ListUserRoles($tenantId: String!, $userId: String!, $electionEventId: String) {\n        list_user_roles(\n            tenant_id: $tenantId\n            user_id: $userId\n            election_event_id: $electionEventId\n        ) {\n            id\n            name\n            permissions\n            access\n            attributes\n            client_roles\n        }\n    }\n": types.ListUserRolesDocument,
    "\n    mutation PublishBallot($electionEventId: uuid!, $ballotPublicationId: uuid!) {\n        publish_ballot(\n            election_event_id: $electionEventId\n            ballot_publication_id: $ballotPublicationId\n        ) {\n            ballot_publication_id\n        }\n    }\n": types.PublishBallotDocument,
    "\n    mutation RestorePrivateKey(\n        $electionEventId: String!\n        $tallySessionId: String!\n        $privateKeyBase64: String!\n    ) {\n        restore_private_key(object: {\n            election_event_id: $electionEventId\n            tally_session_id: $tallySessionId\n            private_key_base64: $privateKeyBase64\n        }) {\n            is_valid\n        }\n    }\n": types.RestorePrivateKeyDocument,
    "\n    mutation SetRolePermission($tenantId: String!, $roleId: String!, $permissionName: String!) {\n        set_role_permission(\n            tenant_id: $tenantId\n            role_id: $roleId\n            permission_name: $permissionName\n        ) {\n            id\n        }\n    }\n": types.SetRolePermissionDocument,
    "\n    mutation SetUserRole($tenantId: String!, $userId: String!, $roleId: String!) {\n        set_user_role(tenant_id: $tenantId, user_id: $userId, role_id: $roleId) {\n            id\n        }\n    }\n": types.SetUserRoleDocument,
    "\n    mutation UpdateTallyCeremony(\n        $election_event_id: uuid!\n        $tally_session_id: uuid!\n        $status: String!\n    ) {\n        update_tally_ceremony(\n            election_event_id: $election_event_id\n            tally_session_id: $tally_session_id\n            status: $status\n        ) {\n            tally_session_id\n        }\n    }\n": types.UpdateTallyCeremonyDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation CheckPrivateKey(\n        $electionEventId: String!\n        $keysCeremonyId: String!\n        $privateKeyBase64: String!\n    ) {\n        check_private_key(\n            object: {\n                election_event_id: $electionEventId\n                keys_ceremony_id: $keysCeremonyId\n                private_key_base64: $privateKeyBase64\n            }\n        ) {\n            is_valid\n        }\n    }\n"): (typeof documents)["\n    mutation CheckPrivateKey(\n        $electionEventId: String!\n        $keysCeremonyId: String!\n        $privateKeyBase64: String!\n    ) {\n        check_private_key(\n            object: {\n                election_event_id: $electionEventId\n                keys_ceremony_id: $keysCeremonyId\n                private_key_base64: $privateKeyBase64\n            }\n        ) {\n            is_valid\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation CreateKeysCeremony(\n        $electionEventId: String!\n        $threshold: Int!\n        $trusteeNames: [String!]\n    ) {\n        create_keys_ceremony(\n            object: {\n                election_event_id: $electionEventId\n                threshold: $threshold\n                trustee_names: $trusteeNames\n            }\n        ) {\n            keys_ceremony_id\n        }\n    }\n"): (typeof documents)["\n    mutation CreateKeysCeremony(\n        $electionEventId: String!\n        $threshold: Int!\n        $trusteeNames: [String!]\n    ) {\n        create_keys_ceremony(\n            object: {\n                election_event_id: $electionEventId\n                threshold: $threshold\n                trustee_names: $trusteeNames\n            }\n        ) {\n            keys_ceremony_id\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation CreateRole($tenantId: String!, $role: KeycloakRole2!) {\n        create_role(tenant_id: $tenantId, role: $role) {\n            id\n            name\n            permissions\n            access\n            attributes\n            client_roles\n        }\n    }\n"): (typeof documents)["\n    mutation CreateRole($tenantId: String!, $role: KeycloakRole2!) {\n        create_role(tenant_id: $tenantId, role: $role) {\n            id\n            name\n            permissions\n            access\n            attributes\n            client_roles\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation CreateScheduledEvent(\n        $tenantId: String!\n        $electionEventId: uuid\n        $eventProcessor: String!\n        $cronConfig: String\n        $eventPayload: jsonb!\n    ) {\n        createScheduledEvent(\n            tenant_id: $tenantId\n            election_event_id: $electionEventId\n            event_processor: $eventProcessor\n            cron_config: $cronConfig\n            event_payload: $eventPayload\n        ) {\n            id\n        }\n    }\n"): (typeof documents)["\n    mutation CreateScheduledEvent(\n        $tenantId: String!\n        $electionEventId: uuid\n        $eventProcessor: String!\n        $cronConfig: String\n        $eventPayload: jsonb!\n    ) {\n        createScheduledEvent(\n            tenant_id: $tenantId\n            election_event_id: $electionEventId\n            event_processor: $eventProcessor\n            cron_config: $cronConfig\n            event_payload: $eventPayload\n        ) {\n            id\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation CreateTallyCeremony($election_event_id: uuid!, $election_ids: [uuid!]!) {\n        create_tally_ceremony(election_event_id: $election_event_id, election_ids: $election_ids) {\n            tally_session_id\n        }\n    }\n"): (typeof documents)["\n    mutation CreateTallyCeremony($election_event_id: uuid!, $election_ids: [uuid!]!) {\n        create_tally_ceremony(election_event_id: $election_event_id, election_ids: $election_ids) {\n            tally_session_id\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation CreateUser($tenantId: String!, $electionEventId: String, $user: KeycloakUser2!) {\n        create_user(tenant_id: $tenantId, election_event_id: $electionEventId, user: $user) {\n            id\n            attributes\n            email\n            email_verified\n            enabled\n            first_name\n            last_name\n            username\n        }\n    }\n"): (typeof documents)["\n    mutation CreateUser($tenantId: String!, $electionEventId: String, $user: KeycloakUser2!) {\n        create_user(tenant_id: $tenantId, election_event_id: $electionEventId, user: $user) {\n            id\n            attributes\n            email\n            email_verified\n            enabled\n            first_name\n            last_name\n            username\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation delete_area_contests($tenantId: uuid!, $area: uuid!) {\n        delete_sequent_backend_area_contest(\n            where: {_and: {area_id: {_eq: $area}, tenant_id: {_eq: $tenantId}}}\n        ) {\n            returning {\n                id\n            }\n        }\n    }\n"): (typeof documents)["\n    mutation delete_area_contests($tenantId: uuid!, $area: uuid!) {\n        delete_sequent_backend_area_contest(\n            where: {_and: {area_id: {_eq: $area}, tenant_id: {_eq: $tenantId}}}\n        ) {\n            returning {\n                id\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation DeleteRole($tenantId: String!, $roleId: String!) {\n        delete_role(tenant_id: $tenantId, role_id: $roleId) {\n            id\n        }\n    }\n"): (typeof documents)["\n    mutation DeleteRole($tenantId: String!, $roleId: String!) {\n        delete_role(tenant_id: $tenantId, role_id: $roleId) {\n            id\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation DeleteRolePermission($tenantId: String!, $roleId: String!, $permissionName: String!) {\n        delete_role_permission(\n            tenant_id: $tenantId\n            role_id: $roleId\n            permission_name: $permissionName\n        ) {\n            id\n        }\n    }\n"): (typeof documents)["\n    mutation DeleteRolePermission($tenantId: String!, $roleId: String!, $permissionName: String!) {\n        delete_role_permission(\n            tenant_id: $tenantId\n            role_id: $roleId\n            permission_name: $permissionName\n        ) {\n            id\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation DeleteUser($tenantId: String!, $electionEventId: String, $userId: String!) {\n        delete_user(tenant_id: $tenantId, election_event_id: $electionEventId, user_id: $userId) {\n            id\n        }\n    }\n"): (typeof documents)["\n    mutation DeleteUser($tenantId: String!, $electionEventId: String, $userId: String!) {\n        delete_user(tenant_id: $tenantId, election_event_id: $electionEventId, user_id: $userId) {\n            id\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation DeleteUserRole($tenantId: String!, $userId: String!, $roleId: String!) {\n        delete_user_role(tenant_id: $tenantId, user_id: $userId, role_id: $roleId) {\n            id\n        }\n    }\n"): (typeof documents)["\n    mutation DeleteUserRole($tenantId: String!, $userId: String!, $roleId: String!) {\n        delete_user_role(tenant_id: $tenantId, user_id: $userId, role_id: $roleId) {\n            id\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation EditUser($body: EditUsersInput!) {\n        edit_user(body: $body) {\n            attributes\n            email\n            email_verified\n            enabled\n            first_name\n            groups\n            id\n            last_name\n            username\n        }\n    }\n"): (typeof documents)["\n    mutation EditUser($body: EditUsersInput!) {\n        edit_user(body: $body) {\n            attributes\n            email\n            email_verified\n            enabled\n            first_name\n            groups\n            id\n            last_name\n            username\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query FetchDocument($tenantId: String!, $electionEventId: String!, $documentId: String!) {\n        fetchDocument(\n            tenant_id: $tenantId\n            election_event_id: $electionEventId\n            document_id: $documentId\n        ) {\n            url\n        }\n    }\n"): (typeof documents)["\n    query FetchDocument($tenantId: String!, $electionEventId: String!, $documentId: String!) {\n        fetchDocument(\n            tenant_id: $tenantId\n            election_event_id: $electionEventId\n            document_id: $documentId\n        ) {\n            url\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation GenerateBallotPublication($electionEventId: uuid!, $electionId: uuid) {\n        generate_ballot_publication(election_event_id: $electionEventId, election_id: $electionId) {\n            ballot_publication_id\n        }\n    }\n"): (typeof documents)["\n    mutation GenerateBallotPublication($electionEventId: uuid!, $electionId: uuid) {\n        generate_ballot_publication(election_event_id: $electionEventId, election_id: $electionId) {\n            ballot_publication_id\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query get_area_with_area_contests($areaId: uuid!, $electionEventId: uuid!) {\n        sequent_backend_area_contest(\n            where: {_and: {area_id: {_eq: $areaId}, election_event_id: {_eq: $electionEventId}}}\n        ) {\n            contest {\n                name\n            }\n            id\n        }\n    }\n"): (typeof documents)["\n    query get_area_with_area_contests($areaId: uuid!, $electionEventId: uuid!) {\n        sequent_backend_area_contest(\n            where: {_and: {area_id: {_eq: $areaId}, election_event_id: {_eq: $electionEventId}}}\n        ) {\n            contest {\n                name\n            }\n            id\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query sequent_backend_area_extended($electionEventId: uuid!, $areaId: uuid!) {\n        sequent_backend_area_contest(\n            where: {_and: {election_event_id: {_eq: $electionEventId}, area_id: {_eq: $areaId}}}\n        ) {\n            contest {\n                id\n                name\n            }\n        }\n    }\n"): (typeof documents)["\n    query sequent_backend_area_extended($electionEventId: uuid!, $areaId: uuid!) {\n        sequent_backend_area_contest(\n            where: {_and: {election_event_id: {_eq: $electionEventId}, area_id: {_eq: $areaId}}}\n        ) {\n            contest {\n                id\n                name\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetBallotStyles {\n        sequent_backend_ballot_style {\n            id\n            election_id\n            election_event_id\n            status\n            tenant_id\n            ballot_eml\n            ballot_signature\n            created_at\n            area_id\n            annotations\n            labels\n            last_updated_at\n        }\n    }\n"): (typeof documents)["\n    query GetBallotStyles {\n        sequent_backend_ballot_style {\n            id\n            election_id\n            election_event_id\n            status\n            tenant_id\n            ballot_eml\n            ballot_signature\n            created_at\n            area_id\n            annotations\n            labels\n            last_updated_at\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetCastVotesByDateRange(\n        $electionEventId: uuid!\n        $tenantId: uuid!\n        $startDate: timestamptz\n        $endDate: timestamptz\n    ) {\n        sequent_backend_cast_vote(\n            where: {\n                _and: {\n                    election_event_id: {_eq: $electionEventId}\n                    tenant_id: {_eq: $tenantId}\n                    created_at: {_gte: $startDate, _lte: $endDate}\n                }\n            }\n        ) {\n            id\n            tenant_id\n            election_id\n            area_id\n            created_at\n            last_updated_at\n            election_event_id\n        }\n    }\n"): (typeof documents)["\n    query GetCastVotesByDateRange(\n        $electionEventId: uuid!\n        $tenantId: uuid!\n        $startDate: timestamptz\n        $endDate: timestamptz\n    ) {\n        sequent_backend_cast_vote(\n            where: {\n                _and: {\n                    election_event_id: {_eq: $electionEventId}\n                    tenant_id: {_eq: $tenantId}\n                    created_at: {_gte: $startDate, _lte: $endDate}\n                }\n            }\n        ) {\n            id\n            tenant_id\n            election_id\n            area_id\n            created_at\n            last_updated_at\n            election_event_id\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetCastVotes($electionEventId: uuid!, $tenantId: uuid!) {\n        sequent_backend_cast_vote(\n            where: {_and: {tenant_id: {_eq: $tenantId}, election_event_id: {_eq: $electionEventId}}}\n        ) {\n            id\n            tenant_id\n            election_id\n            area_id\n            created_at\n            last_updated_at\n            election_event_id\n        }\n    }\n"): (typeof documents)["\n    query GetCastVotes($electionEventId: uuid!, $tenantId: uuid!) {\n        sequent_backend_cast_vote(\n            where: {_and: {tenant_id: {_eq: $tenantId}, election_event_id: {_eq: $electionEventId}}}\n        ) {\n            id\n            tenant_id\n            election_id\n            area_id\n            created_at\n            last_updated_at\n            election_event_id\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetCastVotesForElection($electionEventId: uuid!, $electionId: uuid!, $tenantId: uuid!) {\n        sequent_backend_cast_vote(\n            where: {\n                _and: {\n                    tenant_id: {_eq: $tenantId}\n                    election_event_id: {_eq: $electionEventId}\n                    election_id: {_eq: $electionId}\n                }\n            }\n        ) {\n            id\n            tenant_id\n            election_id\n            area_id\n            created_at\n            last_updated_at\n            election_event_id\n        }\n    }\n"): (typeof documents)["\n    query GetCastVotesForElection($electionEventId: uuid!, $electionId: uuid!, $tenantId: uuid!) {\n        sequent_backend_cast_vote(\n            where: {\n                _and: {\n                    tenant_id: {_eq: $tenantId}\n                    election_event_id: {_eq: $electionEventId}\n                    election_id: {_eq: $electionId}\n                }\n            }\n        ) {\n            id\n            tenant_id\n            election_id\n            area_id\n            created_at\n            last_updated_at\n            election_event_id\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetElectionEventStats($electionEventId: uuid, $tenantId: uuid) {\n        castVotes: sequent_backend_cast_vote_aggregate(\n            where: {election_event_id: {_eq: $electionEventId}, tenant_id: {_eq: $tenantId}}\n        ) {\n            aggregate {\n                count\n            }\n        }\n        elections: sequent_backend_election_aggregate(\n            where: {election_event_id: {_eq: $electionEventId}, tenant_id: {_eq: $tenantId}}\n        ) {\n            aggregate {\n                count\n            }\n        }\n        areas: sequent_backend_area_aggregate(\n            where: {election_event_id: {_eq: $electionEventId}, tenant_id: {_eq: $tenantId}}\n        ) {\n            aggregate {\n                count\n            }\n        }\n    }\n"): (typeof documents)["\n    query GetElectionEventStats($electionEventId: uuid, $tenantId: uuid) {\n        castVotes: sequent_backend_cast_vote_aggregate(\n            where: {election_event_id: {_eq: $electionEventId}, tenant_id: {_eq: $tenantId}}\n        ) {\n            aggregate {\n                count\n            }\n        }\n        elections: sequent_backend_election_aggregate(\n            where: {election_event_id: {_eq: $electionEventId}, tenant_id: {_eq: $tenantId}}\n        ) {\n            aggregate {\n                count\n            }\n        }\n        areas: sequent_backend_area_aggregate(\n            where: {election_event_id: {_eq: $electionEventId}, tenant_id: {_eq: $tenantId}}\n        ) {\n            aggregate {\n                count\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query election_events_tree($tenantId: uuid!, $isArchived: Boolean!) {\n        sequent_backend_election_event(\n            where: {is_archived: {_eq: $isArchived}, _and: {tenant_id: {_eq: $tenantId}}}\n        ) {\n            id\n            name\n            is_archived\n            elections {\n                id\n                name\n                election_event_id\n                image_document_id\n                contests {\n                    id\n                    name\n                    election_event_id\n                    election_id\n                    candidates {\n                        id\n                        name\n                        contest_id\n                        election_event_id\n                    }\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query election_events_tree($tenantId: uuid!, $isArchived: Boolean!) {\n        sequent_backend_election_event(\n            where: {is_archived: {_eq: $isArchived}, _and: {tenant_id: {_eq: $tenantId}}}\n        ) {\n            id\n            name\n            is_archived\n            elections {\n                id\n                name\n                election_event_id\n                image_document_id\n                contests {\n                    id\n                    name\n                    election_event_id\n                    election_id\n                    candidates {\n                        id\n                        name\n                        contest_id\n                        election_event_id\n                    }\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetElections {\n        sequent_backend_election {\n            annotations\n            created_at\n            dates\n            description\n            election_event_id\n            eml\n            id\n            is_consolidated_ballot_encoding\n            labels\n            last_updated_at\n            name\n            num_allowed_revotes\n            presentation\n            spoil_ballot_option\n            status\n            tenant_id\n        }\n    }\n"): (typeof documents)["\n    query GetElections {\n        sequent_backend_election {\n            annotations\n            created_at\n            dates\n            description\n            election_event_id\n            eml\n            id\n            is_consolidated_ballot_encoding\n            labels\n            last_updated_at\n            name\n            num_allowed_revotes\n            presentation\n            spoil_ballot_option\n            status\n            tenant_id\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetEventExecution($tenantId: uuid!, $scheduledEventId: uuid!) {\n        sequent_backend_event_execution(\n            where: {scheduled_event_id: {_eq: $scheduledEventId}, tenant_id: {_eq: $tenantId}}\n        ) {\n            id\n            tenant_id\n            election_event_id\n            scheduled_event_id\n            labels\n            annotations\n            execution_state\n            execution_payload\n            result_payload\n            started_at\n            ended_at\n        }\n    }\n"): (typeof documents)["\n    query GetEventExecution($tenantId: uuid!, $scheduledEventId: uuid!) {\n        sequent_backend_event_execution(\n            where: {scheduled_event_id: {_eq: $scheduledEventId}, tenant_id: {_eq: $tenantId}}\n        ) {\n            id\n            tenant_id\n            election_event_id\n            scheduled_event_id\n            labels\n            annotations\n            execution_state\n            execution_payload\n            result_payload\n            started_at\n            ended_at\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        query getPermissions(\n            $tenant_id: String! = \"\"\n        ) {\n            get_permissions(body: {\n                tenant_id: $tenant_id\n            }) {\n                items {\n                    id\n                    attributes\n                    container_id\n                    description\n                    name\n                }\n                total {\n                    aggregate {\n                        count\n                    }\n                }\n            }\n        }\n        "): (typeof documents)["\n        query getPermissions(\n            $tenant_id: String! = \"\"\n        ) {\n            get_permissions(body: {\n                tenant_id: $tenant_id\n            }) {\n                items {\n                    id\n                    attributes\n                    container_id\n                    description\n                    name\n                }\n                total {\n                    aggregate {\n                        count\n                    }\n                }\n            }\n        }\n        "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation GetPrivateKey($electionEventId: String!, $keysCeremonyId: String!) {\n        get_private_key(\n            object: {election_event_id: $electionEventId, keys_ceremony_id: $keysCeremonyId}\n        ) {\n            private_key_base64\n        }\n    }\n"): (typeof documents)["\n    mutation GetPrivateKey($electionEventId: String!, $keysCeremonyId: String!) {\n        get_private_key(\n            object: {election_event_id: $electionEventId, keys_ceremony_id: $keysCeremonyId}\n        ) {\n            private_key_base64\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        query getRoles(\n            $tenant_id: String! = \"\"\n        ) {\n            get_roles(body: {\n                tenant_id: $tenant_id\n            }) {\n                items {\n                    id\n                    name\n                    permissions\n                    access\n                    attributes\n                    client_roles\n                }\n                total {\n                    aggregate {\n                        count\n                    }\n                }\n            }\n        }\n        "): (typeof documents)["\n        query getRoles(\n            $tenant_id: String! = \"\"\n        ) {\n            get_roles(body: {\n                tenant_id: $tenant_id\n            }) {\n                items {\n                    id\n                    name\n                    permissions\n                    access\n                    attributes\n                    client_roles\n                }\n                total {\n                    aggregate {\n                        count\n                    }\n                }\n            }\n        }\n        "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query TrusteeNames($trustees: [uuid!]!) {\n        sequent_backend_trustee(where: {id: {_in: $trustees}}) {\n            name\n        }\n    }\n"): (typeof documents)["\n    query TrusteeNames($trustees: [uuid!]!) {\n        sequent_backend_trustee(where: {id: {_in: $trustees}}) {\n            name\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation GetUploadUrl($name: String!, $media_type: String!, $size: Int!) {\n        get_upload_url(name: $name, media_type: $media_type, size: $size) {\n            url\n            document_id\n        }\n    }\n"): (typeof documents)["\n    mutation GetUploadUrl($name: String!, $media_type: String!, $size: Int!) {\n        get_upload_url(name: $name, media_type: $media_type, size: $size) {\n            url\n            document_id\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation insert_area_contests($areas: [sequent_backend_area_contest_insert_input!]!) {\n        insert_sequent_backend_area_contest(objects: $areas) {\n            returning {\n                id\n            }\n        }\n    }\n"): (typeof documents)["\n    mutation insert_area_contests($areas: [sequent_backend_area_contest_insert_input!]!) {\n        insert_sequent_backend_area_contest(objects: $areas) {\n            returning {\n                id\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation InsertCastVote(\n        $id: uuid\n        $electionId: uuid\n        $electionEventId: uuid\n        $tenantId: uuid\n        $content: String!\n    ) {\n        insert_sequent_backend_cast_vote(\n            objects: {\n                id: $id\n                election_id: $electionId\n                election_event_id: $electionEventId\n                tenant_id: $tenantId\n                content: $content\n            }\n        ) {\n            returning {\n                id\n                election_id\n                election_event_id\n                tenant_id\n                voter_id_string\n            }\n        }\n    }\n"): (typeof documents)["\n    mutation InsertCastVote(\n        $id: uuid\n        $electionId: uuid\n        $electionEventId: uuid\n        $tenantId: uuid\n        $content: String!\n    ) {\n        insert_sequent_backend_cast_vote(\n            objects: {\n                id: $id\n                election_id: $electionId\n                election_event_id: $electionEventId\n                tenant_id: $tenantId\n                content: $content\n            }\n        ) {\n            returning {\n                id\n                election_id\n                election_event_id\n                tenant_id\n                voter_id_string\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation CreateElectionEvent($electionEvent: CreateElectionEventInput!) {\n        insertElectionEvent(object: $electionEvent) {\n            id\n        }\n    }\n"): (typeof documents)["\n    mutation CreateElectionEvent($electionEvent: CreateElectionEventInput!) {\n        insertElectionEvent(object: $electionEvent) {\n            id\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation InsertTenant($slug: String!) {\n        insertTenant(slug: $slug) {\n            id\n            slug\n        }\n    }\n"): (typeof documents)["\n    mutation InsertTenant($slug: String!) {\n        insertTenant(slug: $slug) {\n            id\n            slug\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query listPgaudit($limit: Int, $offset: Int, $order_by: PgAuditOrderBy) {\n        listPgaudit(limit: $limit, offset: $offset, order_by: $order_by) {\n            items {\n                id\n                audit_type\n                class\n                command\n                dbname\n                id\n                server_timestamp\n                session_id\n                statement\n                user\n            }\n            total {\n                aggregate {\n                    count\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query listPgaudit($limit: Int, $offset: Int, $order_by: PgAuditOrderBy) {\n        listPgaudit(limit: $limit, offset: $offset, order_by: $order_by) {\n            items {\n                id\n                audit_type\n                class\n                command\n                dbname\n                id\n                server_timestamp\n                session_id\n                statement\n                user\n            }\n            total {\n                aggregate {\n                    count\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query ListUserRoles($tenantId: String!, $userId: String!, $electionEventId: String) {\n        list_user_roles(\n            tenant_id: $tenantId\n            user_id: $userId\n            election_event_id: $electionEventId\n        ) {\n            id\n            name\n            permissions\n            access\n            attributes\n            client_roles\n        }\n    }\n"): (typeof documents)["\n    query ListUserRoles($tenantId: String!, $userId: String!, $electionEventId: String) {\n        list_user_roles(\n            tenant_id: $tenantId\n            user_id: $userId\n            election_event_id: $electionEventId\n        ) {\n            id\n            name\n            permissions\n            access\n            attributes\n            client_roles\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation PublishBallot($electionEventId: uuid!, $ballotPublicationId: uuid!) {\n        publish_ballot(\n            election_event_id: $electionEventId\n            ballot_publication_id: $ballotPublicationId\n        ) {\n            ballot_publication_id\n        }\n    }\n"): (typeof documents)["\n    mutation PublishBallot($electionEventId: uuid!, $ballotPublicationId: uuid!) {\n        publish_ballot(\n            election_event_id: $electionEventId\n            ballot_publication_id: $ballotPublicationId\n        ) {\n            ballot_publication_id\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation RestorePrivateKey(\n        $electionEventId: String!\n        $tallySessionId: String!\n        $privateKeyBase64: String!\n    ) {\n        restore_private_key(object: {\n            election_event_id: $electionEventId\n            tally_session_id: $tallySessionId\n            private_key_base64: $privateKeyBase64\n        }) {\n            is_valid\n        }\n    }\n"): (typeof documents)["\n    mutation RestorePrivateKey(\n        $electionEventId: String!\n        $tallySessionId: String!\n        $privateKeyBase64: String!\n    ) {\n        restore_private_key(object: {\n            election_event_id: $electionEventId\n            tally_session_id: $tallySessionId\n            private_key_base64: $privateKeyBase64\n        }) {\n            is_valid\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation SetRolePermission($tenantId: String!, $roleId: String!, $permissionName: String!) {\n        set_role_permission(\n            tenant_id: $tenantId\n            role_id: $roleId\n            permission_name: $permissionName\n        ) {\n            id\n        }\n    }\n"): (typeof documents)["\n    mutation SetRolePermission($tenantId: String!, $roleId: String!, $permissionName: String!) {\n        set_role_permission(\n            tenant_id: $tenantId\n            role_id: $roleId\n            permission_name: $permissionName\n        ) {\n            id\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation SetUserRole($tenantId: String!, $userId: String!, $roleId: String!) {\n        set_user_role(tenant_id: $tenantId, user_id: $userId, role_id: $roleId) {\n            id\n        }\n    }\n"): (typeof documents)["\n    mutation SetUserRole($tenantId: String!, $userId: String!, $roleId: String!) {\n        set_user_role(tenant_id: $tenantId, user_id: $userId, role_id: $roleId) {\n            id\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation UpdateTallyCeremony(\n        $election_event_id: uuid!\n        $tally_session_id: uuid!\n        $status: String!\n    ) {\n        update_tally_ceremony(\n            election_event_id: $election_event_id\n            tally_session_id: $tally_session_id\n            status: $status\n        ) {\n            tally_session_id\n        }\n    }\n"): (typeof documents)["\n    mutation UpdateTallyCeremony(\n        $election_event_id: uuid!\n        $tally_session_id: uuid!\n        $status: String!\n    ) {\n        update_tally_ceremony(\n            election_event_id: $election_event_id\n            tally_session_id: $tally_session_id\n            status: $status\n        ) {\n            tally_session_id\n        }\n    }\n"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;