/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 */
const documents = {
    "\n    mutation CreateScheduledEvent(\n        $tenantId: String!\n        $electionEventId: String!\n        $eventProcessor: String!\n        $cronConfig: String\n        $eventPayload: jsonb!\n        $createdBy: String!\n    ) {\n        createScheduledEvent(\n            tenant_id: $tenantId\n            election_event_id: $electionEventId\n            event_processor: $eventProcessor\n            cron_config: $cronConfig\n            event_payload: $eventPayload\n            created_by: $createdBy\n        ) {\n            id\n        }\n    }\n": types.CreateScheduledEventDocument,
    "\n    query FetchDocument($tenantId: String!, $electionEventId: String!, $documentId: String!) {\n        fetchDocument(\n            tenant_id: $tenantId\n            election_event_id: $electionEventId\n            document_id: $documentId\n        ) {\n            url\n        }\n    }\n": types.FetchDocumentDocument,
    "\n    query GetBallotStyles {\n        sequent_backend_ballot_style {\n            id\n            election_id\n            election_event_id\n            status\n            tenant_id\n            ballot_eml\n            ballot_signature\n            created_at\n            area_id\n            annotations\n            labels\n            last_updated_at\n        }\n    }\n": types.GetBallotStylesDocument,
    "\n    query GetCastVotes(\n        $electionEventId: uuid\n        $tenantId: uuid\n        $startDate: timestamptz!\n        $endDate: timestamptz!\n    ) {\n        sequent_backend_cast_vote(\n            where: {\n                created_at: {_gte: $startDate, _lte: $endDate}\n                election_event_id: {_eq: $electionEventId}\n                tenant_id: {_eq: $tenantId}\n            }\n        ) {\n            id\n            tenant_id\n            election_id\n            area_id\n            created_at\n            last_updated_at\n            election_event_id\n        }\n    }\n": types.GetCastVotesDocument,
    "\n    query GetElectionEventStats($electionEventId: uuid, $tenantId: uuid) {\n        sequent_backend_cast_vote_aggregate(\n            where: {election_event_id: {_eq: $electionEventId}, tenant_id: {_eq: $tenantId}}\n        ) {\n            aggregate {\n                count\n            }\n        }\n        sequent_backend_election_aggregate(\n            where: {election_event_id: {_eq: $electionEventId}, tenant_id: {_eq: $tenantId}}\n        ) {\n            aggregate {\n                count\n            }\n        }\n        sequent_backend_area_aggregate(\n            where: {election_event_id: {_eq: $electionEventId}, tenant_id: {_eq: $tenantId}}\n        ) {\n            aggregate {\n                count\n            }\n        }\n    }\n": types.GetElectionEventStatsDocument,
    "\n    query election_events_tree($tenantId: uuid!, $isArchived: Boolean!) {\n        sequent_backend_election_event(\n            where: {is_archived: {_eq: $isArchived}, _and: {tenant_id: {_eq: $tenantId}}}\n        ) {\n            id\n            name\n            is_archived\n            elections {\n                id\n                name\n                contests {\n                    id\n                    name\n                    candidates {\n                        id\n                        name\n                    }\n                }\n            }\n        }\n    }\n": types.Election_Events_TreeDocument,
    "\n    query GetElections {\n        sequent_backend_election {\n            annotations\n            created_at\n            dates\n            description\n            election_event_id\n            eml\n            id\n            is_consolidated_ballot_encoding\n            labels\n            last_updated_at\n            name\n            num_allowed_revotes\n            presentation\n            spoil_ballot_option\n            status\n            tenant_id\n        }\n    }\n": types.GetElectionsDocument,
    "\n    query GetEventExecution($tenantId: uuid!, $scheduledEventId: uuid!) {\n        sequent_backend_event_execution(\n            where: {scheduled_event_id: {_eq: $scheduledEventId}, tenant_id: {_eq: $tenantId}}\n        ) {\n            id\n            tenant_id\n            election_event_id\n            scheduled_event_id\n            labels\n            annotations\n            execution_state\n            execution_payload\n            result_payload\n            started_at\n            ended_at\n        }\n    }\n": types.GetEventExecutionDocument,
    "\n        query getPermissions(\n            $tenant_id: String! = \"\"\n        ) {\n            get_permissions(body: {\n                tenant_id: $tenant_id\n            }) {\n                items {\n                    id\n                    attributes\n                    container_id\n                    description\n                    name\n                }\n                total {\n                    aggregate {\n                        count\n                    }\n                }\n            }\n        }\n        ": types.GetPermissionsDocument,
    "\n        query getRoles(\n            $tenant_id: String! = \"\"\n        ) {\n            get_roles(body: {\n                tenant_id: $tenant_id\n            }) {\n                items {\n                    id\n                    name\n                    permissions\n                    access\n                    attributes\n                    client_roles\n                }\n                total {\n                    aggregate {\n                        count\n                    }\n                }\n            }\n        }\n        ": types.GetRolesDocument,
    "\n    mutation GetUploadUrl(\n        $name: String!\n        $media_type: String!\n        $size: Int!\n    ) {\n        get_upload_url(\n            name: $name,\n            media_type: $media_type,\n            size: $size\n        ) {\n            url\n            document_id\n        }\n    }\n": types.GetUploadUrlDocument,
    "\n    mutation InsertCastVote(\n        $id: uuid\n        $electionId: uuid\n        $electionEventId: uuid\n        $tenantId: uuid\n        $content: String!\n    ) {\n        insert_sequent_backend_cast_vote(\n            objects: {\n                id: $id\n                election_id: $electionId\n                election_event_id: $electionEventId\n                tenant_id: $tenantId\n                content: $content\n            }\n        ) {\n            returning {\n                id\n                election_id\n                election_event_id\n                tenant_id\n                voter_id_string\n            }\n        }\n    }\n": types.InsertCastVoteDocument,
    "\n    mutation CreateElectionEvent($electionEvent: CreateElectionEventInput!) {\n        insertElectionEvent(object: $electionEvent) {\n            id\n        }\n    }\n": types.CreateElectionEventDocument,
    "\n    mutation InsertTenant($slug: String!) {\n        insertTenant(slug: $slug) {\n            id\n            slug\n        }\n    }\n": types.InsertTenantDocument,
    "\n    query listPgaudit($limit: Int, $offset: Int, $order_by: PgAuditOrderBy) {\n        listPgaudit(limit: $limit, offset: $offset, order_by: $order_by) {\n            items {\n                id\n                audit_type\n                class\n                command\n                dbname\n                id\n                server_timestamp\n                session_id\n                statement\n                user\n            }\n            total {\n                aggregate {\n                    count\n                }\n            }\n        }\n    }\n": types.ListPgauditDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation CreateScheduledEvent(\n        $tenantId: String!\n        $electionEventId: String!\n        $eventProcessor: String!\n        $cronConfig: String\n        $eventPayload: jsonb!\n        $createdBy: String!\n    ) {\n        createScheduledEvent(\n            tenant_id: $tenantId\n            election_event_id: $electionEventId\n            event_processor: $eventProcessor\n            cron_config: $cronConfig\n            event_payload: $eventPayload\n            created_by: $createdBy\n        ) {\n            id\n        }\n    }\n"): (typeof documents)["\n    mutation CreateScheduledEvent(\n        $tenantId: String!\n        $electionEventId: String!\n        $eventProcessor: String!\n        $cronConfig: String\n        $eventPayload: jsonb!\n        $createdBy: String!\n    ) {\n        createScheduledEvent(\n            tenant_id: $tenantId\n            election_event_id: $electionEventId\n            event_processor: $eventProcessor\n            cron_config: $cronConfig\n            event_payload: $eventPayload\n            created_by: $createdBy\n        ) {\n            id\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query FetchDocument($tenantId: String!, $electionEventId: String!, $documentId: String!) {\n        fetchDocument(\n            tenant_id: $tenantId\n            election_event_id: $electionEventId\n            document_id: $documentId\n        ) {\n            url\n        }\n    }\n"): (typeof documents)["\n    query FetchDocument($tenantId: String!, $electionEventId: String!, $documentId: String!) {\n        fetchDocument(\n            tenant_id: $tenantId\n            election_event_id: $electionEventId\n            document_id: $documentId\n        ) {\n            url\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetBallotStyles {\n        sequent_backend_ballot_style {\n            id\n            election_id\n            election_event_id\n            status\n            tenant_id\n            ballot_eml\n            ballot_signature\n            created_at\n            area_id\n            annotations\n            labels\n            last_updated_at\n        }\n    }\n"): (typeof documents)["\n    query GetBallotStyles {\n        sequent_backend_ballot_style {\n            id\n            election_id\n            election_event_id\n            status\n            tenant_id\n            ballot_eml\n            ballot_signature\n            created_at\n            area_id\n            annotations\n            labels\n            last_updated_at\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetCastVotes(\n        $electionEventId: uuid\n        $tenantId: uuid\n        $startDate: timestamptz!\n        $endDate: timestamptz!\n    ) {\n        sequent_backend_cast_vote(\n            where: {\n                created_at: {_gte: $startDate, _lte: $endDate}\n                election_event_id: {_eq: $electionEventId}\n                tenant_id: {_eq: $tenantId}\n            }\n        ) {\n            id\n            tenant_id\n            election_id\n            area_id\n            created_at\n            last_updated_at\n            election_event_id\n        }\n    }\n"): (typeof documents)["\n    query GetCastVotes(\n        $electionEventId: uuid\n        $tenantId: uuid\n        $startDate: timestamptz!\n        $endDate: timestamptz!\n    ) {\n        sequent_backend_cast_vote(\n            where: {\n                created_at: {_gte: $startDate, _lte: $endDate}\n                election_event_id: {_eq: $electionEventId}\n                tenant_id: {_eq: $tenantId}\n            }\n        ) {\n            id\n            tenant_id\n            election_id\n            area_id\n            created_at\n            last_updated_at\n            election_event_id\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetElectionEventStats($electionEventId: uuid, $tenantId: uuid) {\n        sequent_backend_cast_vote_aggregate(\n            where: {election_event_id: {_eq: $electionEventId}, tenant_id: {_eq: $tenantId}}\n        ) {\n            aggregate {\n                count\n            }\n        }\n        sequent_backend_election_aggregate(\n            where: {election_event_id: {_eq: $electionEventId}, tenant_id: {_eq: $tenantId}}\n        ) {\n            aggregate {\n                count\n            }\n        }\n        sequent_backend_area_aggregate(\n            where: {election_event_id: {_eq: $electionEventId}, tenant_id: {_eq: $tenantId}}\n        ) {\n            aggregate {\n                count\n            }\n        }\n    }\n"): (typeof documents)["\n    query GetElectionEventStats($electionEventId: uuid, $tenantId: uuid) {\n        sequent_backend_cast_vote_aggregate(\n            where: {election_event_id: {_eq: $electionEventId}, tenant_id: {_eq: $tenantId}}\n        ) {\n            aggregate {\n                count\n            }\n        }\n        sequent_backend_election_aggregate(\n            where: {election_event_id: {_eq: $electionEventId}, tenant_id: {_eq: $tenantId}}\n        ) {\n            aggregate {\n                count\n            }\n        }\n        sequent_backend_area_aggregate(\n            where: {election_event_id: {_eq: $electionEventId}, tenant_id: {_eq: $tenantId}}\n        ) {\n            aggregate {\n                count\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query election_events_tree($tenantId: uuid!, $isArchived: Boolean!) {\n        sequent_backend_election_event(\n            where: {is_archived: {_eq: $isArchived}, _and: {tenant_id: {_eq: $tenantId}}}\n        ) {\n            id\n            name\n            is_archived\n            elections {\n                id\n                name\n                contests {\n                    id\n                    name\n                    candidates {\n                        id\n                        name\n                    }\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query election_events_tree($tenantId: uuid!, $isArchived: Boolean!) {\n        sequent_backend_election_event(\n            where: {is_archived: {_eq: $isArchived}, _and: {tenant_id: {_eq: $tenantId}}}\n        ) {\n            id\n            name\n            is_archived\n            elections {\n                id\n                name\n                contests {\n                    id\n                    name\n                    candidates {\n                        id\n                        name\n                    }\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetElections {\n        sequent_backend_election {\n            annotations\n            created_at\n            dates\n            description\n            election_event_id\n            eml\n            id\n            is_consolidated_ballot_encoding\n            labels\n            last_updated_at\n            name\n            num_allowed_revotes\n            presentation\n            spoil_ballot_option\n            status\n            tenant_id\n        }\n    }\n"): (typeof documents)["\n    query GetElections {\n        sequent_backend_election {\n            annotations\n            created_at\n            dates\n            description\n            election_event_id\n            eml\n            id\n            is_consolidated_ballot_encoding\n            labels\n            last_updated_at\n            name\n            num_allowed_revotes\n            presentation\n            spoil_ballot_option\n            status\n            tenant_id\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetEventExecution($tenantId: uuid!, $scheduledEventId: uuid!) {\n        sequent_backend_event_execution(\n            where: {scheduled_event_id: {_eq: $scheduledEventId}, tenant_id: {_eq: $tenantId}}\n        ) {\n            id\n            tenant_id\n            election_event_id\n            scheduled_event_id\n            labels\n            annotations\n            execution_state\n            execution_payload\n            result_payload\n            started_at\n            ended_at\n        }\n    }\n"): (typeof documents)["\n    query GetEventExecution($tenantId: uuid!, $scheduledEventId: uuid!) {\n        sequent_backend_event_execution(\n            where: {scheduled_event_id: {_eq: $scheduledEventId}, tenant_id: {_eq: $tenantId}}\n        ) {\n            id\n            tenant_id\n            election_event_id\n            scheduled_event_id\n            labels\n            annotations\n            execution_state\n            execution_payload\n            result_payload\n            started_at\n            ended_at\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        query getPermissions(\n            $tenant_id: String! = \"\"\n        ) {\n            get_permissions(body: {\n                tenant_id: $tenant_id\n            }) {\n                items {\n                    id\n                    attributes\n                    container_id\n                    description\n                    name\n                }\n                total {\n                    aggregate {\n                        count\n                    }\n                }\n            }\n        }\n        "): (typeof documents)["\n        query getPermissions(\n            $tenant_id: String! = \"\"\n        ) {\n            get_permissions(body: {\n                tenant_id: $tenant_id\n            }) {\n                items {\n                    id\n                    attributes\n                    container_id\n                    description\n                    name\n                }\n                total {\n                    aggregate {\n                        count\n                    }\n                }\n            }\n        }\n        "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        query getRoles(\n            $tenant_id: String! = \"\"\n        ) {\n            get_roles(body: {\n                tenant_id: $tenant_id\n            }) {\n                items {\n                    id\n                    name\n                    permissions\n                    access\n                    attributes\n                    client_roles\n                }\n                total {\n                    aggregate {\n                        count\n                    }\n                }\n            }\n        }\n        "): (typeof documents)["\n        query getRoles(\n            $tenant_id: String! = \"\"\n        ) {\n            get_roles(body: {\n                tenant_id: $tenant_id\n            }) {\n                items {\n                    id\n                    name\n                    permissions\n                    access\n                    attributes\n                    client_roles\n                }\n                total {\n                    aggregate {\n                        count\n                    }\n                }\n            }\n        }\n        "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation GetUploadUrl(\n        $name: String!\n        $media_type: String!\n        $size: Int!\n    ) {\n        get_upload_url(\n            name: $name,\n            media_type: $media_type,\n            size: $size\n        ) {\n            url\n            document_id\n        }\n    }\n"): (typeof documents)["\n    mutation GetUploadUrl(\n        $name: String!\n        $media_type: String!\n        $size: Int!\n    ) {\n        get_upload_url(\n            name: $name,\n            media_type: $media_type,\n            size: $size\n        ) {\n            url\n            document_id\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation InsertCastVote(\n        $id: uuid\n        $electionId: uuid\n        $electionEventId: uuid\n        $tenantId: uuid\n        $content: String!\n    ) {\n        insert_sequent_backend_cast_vote(\n            objects: {\n                id: $id\n                election_id: $electionId\n                election_event_id: $electionEventId\n                tenant_id: $tenantId\n                content: $content\n            }\n        ) {\n            returning {\n                id\n                election_id\n                election_event_id\n                tenant_id\n                voter_id_string\n            }\n        }\n    }\n"): (typeof documents)["\n    mutation InsertCastVote(\n        $id: uuid\n        $electionId: uuid\n        $electionEventId: uuid\n        $tenantId: uuid\n        $content: String!\n    ) {\n        insert_sequent_backend_cast_vote(\n            objects: {\n                id: $id\n                election_id: $electionId\n                election_event_id: $electionEventId\n                tenant_id: $tenantId\n                content: $content\n            }\n        ) {\n            returning {\n                id\n                election_id\n                election_event_id\n                tenant_id\n                voter_id_string\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation CreateElectionEvent($electionEvent: CreateElectionEventInput!) {\n        insertElectionEvent(object: $electionEvent) {\n            id\n        }\n    }\n"): (typeof documents)["\n    mutation CreateElectionEvent($electionEvent: CreateElectionEventInput!) {\n        insertElectionEvent(object: $electionEvent) {\n            id\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation InsertTenant($slug: String!) {\n        insertTenant(slug: $slug) {\n            id\n            slug\n        }\n    }\n"): (typeof documents)["\n    mutation InsertTenant($slug: String!) {\n        insertTenant(slug: $slug) {\n            id\n            slug\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query listPgaudit($limit: Int, $offset: Int, $order_by: PgAuditOrderBy) {\n        listPgaudit(limit: $limit, offset: $offset, order_by: $order_by) {\n            items {\n                id\n                audit_type\n                class\n                command\n                dbname\n                id\n                server_timestamp\n                session_id\n                statement\n                user\n            }\n            total {\n                aggregate {\n                    count\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query listPgaudit($limit: Int, $offset: Int, $order_by: PgAuditOrderBy) {\n        listPgaudit(limit: $limit, offset: $offset, order_by: $order_by) {\n            items {\n                id\n                audit_type\n                class\n                command\n                dbname\n                id\n                server_timestamp\n                session_id\n                statement\n                user\n            }\n            total {\n                aggregate {\n                    count\n                }\n            }\n        }\n    }\n"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;