// SPDX-FileCopyrightText: 2023 Felix Robles <felix@sequentech.io>
// SPDX-FileCopyrightText: 2023, 2024 Eduardo Robles <edu@sequentech.io>
//
// SPDX-License-Identifier: AGPL-3.0-only

pub mod activity_logs_report;
pub mod create_ballot_receipt;
pub mod create_keys;
pub mod delete_election_event;
pub mod electoral_log;
pub mod execute_tally_session;
pub mod export_application;
pub mod export_ballot_publication;
pub mod export_election_event;
pub mod export_tally_results;
pub mod export_tasks_execution;
pub mod export_templates;
pub mod export_tenant_config;
pub mod export_trustees;
pub mod export_users;
pub mod generate_report;
pub mod generate_template;
pub mod import_application;
pub mod import_areas;
pub mod import_candidates;
pub mod import_election_event;
pub mod import_templates;
pub mod import_tenant_config;
pub mod import_users;
pub mod insert_election_event;
pub mod insert_tenant;
pub mod manage_election_allow_tally;
pub mod manage_election_dates;
pub mod manage_election_event_date;
pub mod manage_election_event_enrollment;
pub mod manage_election_event_lockdown;
pub mod manage_election_init_report;
pub mod manage_election_voting_period_end;
pub mod manual_verification_report;
pub mod miru_plugin_tasks;
pub mod plugins_tasks;
pub mod post_tally;
pub mod prepare_publication_preview;
pub mod process_board;
pub mod render_document_pdf;
pub mod render_report;
pub mod review_boards;
pub mod scheduled_events;
pub mod scheduled_reports;
pub mod send_template;
pub mod set_public_key;
pub mod update_election_event_ballot_styles;
pub mod upsert_areas;
