/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 */
const documents = {
    "\n    mutation CreateReport(\n        $template: String!\n        $tenantId: String!\n        $electionEventId: String!\n        $name: String!\n        $format: String!\n    ) {\n        renderReport(\n            template: $template\n            tenant_id: $tenantId\n            election_event_id: $electionEventId\n            name: $name\n            format: $format\n        ) {\n            id\n            election_event_id\n            tenant_id\n            name\n            size\n            media_type\n        }\n    }\n": types.CreateReportDocument,
    "\n    mutation CreateScheduledEvent(\n        $tenantId: String!\n        $electionEventId: String!\n        $eventProcessor: String!\n        $cronConfig: String\n        $eventPayload: jsonb!\n        $createdBy: String!\n    ) {\n        createScheduledEvent(\n            tenant_id: $tenantId\n            election_event_id: $electionEventId\n            event_processor: $eventProcessor\n            cron_config: $cronConfig\n            event_payload: $eventPayload\n            created_by: $createdBy\n        ) {\n            id\n            tenant_id\n            election_event_id\n            created_at\n            stopped_at\n            labels\n            annotations\n            event_processor\n            cron_config\n            event_payload\n            created_by\n        }\n    }\n": types.CreateScheduledEventDocument,
    "\n    query FetchDocument($tenantId: String!, $electionEventId: String!, $documentId: String!) {\n        fetchDocument(\n            tenant_id: $tenantId\n            election_event_id: $electionEventId\n            document_id: $documentId\n        ) {\n            url\n        }\n    }\n": types.FetchDocumentDocument,
    "\n    query GetBallotStyles {\n        sequent_backend_ballot_style {\n            id\n            election_id\n            election_event_id\n            status\n            tenant_id\n            ballot_eml\n            ballot_signature\n            created_at\n            area_id\n            annotations\n            labels\n            last_updated_at\n        }\n    }\n": types.GetBallotStylesDocument,
    "\n    query GetCastVotes(\n        $electionEventId: uuid\n        $tenantId: uuid\n        $startDate: timestamptz!\n        $endDate: timestamptz!\n    ) {\n        sequent_backend_cast_vote(\n            where: {\n                created_at: {_gte: $startDate, _lte: $endDate}\n                election_event_id: {_eq: $electionEventId}\n                tenant_id: {_eq: $tenantId}\n            }\n        ) {\n            id\n            tenant_id\n            election_id\n            area_id\n            created_at\n            last_updated_at\n            election_event_id\n        }\n    }\n": types.GetCastVotesDocument,
    "\n    query GetElectionEventStats($electionEventId: uuid, $tenantId: uuid) {\n        sequent_backend_cast_vote_aggregate(\n            where: {election_event_id: {_eq: $electionEventId}, tenant_id: {_eq: $tenantId}}\n        ) {\n            aggregate {\n                count\n            }\n        }\n        sequent_backend_election_aggregate(\n            where: {election_event_id: {_eq: $electionEventId}, tenant_id: {_eq: $tenantId}}\n        ) {\n            aggregate {\n                count\n            }\n        }\n        sequent_backend_area_aggregate(\n            where: {election_event_id: {_eq: $electionEventId}, tenant_id: {_eq: $tenantId}}\n        ) {\n            aggregate {\n                count\n            }\n        }\n    }\n": types.GetElectionEventStatsDocument,
    "\n    query GetElections {\n        sequent_backend_election {\n            annotations\n            created_at\n            dates\n            description\n            election_event_id\n            eml\n            id\n            is_consolidated_ballot_encoding\n            labels\n            last_updated_at\n            name\n            num_allowed_revotes\n            presentation\n            spoil_ballot_option\n            status\n            tenant_id\n        }\n    }\n": types.GetElectionsDocument,
    "\n    query GetEventExecution($tenantId: uuid!, $scheduledEventId: uuid!) {\n        sequent_backend_event_execution(\n            where: {scheduled_event_id: {_eq: $scheduledEventId}, tenant_id: {_eq: $tenantId}}\n        ) {\n            id\n            tenant_id\n            election_event_id\n            scheduled_event_id\n            labels\n            annotations\n            execution_state\n            execution_payload\n            result_payload\n            started_at\n            ended_at\n        }\n    }\n": types.GetEventExecutionDocument,
    "\n    mutation InsertCastVote(\n        $id: uuid\n        $electionId: uuid\n        $electionEventId: uuid\n        $tenantId: uuid\n        $content: String!\n    ) {\n        insert_sequent_backend_cast_vote(\n            objects: {\n                id: $id\n                election_id: $electionId\n                election_event_id: $electionEventId\n                tenant_id: $tenantId\n                content: $content\n            }\n        ) {\n            returning {\n                id\n                election_id\n                election_event_id\n                tenant_id\n                voter_id_string\n            }\n        }\n    }\n": types.InsertCastVoteDocument,
    "\n    mutation CreateElectionEvent(\n        $electionEvent: sequent_backend_election_event_insert_input!\n        $elections: [sequent_backend_election_insert_input!]!\n    ) {\n        insert_sequent_backend_election_event(objects: [$electionEvent]) {\n            returning {\n                id\n            }\n        }\n        insert_sequent_backend_election(objects: $elections) {\n            returning {\n                id\n            }\n        }\n    }\n": types.CreateElectionEventDocument,
    "\n    mutation UpdateElectionStatus(\n        $electionId: uuid! = \"f2f1065e-b784-46d1-b81a-c71bfeb9ad55\",\n        $electionEventId: uuid! = \"33f18502-a67c-4853-8333-a58630663559\",\n        $tenantId: uuid! = \"90505c8a-23a9-4cdf-a26b-4e19f6a097d5\",\n        $status: jsonb! = {voting_status: \"STARTED\"}\n    ) {\n        update_sequent_backend_election(\n            where: {\n                id: {_eq: $electionId},\n                election_event_id: {_eq: $electionEventId},\n                tenant_id: {_eq: $tenantId}\n            },\n            _set: {\n                status: $status\n            }\n        ) {\n            returning {\n                id\n            }\n        }\n    }\n": types.UpdateElectionStatusDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation CreateReport(\n        $template: String!\n        $tenantId: String!\n        $electionEventId: String!\n        $name: String!\n        $format: String!\n    ) {\n        renderReport(\n            template: $template\n            tenant_id: $tenantId\n            election_event_id: $electionEventId\n            name: $name\n            format: $format\n        ) {\n            id\n            election_event_id\n            tenant_id\n            name\n            size\n            media_type\n        }\n    }\n"): (typeof documents)["\n    mutation CreateReport(\n        $template: String!\n        $tenantId: String!\n        $electionEventId: String!\n        $name: String!\n        $format: String!\n    ) {\n        renderReport(\n            template: $template\n            tenant_id: $tenantId\n            election_event_id: $electionEventId\n            name: $name\n            format: $format\n        ) {\n            id\n            election_event_id\n            tenant_id\n            name\n            size\n            media_type\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation CreateScheduledEvent(\n        $tenantId: String!\n        $electionEventId: String!\n        $eventProcessor: String!\n        $cronConfig: String\n        $eventPayload: jsonb!\n        $createdBy: String!\n    ) {\n        createScheduledEvent(\n            tenant_id: $tenantId\n            election_event_id: $electionEventId\n            event_processor: $eventProcessor\n            cron_config: $cronConfig\n            event_payload: $eventPayload\n            created_by: $createdBy\n        ) {\n            id\n            tenant_id\n            election_event_id\n            created_at\n            stopped_at\n            labels\n            annotations\n            event_processor\n            cron_config\n            event_payload\n            created_by\n        }\n    }\n"): (typeof documents)["\n    mutation CreateScheduledEvent(\n        $tenantId: String!\n        $electionEventId: String!\n        $eventProcessor: String!\n        $cronConfig: String\n        $eventPayload: jsonb!\n        $createdBy: String!\n    ) {\n        createScheduledEvent(\n            tenant_id: $tenantId\n            election_event_id: $electionEventId\n            event_processor: $eventProcessor\n            cron_config: $cronConfig\n            event_payload: $eventPayload\n            created_by: $createdBy\n        ) {\n            id\n            tenant_id\n            election_event_id\n            created_at\n            stopped_at\n            labels\n            annotations\n            event_processor\n            cron_config\n            event_payload\n            created_by\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query FetchDocument($tenantId: String!, $electionEventId: String!, $documentId: String!) {\n        fetchDocument(\n            tenant_id: $tenantId\n            election_event_id: $electionEventId\n            document_id: $documentId\n        ) {\n            url\n        }\n    }\n"): (typeof documents)["\n    query FetchDocument($tenantId: String!, $electionEventId: String!, $documentId: String!) {\n        fetchDocument(\n            tenant_id: $tenantId\n            election_event_id: $electionEventId\n            document_id: $documentId\n        ) {\n            url\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetBallotStyles {\n        sequent_backend_ballot_style {\n            id\n            election_id\n            election_event_id\n            status\n            tenant_id\n            ballot_eml\n            ballot_signature\n            created_at\n            area_id\n            annotations\n            labels\n            last_updated_at\n        }\n    }\n"): (typeof documents)["\n    query GetBallotStyles {\n        sequent_backend_ballot_style {\n            id\n            election_id\n            election_event_id\n            status\n            tenant_id\n            ballot_eml\n            ballot_signature\n            created_at\n            area_id\n            annotations\n            labels\n            last_updated_at\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetCastVotes(\n        $electionEventId: uuid\n        $tenantId: uuid\n        $startDate: timestamptz!\n        $endDate: timestamptz!\n    ) {\n        sequent_backend_cast_vote(\n            where: {\n                created_at: {_gte: $startDate, _lte: $endDate}\n                election_event_id: {_eq: $electionEventId}\n                tenant_id: {_eq: $tenantId}\n            }\n        ) {\n            id\n            tenant_id\n            election_id\n            area_id\n            created_at\n            last_updated_at\n            election_event_id\n        }\n    }\n"): (typeof documents)["\n    query GetCastVotes(\n        $electionEventId: uuid\n        $tenantId: uuid\n        $startDate: timestamptz!\n        $endDate: timestamptz!\n    ) {\n        sequent_backend_cast_vote(\n            where: {\n                created_at: {_gte: $startDate, _lte: $endDate}\n                election_event_id: {_eq: $electionEventId}\n                tenant_id: {_eq: $tenantId}\n            }\n        ) {\n            id\n            tenant_id\n            election_id\n            area_id\n            created_at\n            last_updated_at\n            election_event_id\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetElectionEventStats($electionEventId: uuid, $tenantId: uuid) {\n        sequent_backend_cast_vote_aggregate(\n            where: {election_event_id: {_eq: $electionEventId}, tenant_id: {_eq: $tenantId}}\n        ) {\n            aggregate {\n                count\n            }\n        }\n        sequent_backend_election_aggregate(\n            where: {election_event_id: {_eq: $electionEventId}, tenant_id: {_eq: $tenantId}}\n        ) {\n            aggregate {\n                count\n            }\n        }\n        sequent_backend_area_aggregate(\n            where: {election_event_id: {_eq: $electionEventId}, tenant_id: {_eq: $tenantId}}\n        ) {\n            aggregate {\n                count\n            }\n        }\n    }\n"): (typeof documents)["\n    query GetElectionEventStats($electionEventId: uuid, $tenantId: uuid) {\n        sequent_backend_cast_vote_aggregate(\n            where: {election_event_id: {_eq: $electionEventId}, tenant_id: {_eq: $tenantId}}\n        ) {\n            aggregate {\n                count\n            }\n        }\n        sequent_backend_election_aggregate(\n            where: {election_event_id: {_eq: $electionEventId}, tenant_id: {_eq: $tenantId}}\n        ) {\n            aggregate {\n                count\n            }\n        }\n        sequent_backend_area_aggregate(\n            where: {election_event_id: {_eq: $electionEventId}, tenant_id: {_eq: $tenantId}}\n        ) {\n            aggregate {\n                count\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetElections {\n        sequent_backend_election {\n            annotations\n            created_at\n            dates\n            description\n            election_event_id\n            eml\n            id\n            is_consolidated_ballot_encoding\n            labels\n            last_updated_at\n            name\n            num_allowed_revotes\n            presentation\n            spoil_ballot_option\n            status\n            tenant_id\n        }\n    }\n"): (typeof documents)["\n    query GetElections {\n        sequent_backend_election {\n            annotations\n            created_at\n            dates\n            description\n            election_event_id\n            eml\n            id\n            is_consolidated_ballot_encoding\n            labels\n            last_updated_at\n            name\n            num_allowed_revotes\n            presentation\n            spoil_ballot_option\n            status\n            tenant_id\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetEventExecution($tenantId: uuid!, $scheduledEventId: uuid!) {\n        sequent_backend_event_execution(\n            where: {scheduled_event_id: {_eq: $scheduledEventId}, tenant_id: {_eq: $tenantId}}\n        ) {\n            id\n            tenant_id\n            election_event_id\n            scheduled_event_id\n            labels\n            annotations\n            execution_state\n            execution_payload\n            result_payload\n            started_at\n            ended_at\n        }\n    }\n"): (typeof documents)["\n    query GetEventExecution($tenantId: uuid!, $scheduledEventId: uuid!) {\n        sequent_backend_event_execution(\n            where: {scheduled_event_id: {_eq: $scheduledEventId}, tenant_id: {_eq: $tenantId}}\n        ) {\n            id\n            tenant_id\n            election_event_id\n            scheduled_event_id\n            labels\n            annotations\n            execution_state\n            execution_payload\n            result_payload\n            started_at\n            ended_at\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation InsertCastVote(\n        $id: uuid\n        $electionId: uuid\n        $electionEventId: uuid\n        $tenantId: uuid\n        $content: String!\n    ) {\n        insert_sequent_backend_cast_vote(\n            objects: {\n                id: $id\n                election_id: $electionId\n                election_event_id: $electionEventId\n                tenant_id: $tenantId\n                content: $content\n            }\n        ) {\n            returning {\n                id\n                election_id\n                election_event_id\n                tenant_id\n                voter_id_string\n            }\n        }\n    }\n"): (typeof documents)["\n    mutation InsertCastVote(\n        $id: uuid\n        $electionId: uuid\n        $electionEventId: uuid\n        $tenantId: uuid\n        $content: String!\n    ) {\n        insert_sequent_backend_cast_vote(\n            objects: {\n                id: $id\n                election_id: $electionId\n                election_event_id: $electionEventId\n                tenant_id: $tenantId\n                content: $content\n            }\n        ) {\n            returning {\n                id\n                election_id\n                election_event_id\n                tenant_id\n                voter_id_string\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation CreateElectionEvent(\n        $electionEvent: sequent_backend_election_event_insert_input!\n        $elections: [sequent_backend_election_insert_input!]!\n    ) {\n        insert_sequent_backend_election_event(objects: [$electionEvent]) {\n            returning {\n                id\n            }\n        }\n        insert_sequent_backend_election(objects: $elections) {\n            returning {\n                id\n            }\n        }\n    }\n"): (typeof documents)["\n    mutation CreateElectionEvent(\n        $electionEvent: sequent_backend_election_event_insert_input!\n        $elections: [sequent_backend_election_insert_input!]!\n    ) {\n        insert_sequent_backend_election_event(objects: [$electionEvent]) {\n            returning {\n                id\n            }\n        }\n        insert_sequent_backend_election(objects: $elections) {\n            returning {\n                id\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation UpdateElectionStatus(\n        $electionId: uuid! = \"f2f1065e-b784-46d1-b81a-c71bfeb9ad55\",\n        $electionEventId: uuid! = \"33f18502-a67c-4853-8333-a58630663559\",\n        $tenantId: uuid! = \"90505c8a-23a9-4cdf-a26b-4e19f6a097d5\",\n        $status: jsonb! = {voting_status: \"STARTED\"}\n    ) {\n        update_sequent_backend_election(\n            where: {\n                id: {_eq: $electionId},\n                election_event_id: {_eq: $electionEventId},\n                tenant_id: {_eq: $tenantId}\n            },\n            _set: {\n                status: $status\n            }\n        ) {\n            returning {\n                id\n            }\n        }\n    }\n"): (typeof documents)["\n    mutation UpdateElectionStatus(\n        $electionId: uuid! = \"f2f1065e-b784-46d1-b81a-c71bfeb9ad55\",\n        $electionEventId: uuid! = \"33f18502-a67c-4853-8333-a58630663559\",\n        $tenantId: uuid! = \"90505c8a-23a9-4cdf-a26b-4e19f6a097d5\",\n        $status: jsonb! = {voting_status: \"STARTED\"}\n    ) {\n        update_sequent_backend_election(\n            where: {\n                id: {_eq: $electionId},\n                election_event_id: {_eq: $electionEventId},\n                tenant_id: {_eq: $tenantId}\n            },\n            _set: {\n                status: $status\n            }\n        ) {\n            returning {\n                id\n            }\n        }\n    }\n"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;