apiVersion: v1
kind: ConfigMap
metadata:
  name: step-env
  namespace: step-apps
data:
  # General
  ENV_SLUG: "step"
  LOG_LEVEL: "info"
  
  # RabbitMQ
  AMQP_ADDR: "amqp://rabbitmq.step-infra.svc.cluster.local:5672"
  
  # S3 / Storage (MinIO/RustFS)
  AWS_REGION: "us-east-1"
  RUSTFS_URL: "http://rustfs.step-infra.svc.cluster.local:9000"
  AWS_S3_PRIVATE_URI: "http://rustfs.step-infra.svc.cluster.local:9000"
  AWS_S3_PUBLIC_URI: "http://rustfs.step-infra.svc.cluster.local:9000"
  AWS_S3_ACCESS_KEY: "admin"
  AWS_S3_BUCKET: "election-event-documents"
  AWS_S3_PUBLIC_BUCKET: "public"
  # Public facing Storage URL for Browser (via Ingress)
  PUBLIC_BUCKET_URL: "https://portal.local/storage/public/"

  # Keycloak
  # Internal URL for Backend-to-Backend
  KEYCLOAK_URL: "http://keycloak.step-infra.svc.cluster.local:8090"
  # Public URL for Browser Redirects
  KEYCLOAK_PUBLIC_URL: "https://portal.local"

  KEYCLOAK_DB__USER: "postgres"
  KEYCLOAK_DB__HOST: "postgres.step-infra.svc.cluster.local"
  KEYCLOAK_DB__PORT: "5432"
  KEYCLOAK_DB__DBNAME: "keycloak"

  # Hasura
  # Public facing Hasura URL for Browser (via Ingress)
  HASURA_URL: "https://portal.local/hasura/v1/graphql"
  HASURA_ENDPOINT: "http://hasura.step-apps.svc.cluster.local:8080/v1/graphql"
  HARVEST_DOMAIN: "harvest.step-apps.svc.cluster.local:8400"

  HASURA_DB__USER: "postgres"
  HASURA_DB__HOST: "postgres.step-infra.svc.cluster.local"
  HASURA_DB__PORT: "5432"
  HASURA_DB__DBNAME: "hasura"

  # B3
  B3_PG_USER: "postgres"
  B3_PG_HOST: "postgres.step-infra.svc.cluster.local"
  B3_PG_PORT: "5432"
  B3_PG_DATABASE: "b3"

  # Secrets
  SECRETS_BACKEND: "env"

  # Other
  VOTING_PORTAL_URL: "https://portal.local"
