apiVersion: v1
kind: Secret
metadata:
  name: gitea-pull-secret
  namespace: step-apps
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "gitea.gitea:3000": {
          "auth": "YWRtaW46YWRtaW4xMjM="
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: harvest
  namespace: step-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harvest
  template:
    metadata:
      labels:
        app: harvest
    spec:
      imagePullSecrets:
        - name: gitea-pull-secret
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: harvest
          image: gitea.gitea:3000/admin/harvest:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: step-env
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: windmill
  namespace: step-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: windmill
  template:
    metadata:
      labels:
        app: windmill
    spec:
      imagePullSecrets:
        - name: gitea-pull-secret
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: windmill
          image: gitea.gitea:3000/admin/windmill:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: step-env
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-portal
  namespace: step-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-portal
  template:
    metadata:
      labels:
        app: admin-portal
    spec:
      imagePullSecrets:
        - name: gitea-pull-secret
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: admin-portal
          image: gitea.gitea:3000/admin/admin-portal:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: step-env
          env:
            - name: KEYCLOAK_URL
              value: "http://keycloak.local/"
---
apiVersion: v1
kind: Service
metadata:
  name: admin-portal
  namespace: step-apps
spec:
  selector:
    app: admin-portal
  ports:
    - port: 80
      targetPort: 8000
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix
  namespace: step-apps
spec:
  stripPrefix:
    prefixes:
      - /hasura
---
apiVersion: v1
kind: Service
metadata:
  name: hasura
  namespace: step-apps
spec:
  selector:
    app: hasura
  ports:
    - port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasura
  namespace: step-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hasura
  template:
    metadata:
      labels:
        app: hasura
    spec:
      imagePullSecrets:
        - name: gitea-pull-secret
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: hasura
          image: gitea.gitea:3000/admin/hasura:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: step-env
          env:
            - name: PG_DATABASE_URL
              value: postgres://postgres:password@postgres.step-infra.svc.cluster.local:5432/hasura
            - name: HASURA_GRAPHQL_DATABASE_URL
              value: postgres://postgres:password@postgres.step-infra.svc.cluster.local:5432/hasura
            - name: HASURA_GRAPHQL_METADATA_DATABASE_URL
              value: postgres://postgres:password@postgres.step-infra.svc.cluster.local:5432/hasura
            - name: HASURA_GRAPHQL_ADMIN_SECRET
              value: "admin123"
            - name: HASURA_GRAPHQL_JWT_SECRET
              value: '{"type":"RS256", "jwk_url": "http://keycloak.step-infra.svc.cluster.local:8090/realms/step/protocol/openid-connect/certs"}'
            - name: HASURA_GRAPHQL_UNAUTHORIZED_ROLE
              value: "anonymous"
            - name: HASURA_GRAPHQL_ENABLE_CONSOLE
              value: "true"
            - name: HASURA_GRAPHQL_DEV_MODE
              value: "true"
            - name: HASURA_GRAPHQL_MIGRATIONS_SERVER_TIMEOUT
              value: "60"
