-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- -- 1. Drop existing function if it exists
-- DROP FUNCTION IF EXISTS sequent_backend.count_applications_func(uuid, text, jsonb, jsonb);
