-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "sequent_backend"."tally_sheet" add column "created_by_user_id" text
--  null;
