-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "sequent_backend"."cast_vote" add column "ballot_id" text
--  null unique;
