-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE OR REPLACE FUNCTION sequent_backend.set_current_timestamp_updated_at()
--  RETURNS trigger
--  LANGUAGE plpgsql
-- AS $function$
-- DECLARE
--   _new record;
-- BEGIN
--   _new := NEW;
--   _new."updated_at" = NOW();
--   RETURN _new;
-- END;
-- $function$;
--
-- CREATE OR REPLACE FUNCTION sequent_backend.set_current_timestamp_last_updated_at()
--  RETURNS trigger
--  LANGUAGE plpgsql
-- AS $function$
-- DECLARE
--   _new record;
-- BEGIN
--   _new := NEW;
--   _new."last_updated_at" = NOW();
--   RETURN _new;
-- END;
-- $function$;
