-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "sequent_backend"."report" add column "encryption_policy" character varying
--  not null default 'unencrypted';
