-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "sequent_backend"."tally_session_contest" add column "tally_session_id" uuid
--  not null;
