-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "sequent_backend"."communication_template" add column "communication_type" text
--  not null;
