-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "sequent_backend"."scheduled_event" add column "task_id" varchar
--  null;
