-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "sequent_backend"."election_event" add column "encryption_protocol" varchar
--  not null;
