// SPDX-FileCopyrightText: 2024 Félix Robles <felix@sequentech.io>
//
// SPDX-License-Identifier: AGPL-3.0-only
import {GraphQLRequest, operationName} from "@apollo/client"

const AdminOperationMap: Record<string, string> = {
    // area
    sequent_backend_area: "area-read",
    sequent_backend_areas: "area-read",
    insert_sequent_backend_area: "area-write",
    insert_sequent_backend_areas: "area-write",
    update_sequent_backend_area: "area-write",
    update_sequent_backend_areas: "area-write",
    delete_sequent_backend_area: "area-write",
    delete_sequent_backend_areas: "area-write",
    // area_contest
    sequent_backend_area_contest: "area-read",
    sequent_backend_area_contests: "area-read",
    insert_sequent_backend_area_contest: "area-write",
    insert_sequent_backend_area_contests: "area-write",
    update_sequent_backend_area_contest: "area-write",
    update_sequent_backend_area_contests: "area-write",
    delete_sequent_backend_area_contest: "area-write",
    delete_sequent_backend_area_contests: "area-write",
    // ballot_publication
    sequent_backend_ballot_publication: "publish-read",
    sequent_backend_ballot_publications: "publish-read",
    insert_sequent_backend_ballot_publication: "publish-write",
    insert_sequent_backend_ballot_publications: "publish-write",
    update_sequent_backend_ballot_publication: "publish-write",
    update_sequent_backend_ballot_publications: "publish-write",
    delete_sequent_backend_ballot_publication: "publish-write",
    delete_sequent_backend_ballot_publications: "publish-write",
    // ballot_style
    sequent_backend_ballot_style: "publish-read",
    sequent_backend_ballot_styles: "publish-read",
    insert_sequent_backend_ballot_style: "publish-write",
    insert_sequent_backend_ballot_styles: "publish-write",
    update_sequent_backend_ballot_style: "publish-write",
    update_sequent_backend_ballot_styles: "publish-write",
    delete_sequent_backend_ballot_style: "publish-write",
    delete_sequent_backend_ballot_styles: "publish-write",
    // candidate
    sequent_backend_candidate: "election-event-read",
    sequent_backend_candidates: "election-event-read",
    insert_sequent_backend_candidate: "election-event-write",
    insert_sequent_backend_candidates: "election-event-write",
    update_sequent_backend_candidate: "election-event-write",
    update_sequent_backend_candidates: "election-event-write",
    delete_sequent_backend_candidate: "election-event-write",
    delete_sequent_backend_candidates: "election-event-write",
    // cast_vote
    sequent_backend_cast_vote: "cast-vote-read",
    sequent_backend_cast_votes: "cast-vote-read",
    // communication_template
    sequent_backend_communication_template: "communication-template-read",
    sequent_backend_communication_templates: "communication-template-read",
    insert_sequent_backend_communication_template: "communication-template-write",
    insert_sequent_backend_communication_templates: "communication-template-write",
    update_sequent_backend_communication_template: "communication-template-write",
    update_sequent_backend_communication_templates: "communication-template-write",
    delete_sequent_backend_communication_template: "communication-template-write",
    delete_sequent_backend_communication_templates: "communication-template-write",
    // contest
    sequent_backend_contest: "election-event-read",
    sequent_backend_contests: "election-event-read",
    insert_sequent_backend_contest: "election-event-write",
    insert_sequent_backend_contests: "election-event-write",
    update_sequent_backend_contest: "election-event-write",
    update_sequent_backend_contests: "election-event-write",
    delete_sequent_backend_contest: "election-event-write",
    delete_sequent_backend_contests: "election-event-write",
    // document
    sequent_backend_document: "document-read",
    sequent_backend_documents: "document-read",
    insert_sequent_backend_document: "document-write",
    insert_sequent_backend_documents: "document-write",
    update_sequent_backend_document: "document-write",
    update_sequent_backend_documents: "document-write",
    delete_sequent_backend_document: "document-write",
    delete_sequent_backend_documents: "document-write",
    // election
    sequent_backend_election: "election-event-read",
    sequent_backend_elections: "election-event-read",
    insert_sequent_backend_election: "election-event-write",
    insert_sequent_backend_elections: "election-event-write",
    update_sequent_backend_election: "election-event-write",
    update_sequent_backend_elections: "election-event-write",
    delete_sequent_backend_election: "election-event-write",
    delete_sequent_backend_elections: "election-event-write",
    // election_event
    sequent_backend_election_event: "election-event-read",
    sequent_backend_election_events: "election-event-read",
    insert_sequent_backend_election_event: "election-event-write",
    insert_sequent_backend_election_events: "election-event-write",
    update_sequent_backend_election_event: "election-event-write",
    update_sequent_backend_election_events: "election-event-write",
    delete_sequent_backend_election_event: "election-event-write",
    delete_sequent_backend_election_events: "election-event-write",
    // keys_ceremony
    sequent_backend_keys_ceremony: "admin-ceremony",
    sequent_backend_keys_ceremonys: "admin-ceremony",
    // results_area_contest
    sequent_backend_results_area_contest: "tally-results-read",
    sequent_backend_results_area_contests: "tally-results-read",
    // results_area_contest_candidate
    sequent_backend_results_area_contest_candidate: "tally-results-read",
    sequent_backend_results_area_contest_candidates: "tally-results-read",
    // results_contest
    sequent_backend_results_contest: "tally-results-read",
    sequent_backend_results_contests: "tally-results-read",
    // results_contest_candidate
    sequent_backend_results_contest_candidate: "tally-results-read",
    sequent_backend_results_contest_candidates: "tally-results-read",
    // results_election
    sequent_backend_results_election: "tally-results-read",
    sequent_backend_results_elections: "tally-results-read",
    // results_event
    sequent_backend_results_event: "tally-results-read",
    sequent_backend_results_events: "tally-results-read",
    // support_material
    sequent_backend_support_material: "support-material-read",
    sequent_backend_support_materials: "support-material-read",
    insert_sequent_backend_support_material: "support-material-write",
    insert_sequent_backend_support_materials: "support-material-write",
    update_sequent_backend_support_material: "support-material-write",
    update_sequent_backend_support_materials: "support-material-write",
    delete_sequent_backend_support_material: "support-material-write",
    delete_sequent_backend_support_materials: "support-material-write",
    // tally_session
    sequent_backend_tally_session: "admin-ceremony",
    sequent_backend_tally_sessions: "admin-ceremony",
    // tally_session_contest
    sequent_backend_tally_session_contest: "admin-ceremony",
    sequent_backend_tally_session_contests: "admin-ceremony",
    // tally_session_execution
    sequent_backend_tally_session_execution: "admin-ceremony",
    sequent_backend_tally_session_executions: "admin-ceremony",
    // tally_sheet
    sequent_backend_tally_sheet: "tally-sheet-view",
    sequent_backend_tally_sheets: "tally-sheet-view",
    insert_sequent_backend_tally_sheet: "tally-sheet-create",
    insert_sequent_backend_tally_sheets: "tally-sheet-create",
    update_sequent_backend_tally_sheet: "tally-sheet-create",
    update_sequent_backend_tally_sheets: "tally-sheet-create",
    delete_sequent_backend_tally_sheet: "tally-sheet-create",
    delete_sequent_backend_tally_sheets: "tally-sheet-create",
    // trustee
    sequent_backend_trustee: "trustee-read",
    sequent_backend_trustees: "trustee-read",
    insert_sequent_backend_trustee: "trustee-write",
    insert_sequent_backend_trustees: "trustee-write",
    update_sequent_backend_trustee: "trustee-write",
    update_sequent_backend_trustees: "trustee-write",
    delete_sequent_backend_trustee: "trustee-write",
    delete_sequent_backend_trustees: "trustee-write",
}

const TrusteeOperationMap: Record<string, string> = {
    ...AdminOperationMap,
    // keys_ceremony
    sequent_backend_keys_ceremony: "trustee-ceremony",
    sequent_backend_keys_ceremonys: "trustee-ceremony",
    // tally_session
    sequent_backend_tally_session: "trustee-ceremony",
    sequent_backend_tally_sessions: "trustee-ceremony",
    // tally_session_contest
    sequent_backend_tally_session_contest: "trustee-ceremony",
    sequent_backend_tally_session_contests: "trustee-ceremony",
    // tally_session_execution
    sequent_backend_tally_session_execution: "trustee-ceremony",
    sequent_backend_tally_session_executions: "trustee-ceremony",
}

export const getOperationRole = (operation: GraphQLRequest, isTrustee = false): string => {
    return (
        (isTrustee ? TrusteeOperationMap : AdminOperationMap)[operation?.operationName ?? ""] ??
        "admin-user"
    )
}
