// SPDX-FileCopyrightText: 2023 Félix Robles <felix@sequentech.io>
//
// SPDX-License-Identifier: AGPL-3.0-only

export enum ScheduledEventType {
    CREATE_REPORT = "CREATE_REPORT",
    UPDATE_VOTING_STATUS = "UPDATE_VOTING_STATUS",
    CREATE_BOARD = "CREATE_BOARD",
    CREATE_KEYS = "CREATE_KEYS",
    SET_PUBLIC_KEY = "SET_PUBLIC_KEY",
    CREATE_ELECTION_EVENT_BALLOT_STYLES = "CREATE_ELECTION_EVENT_BALLOT_STYLES",
    TALLY_ELECTION_EVENT = "TALLY_ELECTION_EVENT",
    SEND_TEMPLATE = "SEND_TEMPLATE",
}
