-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "sequent_backend"."area_contest" add column "last_updated_at" timestamptz
--  null default now();
