#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2025 Sequent Tech Inc <legal@sequentech.io>
#
# SPDX-License-Identifier: AGPL-3.0-only
"""Report every use of `unsafe` in the Rust workspace and how each crate controls it.

Every crate of the workspace is expected to forbid unsafe code through its manifest
(`[lints.rust] unsafe_code = "forbid"`), or to deny it and allow each remaining use where
it stands, under a `// SAFETY:` comment that states the invariant relied upon. Generated
bindings (files whose first lines say so) are listed but not held to the comment rule.

    scripts/check-unsafe.py packages        # exit 1 on any use without the lint or the comment
"""
from __future__ import annotations

import re
import sys
import tomllib
from pathlib import Path

UNSAFE = re.compile(r"\bunsafe\b")
LINT = re.compile(r'^\s*unsafe_code\s*=\s*"(forbid|deny)"', re.M)
GENERATED = re.compile(r"generated by|do not edit", re.I)
SKIP_DIRS = {"target", "vendor", "node_modules", "rust-local-target", "pkg"}


def strip_comments_and_strings(line: str) -> str:
    line = re.sub(r'"(?:\\.|[^"\\])*"', '""', line)
    return line.split("//", 1)[0]


def crate_dirs(root: Path) -> list[Path]:
    manifest = tomllib.loads((root / "Cargo.toml").read_text(encoding="utf-8"))
    dirs = []
    for member in manifest.get("workspace", {}).get("members", []):
        dirs += sorted(p.parent for p in root.glob(f"{member}/Cargo.toml"))
    return dirs


def uses_in(crate: Path) -> list[tuple[Path, int, bool, bool]]:
    """(file, line, has_safety_comment, generated) for every `unsafe` token outside comments and strings."""
    found = []
    for path in sorted(crate.rglob("*.rs")):
        if SKIP_DIRS & set(path.relative_to(crate).parts):
            continue
        lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
        generated = any(GENERATED.search(l) for l in lines[:5])
        for i, line in enumerate(lines):
            if not UNSAFE.search(strip_comments_and_strings(line)):
                continue
            window = [l for l in lines[max(0, i - 6):i] if l.strip()]
            safety = any("SAFETY:" in l for l in window) or "SAFETY:" in line
            found.append((path, i + 1, safety, generated))
    return found


def main() -> int:
    root = Path(sys.argv[1] if len(sys.argv) > 1 else "packages").resolve()
    problems = 0
    total = 0
    for crate in crate_dirs(root):
        manifest = (crate / "Cargo.toml").read_text(encoding="utf-8")
        lint = LINT.search(manifest)
        uses = uses_in(crate)
        total += len(uses)
        name = crate.relative_to(root).as_posix()
        status = f'unsafe_code = "{lint.group(1)}"' if lint else "no unsafe_code lint"
        print(f"{name}: {len(uses)} use(s), {status}")
        if not lint and not all(g for *_, g in uses):
            print(f"  problem: no unsafe_code lint in {name}/Cargo.toml")
            problems += 1
        for path, line, safety, generated in uses:
            where = f"  {path.relative_to(root).as_posix()}:{line}"
            if generated:
                print(f"{where} (generated bindings)")
            elif safety:
                print(f"{where} (// SAFETY: stated)")
            else:
                print(f"{where} problem: no // SAFETY: comment")
                problems += 1
    print(f"unsafe uses: {total}, problems: {problems}")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
