-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "sequent_backend"."lock" add column "created_at" timestamptz
--  not null default now();
