// SPDX-FileCopyrightText: 2026 Sequent Tech Inc <legal@sequentech.io>
//
// SPDX-License-Identifier: AGPL-3.0-only

//! The election event import bundle: what it contains, and whether it is valid.
//!
//! This is the single definition of the format shared by everything that
//! produces or consumes an import — windmill's importer on the server, and the
//! configuration tools in `beyond/packages` in the browser.
//!
//! It lives here rather than in `beyond` because the dependency between the
//! repositories runs one way: `beyond` is a git submodule of step and
//! path-depends on this crate, so step cannot depend on `beyond`. Anything
//! windmill must use has to be here. `sequent-core` also already compiles to
//! WASM and is already vendored into the front ends as a package, so both
//! consumers reach this module through paths that already carry production
//! code.
//!
//! Everything in this module must stay **pure** — no database, no IO, no
//! clock — or it cannot run in a browser, and the browser is where a delivery
//! engineer wants the answer.
//!
//! See `beyond/docs/docusaurus/docs/engineering/election-config-architecture.md`
//! and <https://github.com/sequentech/meta/issues/12769>.

/// Turning a source document's rows into a bundle. Needs the templates, so it
/// shares their feature.
#[cfg(feature = "election_config_templates")]
pub mod build;

/// What a bundle becomes as files. Needs the builder, so it shares its feature;
/// the zip writer itself is behind `election_config_archive`.
#[cfg(feature = "election_config_templates")]
pub mod archive;

/// The Election Architect's plan, and how it becomes rows the builder reads.
/// Needs the builder's feature, since compiling a plan means building a bundle.
#[cfg(feature = "election_config_templates")]
pub mod architect;

pub mod branding;
pub mod census_csv;

/// How a ballot behaves, in the platform's own words. Ungated: the bundle
/// validator needs the value space and carries no feature.
pub mod policy;

/// What a client's build of the wizard may say. Shares the architect's feature,
/// since applying a profile means having a plan to apply it to.
#[cfg(feature = "election_config_templates")]
pub mod profile;

pub mod emit;
pub mod ids;
pub mod paths;

/// The ballots a plan's voters would be given, generated by the platform's own
/// ballot-style builder. Shares the builder's feature, since previewing means
/// having built the entities first.
#[cfg(feature = "election_config_templates")]
pub mod preview;

pub mod presets;

/// Bundles with known verdicts, shared by every caller of [`validate`] so the two
/// reach the same answer rather than each agreeing with itself.
pub mod fixtures;
pub mod problem;

/// Rendering the base entity templates, behind its own feature so a front end
/// that only validates an existing bundle carries no template engine.
#[cfg(feature = "election_config_templates")]
pub mod render;

pub mod report;
pub mod schema;
pub mod sheet;

/// A moment a plan names, and the instant the platform acts on. Ungated: the
/// scheduler's requirements are not a template concern.
pub mod time;
pub mod validate;

/// The browser's view of this module: thin wrappers over the same functions
/// `step-cli` and windmill call.
///
/// Gated the way `crate::wasm` is, so it appears in exactly the builds that have a
/// JavaScript side. What it exposes depends on the other features — checking an
/// existing bundle needs neither a template engine nor a spreadsheet parser, and a
/// front end that only does that should carry neither.
#[cfg(all(feature = "wasm", feature = "default_features"))]
pub mod wasm;

/// Reading `.xlsx`, behind its own feature so front ends with no workbook to read
/// do not carry a spreadsheet library.
#[cfg(feature = "election_config_xlsx")]
pub mod xlsx;

/// Writing `.xlsx`, behind the same feature as reading it: a front end that
/// carries the spreadsheet library at all can go both ways with it.
#[cfg(feature = "election_config_xlsx")]
pub mod xlsx_write;

/// Reading a workbook back as a plan — the inverse of `architect::to_workbook`.
#[cfg(feature = "election_config_templates")]
pub mod plan_from_workbook;

#[cfg(test)]
mod validate_tests;

// Every re-export below carries the same gate as the module it names. A
// re-export gated differently from its module is not a style question: `pub use
// build::…` without a gate does not compile at all once the module is absent,
// and `default_features` does not imply `election_config_templates` — so the
// crate was broken for every feature set windmill, harvest, velvet and the
// browser builds actually declare. `cargo build --workspace` hid it by unifying
// step-cli's features across the graph, which is why only CI saw it.
#[cfg(feature = "election_config_templates")]
pub use architect::{validate_plan, Blueprint};
#[cfg(feature = "election_config_templates")]
pub use archive::{layout, Artifact, Layout};
#[cfg(feature = "election_config_templates")]
pub use build::{
    build, BuildOptions, Bundle, CommunicationTemplate, JsonTable, PlainTable,
};
pub use emit::{json_csv, plain_csv, JsonField};
pub use ids::IdFactory;
pub use paths::{coerce_cell, deep_merge, expand, Cell};
pub use policy::{Policies as ContestPolicies, PolicyPatch, PolicyValue};
pub use presets::{AuthPreset, RealmPatch};
pub use problem::{Code, Problem, Report as ValidationReport, Severity};
#[cfg(feature = "election_config_templates")]
pub use profile::{apply_profile, ClientProfile, Profile};
#[cfg(feature = "election_config_templates")]
pub use render::TemplateSet;
pub use report::{EReportEncryption, Report, ReportCronConfig, ReportType};
pub use schema::ImportElectionEventSchema;
pub use sheet::{Origin, Row, Sheet, Workbook};
pub use time::Timestamp;
pub use validate::validate;
