// SPDX-FileCopyrightText: 2024 Sequent Tech <legal@sequentech.io>
//
// SPDX-License-Identifier: AGPL-3.0-only

export enum ETasksExecution {
    EXPORT_ELECTION_EVENT = "EXPORT_ELECTION_EVENT",
    EXPORT_TENANT_CONFIG = "EXPORT_TENANT_CONFIG",
    IMPORT_TENANT_CONFIG = "IMPORT_TENANT_CONFIG",
    EXPORT_TRUSTEES = "EXPORT_TRUSTEES",
    IMPORT_CANDIDATES = "IMPORT_CANDIDATES",
    IMPORT_USERS = "IMPORT_USERS",
    CREATE_ELECTION_EVENT = "CREATE_ELECTION_EVENT",
    IMPORT_ELECTION_EVENT = "IMPORT_ELECTION_EVENT",
    EXPORT_VOTERS = "EXPORT_VOTERS",
    CREATE_TRANSMISSION_PACKAGE = "CREATE_TRANSMISSION_PACKAGE",
    EXPORT_BALLOT_PUBLICATION = "EXPORT_BALLOT_PUBLICATION",
    EXPORT_ACTIVITY_LOGS_REPORT = "EXPORT_ACTIVITY_LOGS_REPORT",
    GENERATE_REPORT = "GENERATE_REPORT",
    GENERATE_TRANSMISSION_REPORT = "GENERATE_TRANSMISSION_REPORT",
    EXPORT_APPLICATION = "EXPORT_APPLICATION",
    IMPORT_APPLICATION = "IMPORT_APPLICATION",
    RENDER_DOCUMENT_PDF = "RENDER_DOCUMENT_PDF",
    PREPARE_PUBLICATION_PREVIEW = "PREPARE_PUBLICATION_PREVIEW",
}
