// SPDX-FileCopyrightText: 2024 Sequent Tech <legal@sequentech.io>
//
// SPDX-License-Identifier: AGPL-3.0-only

export enum ETasksExecution {
    EXPORT_ELECTION_EVENT = "EXPORT_ELECTION_EVENT",
    IMPORT_CANDIDATES = "IMPORT_CANDIDATES",
    IMPORT_USERS = "IMPORT_USERS",
    IMPORT_ELECTION_EVENT = "IMPORT_ELECTION_EVENT",
    EXPORT_VOTERS = "EXPORT_VOTERS",
    CREATE_TRANSMISSION_PACKAGE = "CREATE_TRANSMISSION_PACKAGE",
    EXPORT_BALLOT_PUBLICATION = "EXPORT_BALLOT_PUBLICATION",
    EXPORT_ACTIVITY_LOGS_REPORT = "EXPORT_ACTIVITY_LOGS_REPORT",
}
