# SPDX-FileCopyrightText: 2025 Sequent Tech Inc <legal@sequentech.io>
#
# SPDX-License-Identifier: AGPL-3.0-only

FROM hasura/graphql-engine:v2.33.1.cli-migrations-v3

COPY metadata /hasura-metadata
COPY migrations /hasura-migrations
