// SPDX-FileCopyrightText: 2026 Sequent Tech Inc <legal@sequentech.io>
// SPDX-License-Identifier: AGPL-3.0-only

//! Render command help and configuration rustdoc from the same sources as the CLI.
use super::{config::Settings, Command};
use anyhow::Result;
use clap::Subcommand;
use std::collections::BTreeMap;

/// Extract field rustdoc for configuration tables; defaults come from serialization.
fn descriptions() -> BTreeMap<(String, String), String> {
    let mut result = BTreeMap::new();
    let mut structure = String::new();
    let mut comments = Vec::new();
    for line in include_str!("config.rs").lines().map(str::trim) {
        if let Some(comment) = line.strip_prefix("/// ") {
            comments.push(comment.to_owned());
        } else if let Some(name) = line.strip_prefix("pub struct ") {
            structure = name.trim_end_matches(" {").to_owned();
            comments.clear();
        } else if let Some(field) = line.strip_prefix("pub ").and_then(|s| s.split_once(':')) {
            result.insert((structure.clone(), field.0.to_owned()), comments.join(" "));
            comments.clear();
        } else if !line.starts_with("#[") {
            comments.clear();
        }
    }
    result
}

/// Generate the public reference without requiring a configured tenant or live services.
pub fn markdown() -> Result<String> {
    let mut text = String::from("---\ntitle: Voting load reference\nsidebar_position: 10\n---\n\n<!-- SPDX-FileCopyrightText: 2026 Sequent Tech Inc <legal@sequentech.io> -->\n<!-- SPDX-License-Identifier: AGPL-3.0-only -->\n\nGenerated by `step-cli load reference`. Unknown configuration keys are rejected. Local initialization derives tenant endpoints, the available browser, and Docker networking from the coordinator. Paths in preparation are relative to the workload YAML. Secrets are referenced by environment-variable name.\n\n");
    let mut command = Command::augment_subcommands(clap::Command::new("step-cli load"));
    for child in command
        .get_subcommands_mut()
        .filter(|child| !child.is_hide_set())
    {
        let name = child.get_name().to_owned();
        text.push_str(&format!(
            "## {name}\n\n```text\n{}\n```\n\n",
            child.render_long_help()
        ));
    }
    let defaults = serde_json::to_value(Settings::default())?;
    let docs = descriptions();
    for (section, kind) in [
        ("target", "Target"),
        ("workload", "Workload"),
        ("execution", "Execution"),
        ("preparation", "Preparation"),
        ("runtime", "Runtime"),
        ("reporting", "Reporting"),
    ] {
        text.push_str(&format!(
            "## {section}\n\n| Setting | Default | Meaning |\n| --- | --- | --- |\n"
        ));
        if let Some(fields) = defaults[section].as_object() {
            for (name, value) in fields {
                let default = if section == "runtime" && name == "playwright_dir" {
                    "packages/voting-portal under the current directory".into()
                } else if section == "runtime" && name == "chromium" {
                    "CHROMIUM_EXECUTABLE_PATH, chromium on PATH, or Playwright default".into()
                } else if section == "target" && name == "tenant_id" {
                    "from CLI session".into()
                } else {
                    value.to_string()
                };
                let description = docs
                    .get(&(kind.to_owned(), name.clone()))
                    .cloned()
                    .unwrap_or_default();
                text.push_str(&format!("| `{name}` | `{default}` | {description} |\n"));
            }
        }
        text.push('\n');
    }
    text.push_str("## Goals\n\n`goals` defaults to an empty mapping. Supported stages are `status_ms`, `cast_ms`, and `journey_ms`; each accepts positive `p50` and `p99` limits in milliseconds. `min_casts_per_second` defaults to zero (disabled). Status-only workloads cannot configure cast goals. Every planned journey must succeed regardless of optional performance goals.\n");
    // Clap indents blank help lines; keep generated Markdown whitespace-clean.
    Ok(text
        .lines()
        .map(str::trim_end)
        .collect::<Vec<_>>()
        .join("\n")
        + "\n")
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn reference_documents_every_serialized_setting() {
        let defaults = serde_json::to_value(Settings::default()).unwrap();
        let docs = descriptions();
        for (section, kind) in [
            ("target", "Target"),
            ("workload", "Workload"),
            ("execution", "Execution"),
            ("preparation", "Preparation"),
            ("runtime", "Runtime"),
            ("reporting", "Reporting"),
        ] {
            for name in defaults[section].as_object().unwrap().keys() {
                assert!(
                    !docs
                        .get(&(kind.into(), name.clone()))
                        .unwrap_or(&String::new())
                        .is_empty(),
                    "Missing rustdoc: {section}.{name}"
                );
            }
        }
        let text = markdown().unwrap();
        assert!(text.contains("## prepare"));
        assert!(text.lines().all(|line| line == line.trim_end()));
        assert!(!text.contains("## encrypt"));
    }
}
