-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "sequent_backend"."contest" add column "under_vote_alert" bool
--  null default 'false';
