// SPDX-FileCopyrightText: 2025 Sequent Tech Inc <legal@sequentech.io>
//
// SPDX-License-Identifier: AGPL-3.0-only

export enum ScheduledEvents {
    SYSTEM_LOCKDOWN_FOR_INTERNET_VOTING_SETTINGS = "SYSTEM_LOCKDOWN_FOR_INTERNET_VOTING_SETTINGS",
    START_PRE_REGISTRATION_OVCS = "START_PRE_REGISTRATION_OVCS",
    END_PRE_REGISTRATION_OVCS = "END_PRE_REGISTRATION_OVCS",
    START_TEST_VOTING_PERIOD = "START_TEST_VOTING_PERIOD",
    END_TEST_VOTING_PERIOD = "END_TEST_VOTING_PERIOD",
    START_INTERNET_VOTING_PERIOD = "START_INTERNET_VOTING_PERIOD",
    END_INTERNET_VOTING_PERIOD = "END_INTERNET_VOTING_PERIOD",
    LAB_TEST = "LAB_TEST",
    FIELD_TEST = "FIELD_TEST",
    MOCK_ELECTIONS = "MOCK_ELECTIONS",
    FTS = "FTS",
}
