#![allow(dead_code)]
// SPDX-FileCopyrightText: 2026 Sequent Tech <legal@sequentech.io>
//
// SPDX-License-Identifier: AGPL-3.0-only

//! Producing a Verificatum corpus on demand, by running Verificatum.
//!
//! The checked-in corpora under `testdata/` are fixed shapes: one single-party
//! session and two three-party ones. That bounds the ingest side of the interop
//! to whatever someone once generated by hand, which is exactly the restriction
//! the emit side escaped once protocol info files could be synthesized.
//!
//! This runs VMN's own multi-party demo to produce a corpus for a *given* shape,
//! so a test can generate its own input and verify whatever comes back.
//!
//! # It must never substitute
//!
//! [`generate`] returns `None` when the toolchain is absent, and the caller
//! skips. It must not fall back to producing corpus data with our own code: the
//! whole evidentiary value of a corpus is that a different implementation
//! produced it, and a fallback would silently convert every cross-implementation
//! test into a self-consistency one while leaving them green.
//!
//! # What running VMN's prover requires
//!
//! Rather more than running its verifier, and none of it is guessable:
//!
//! - **A Unix host.** `vmni` and `vmn` hardcode `/dev/urandom` and derive a URL
//!   from the machine hostname against a lowercase-only regex, both evaluated
//!   before argument parsing. On Windows we go through WSL, inside an
//!   unprivileged UTS namespace so `hostname localhost` affects nothing outside
//!   the process tree.
//! - **Unix line endings.** The demo scripts come through a Windows checkout
//!   with CRLF, and `/bin/sh` fails on them with a misleading
//!   `./conf: : not found` followed by a syntax error at end of file.
//! - **No X server.** `TERM=./vterm` and `SILENT=-s`, which VMN supports but
//!   documents only in a comment inside `conf`.
//! - **Rewritten launchers.** The shipped `bin/` scripts hardcode
//!   `/usr/local/share/java`; only the `CLASSPATH` line is rewritten, so
//!   everything else about how an operator invokes them is preserved.
//! - **`./delete` between runs.** A second `./mix` against a spent session
//!   blocks *indefinitely* rather than reporting anything.

use std::path::{Path, PathBuf};
use std::process::Command;

/// The session shape to generate.
#[derive(Clone, Debug)]
pub struct Shape {
    pub parties: usize,
    pub threshold: usize,
    pub width: usize,
    pub ciphertexts: usize,
    /// Parties that take part in mixing and decryption. `None` means all of
    /// them; a subset makes the others inactive, so VMN writes its placeholder
    /// decryption material for them.
    pub active: Option<Vec<usize>>,
}

impl Shape {
    #[must_use]
    pub fn new(parties: usize, threshold: usize, width: usize, ciphertexts: usize) -> Self {
        Shape {
            parties,
            threshold,
            width,
            ciphertexts,
            active: None,
        }
    }

    #[must_use]
    pub fn with_active(mut self, active: Vec<usize>) -> Self {
        self.active = Some(active);
        self
    }

    fn label(&self) -> String {
        let active = match &self.active {
            None => "all".to_string(),
            Some(a) => a.iter().map(usize::to_string).collect::<Vec<_>>().join("-"),
        };
        format!(
            "k{}_t{}_w{}_n{}_{active}",
            self.parties, self.threshold, self.width, self.ciphertexts
        )
    }
}

/// A generated corpus: the proof directory and the protocol info file that
/// describes the session it came from.
pub struct Corpus {
    pub nizkp: PathBuf,
    pub protinfo: PathBuf,
}

/// Run VMN to produce a corpus for `shape`, or `None` if it cannot be run here.
///
/// Output is written under the system temporary directory on the *Windows* side
/// when going through WSL, so the caller can read it with ordinary file I/O.
pub fn generate(shape: &Shape) -> Option<Corpus> {
    // VMN's demo binds fixed ports (HINTOFFSET 4040, HTTPOFFSET 8040) and uses a
    // fixed working directory, so two runs at once fight over both. Cargo runs
    // the tests in a binary in parallel, which showed up as tests that pass
    // serially and fail together. Generation is exclusive by nature.
    static ONE_AT_A_TIME: std::sync::Mutex<()> = std::sync::Mutex::new(());
    let _guard = ONE_AT_A_TIME.lock().unwrap_or_else(|e| e.into_inner());

    let source = vmn_source()?;
    let shell = Shell::detect()?;

    let out_host = std::env::temp_dir().join(format!("vsvmn_corpus_{}", shape.label()));
    let _ = std::fs::remove_dir_all(&out_host);
    std::fs::create_dir_all(&out_host).ok()?;

    let script = script(shape, &shell.to_unix(&source), &shell.to_unix(&out_host));
    let script_host = out_host.join("generate.sh");
    std::fs::write(&script_host, script).ok()?;

    let status = shell.run(&format!(
        "tr -d '\\r' < '{}' > /tmp/vsvmn_gen.sh && chmod +x /tmp/vsvmn_gen.sh && \
         unshare -U -u --map-root-user bash -c 'hostname localhost; /tmp/vsvmn_gen.sh'",
        shell.to_unix(&script_host)
    ));

    let corpus = Corpus {
        nizkp: out_host.join("nizkp"),
        protinfo: out_host.join("protInfo.xml"),
    };
    if !status || !corpus.nizkp.is_dir() || !corpus.protinfo.is_file() {
        eprintln!("corpus generation did not produce a proof directory; skipping");
        return None;
    }
    Some(corpus)
}

/// The Verificatum source tree, which holds both the jars and the demo.
fn vmn_source() -> Option<PathBuf> {
    let dir = match std::env::var("VMN_SOURCE") {
        Ok(d) => PathBuf::from(d),
        Err(_) => PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../braid/verificatum"),
    };
    dir.join("verificatum-vmn/demo/mixnet/conf")
        .is_file()
        .then_some(dir)
}

/// How to run a Bourne shell on this host.
enum Shell {
    /// A Unix host: run `bash` directly.
    Native,
    /// Windows: go through a WSL distribution.
    Wsl(String),
}

impl Shell {
    fn detect() -> Option<Self> {
        if cfg!(unix) {
            return Some(Shell::Native);
        }
        // `wsl -l -q` lists installed distributions; take the first that runs.
        let out = Command::new("wsl.exe").args(["-l", "-q"]).output().ok()?;
        let listing = String::from_utf16_lossy(
            &out.stdout
                .chunks_exact(2)
                .map(|p| u16::from_le_bytes([p[0], p[1]]))
                .collect::<Vec<_>>(),
        );
        let distro = listing
            .lines()
            .map(str::trim)
            .find(|l| !l.is_empty() && !l.contains("docker"))?;
        eprintln!("using WSL distribution {distro} to run Verificatum's prover");
        Some(Shell::Wsl(distro.to_string()))
    }

    /// A path as the shell sees it.
    fn to_unix(&self, path: &Path) -> String {
        let text = path.display().to_string().replace('\\', "/");
        match self {
            Shell::Native => text,
            // C:/x -> /mnt/c/x
            Shell::Wsl(_) => match text.split_once(':') {
                Some((drive, rest)) if drive.len() == 1 => {
                    format!("/mnt/{}{}", drive.to_lowercase(), rest)
                }
                _ => text,
            },
        }
    }

    fn run(&self, command: &str) -> bool {
        let mut process = match self {
            Shell::Native => {
                let mut c = Command::new("bash");
                c.arg("-c").arg(command);
                c
            }
            Shell::Wsl(distro) => {
                let mut c = Command::new("wsl.exe");
                c.args(["-d", distro, "--", "bash", "-c", command]);
                c
            }
        };
        match process.status() {
            Ok(s) => s.success(),
            Err(e) => {
                eprintln!("could not run a shell: {e}");
                false
            }
        }
    }
}

/// The setup-and-run script, parameterized by the shape.
fn script(shape: &Shape, source: &str, out: &str) -> String {
    let Shape {
        parties,
        threshold,
        width,
        ciphertexts,
        active,
    } = shape;

    // A subset means: run the full demo first, then restrict and mix again. The
    // spent session must be deleted or ./mix blocks forever.
    let restrict = match active {
        None => String::new(),
        Some(set) => {
            let list = set.iter().map(usize::to_string).collect::<Vec<_>>().join(",");
            format!(
                "for step in \"sact '{{{list}}}'\" delete mix; do\n\
                 \x20   eval \"./$step\" >> \"$WORK/demo.log\" 2>&1 \\\n\
                 \x20       || {{ echo \"restrict step failed: $step\"; tail -30 \"$WORK/demo.log\"; exit 1; }}\n\
                 done\n"
            )
        }
    };

    format!(
        r#"#!/bin/bash
set -e
SRC={source}
OUT={out}
WORK=$(mktemp -d)
JARS="$SRC/verificatum-vmn/verificatum-vmn-3.1.0.jar:$SRC/verificatum-vcr/verificatum-vcr-3.1.0.jar"

mkdir -p "$WORK/bin"
for f in "$SRC"/verificatum-vmn/bin/* "$SRC"/verificatum-vcr/bin/*; do
    [ -f "$f" ] || continue
    sed "s|^export CLASSPATH=.*|export CLASSPATH=$JARS|" "$f" > "$WORK/bin/$(basename "$f")"
done
cp -r "$SRC/verificatum-vmn/demo/mixnet" "$WORK/demo"
find "$WORK/demo" "$WORK/bin" -type f -print0 | while IFS= read -r -d '' f; do
    tr -d '\r' < "$f" > "$f.unix" && mv "$f.unix" "$f"
done
chmod +x "$WORK/bin"/* "$WORK"/demo/* 2>/dev/null || true

cd "$WORK/demo"
sed -i 's|^TERM=xterm$|TERM=./vterm|' conf
sed -i 's|^#SILENT=-s$|SILENT=-s|' conf
sed -i 's|^#WIDTH=2$|WIDTH={width}|' conf
sed -i 's|^NO_MIXSERVERS=3$|NO_MIXSERVERS={parties}|' conf
sed -i 's|^THRESHOLD=2$|THRESHOLD={threshold}|' conf
sed -i 's|^NO_CIPHERTEXTS=100$|NO_CIPHERTEXTS={ciphertexts}|' conf

export PATH="$WORK/bin:$PATH"
export VERIFICATUM_RANDOM_SOURCE="$WORK/random_source"
export VERIFICATUM_RANDOM_SEED="$WORK/random_seed"
vog -rndinit RandomDevice /dev/urandom > /dev/null 2>&1 || true

./demo > "$WORK/demo.log" 2>&1 || {{ tail -20 "$WORK/demo.log"; exit 1; }}
{restrict}
SESSION="$WORK/demo/mydemodir/Party01/dir/nizkp/default"
[ -d "$SESSION" ] || {{ echo "no proof directory at $SESSION"; tail -30 "$WORK/demo.log"; exit 1; }}
# A partially written session would surface later as a confusing "file not
# found" in the test, so insist the directory is complete here.
for required in type width auxsid version FullPublicKey.bt proofs/activethreshold; do
    [ -e "$SESSION/$required" ] || {{ echo "session is missing $required"; ls -R "$SESSION"; exit 1; }}
done
cp -r "$SESSION" "$OUT/nizkp"
cp "$WORK/demo/mydemodir/Party01/protInfo.xml" "$OUT/protInfo.xml"
rm -rf "$WORK"
"#
    )
}

// -------------------------------------------------------------------------
// Test vectors, and sharing a corpus across a test binary
// -------------------------------------------------------------------------

use std::collections::HashMap;
use std::sync::OnceLock;

/// `vmnv -t` output: the intermediate values Verificatum computed for a session,
/// keyed by name (`der.rho`, `PoS.s`, `Dec.v`, …).
///
/// These are what the transcript layer is checked against. Taking them from the
/// *generated* session rather than from a file captured once means they track
/// whatever VMN is installed: a pinned value from 3.1.0 would keep passing
/// against a 3.2 that had changed something, which is a check that cannot fail.
pub type TestVectors = HashMap<String, String>;

/// Parse `vmnv -t`'s three-line records:
///
/// ```text
/// TEST VECTOR
/// der.rho - Derived prefix bytes to all random oracle queries.
/// f0504114...
/// ```
fn parse_test_vectors(text: &str) -> TestVectors {
    let lines: Vec<&str> = text.lines().map(str::trim).collect();
    let mut out = HashMap::new();
    for (index, line) in lines.iter().enumerate() {
        if *line != "TEST VECTOR" {
            continue;
        }
        let (Some(header), Some(value)) = (lines.get(index + 1), lines.get(index + 2)) else {
            continue;
        };
        if let Some((name, _)) = header.split_once(" - ") {
            // A name can recur once per party; the first occurrence is party 1's.
            out.entry(name.trim().to_string())
                .or_insert_with(|| (*value).to_string());
        }
    }
    out
}

impl Corpus {
    /// Run `vmnv -t` over this corpus and return what Verificatum computed.
    ///
    /// Returns `None` if the verifier cannot be run, which is separate from it
    /// rejecting the proof — the caller skips rather than treating absence as
    /// agreement.
    pub fn test_vectors(&self) -> Option<TestVectors> {
        let text = self.raw_test_vectors()?;
        let vectors = parse_test_vectors(&text);
        vectors.contains_key("der.rho").then_some(vectors)
    }

    /// The whole `vmnv -t` output.
    ///
    /// Some vectors -- `bas.pk`, `bas.h` -- are multi-line point lists rather
    /// than a single value, so a caller that needs those parses the text itself.
    pub fn raw_test_vectors(&self) -> Option<String> {
        let (source, _) = random_source()?;
        let seed = private_seed()?;
        let output = Command::new(java())
            .arg("-cp")
            .arg(classpath()?)
            .arg("com.verificatum.protocol.mixnet.MixNetElGamalVerifyFiatShamirTool")
            .args(["vmnv"])
            .arg(&source)
            .arg(&seed)
            .args(["-mix", "-t", "par,der,bas,PoS,Dec,u", "-wd"])
            // Unique per call: concurrent vmnv runs sharing a working directory
            // delete each other's scratch space (see they_verify_ours.rs).
            .arg(format!(
                "vsvmn_tv_{}_{}",
                std::process::id(),
                NEXT_WD.fetch_add(1, std::sync::atomic::Ordering::Relaxed)
            ))
            .args(["-auxsid", "default"])
            .arg(&self.protinfo)
            .arg(&self.nizkp)
            .output()
            .ok()?;

        let text = String::from_utf8_lossy(&output.stdout).into_owned();
        text.contains("TEST VECTOR").then_some(text)
    }
}

/// The random source and seed `vmnv` refuses to start without, even though
/// verification consumes no randomness.
///
/// Provisioned here rather than supplied by the caller. Corpus *generation*
/// already builds its own inside the shell it runs VMN in; making the native
/// path do the same is what lets `cargo test` run the suite unaided. An
/// externally initialised source is still honoured through the two environment
/// variables, which is the only way to point at one built differently.
///
/// The pair is canonical and shared — callers must copy the *seed* before use,
/// because `vmnv` rewrites it on every run.
pub fn random_source() -> Option<&'static (PathBuf, PathBuf)> {
    static SOURCE: OnceLock<Option<(PathBuf, PathBuf)>> = OnceLock::new();
    SOURCE
        .get_or_init(|| {
            match (
                std::env::var("VMN_RANDOM_SOURCE"),
                std::env::var("VMN_RANDOM_SEED"),
            ) {
                (Ok(source), Ok(seed)) => Some((PathBuf::from(source), PathBuf::from(seed))),
                _ => provision_random_source(),
            }
        })
        .as_ref()
}

/// Build a random source with `vog`, the way Verificatum's own documentation
/// does — except for the initialiser.
///
/// `vog -rndinit RandomDevice /dev/urandom` is what the manual says, and it is
/// what corpus generation uses because it runs under a Unix shell. There is no
/// `/dev/urandom` on Windows, so this takes the portable route instead: 512
/// bytes from the OS into a file, handed to a seeded PRG. The seed material is
/// only ever consumed by `vmnv`, which verifies deterministically.
fn provision_random_source() -> Option<(PathBuf, PathBuf)> {
    // Per process: two test binaries provisioning at once must not collide, and
    // `vog` writes both files non-atomically.
    let dir = std::env::temp_dir().join(format!("vsvmn_rnd_{}", std::process::id()));
    std::fs::create_dir_all(&dir).ok()?;
    let (source, seed) = (dir.join("random_source"), dir.join("random_seed"));

    let material = dir.join("seed_material");
    let mut bytes = [0u8; 512];
    getrandom::fill(&mut bytes).ok()?;
    std::fs::write(&material, bytes).ok()?;

    // The hash function descriptor the PRG is built from, then the PRG itself;
    // `vog` writes the source and seed as a side effect of the second call.
    let descriptor = vog(&source, &seed, &["-gen", "HashfunctionHeuristic", "SHA-256"])?;
    vog(
        &source,
        &seed,
        &[
            "-seed",
            material.to_str()?,
            "-rndinit",
            "PRGHeuristic",
            descriptor.trim(),
        ],
    )?;

    if !source.is_file() || !seed.is_file() {
        eprintln!("vog did not write a random source under {}", dir.display());
        return None;
    }
    eprintln!("initialised a random source in {}", dir.display());
    Some((source, seed))
}

/// One `vog` invocation, returning its standard output.
fn vog(source: &Path, seed: &Path, args: &[&str]) -> Option<String> {
    let output = Command::new(java())
        .arg("-cp")
        .arg(classpath()?)
        .arg("com.verificatum.ui.gen.GeneratorTool")
        .args(["vog", ":VERIFICATUM_VOG_BUILTIN"])
        .args([source, seed])
        .args(args)
        .output()
        .ok()?;
    if !output.status.success() {
        eprintln!(
            "vog {} failed: {}",
            args.join(" "),
            String::from_utf8_lossy(&output.stderr).trim()
        );
        return None;
    }
    Some(String::from_utf8_lossy(&output.stdout).into_owned())
}

/// A private copy of the seed, since `vmnv` rewrites it on every run and the
/// tests run concurrently.
pub fn private_seed() -> Option<PathBuf> {
    let (_, seed) = random_source()?;
    let private = std::env::temp_dir().join(format!(
        "vsvmn_seed_{}_{}",
        std::process::id(),
        NEXT_WD.fetch_add(1, std::sync::atomic::Ordering::Relaxed)
    ));
    std::fs::copy(seed, &private).ok()?;
    Some(private)
}

/// The `java` binary to run. `VMN_JAVA` overrides `java` from `PATH`.
pub fn java() -> String {
    std::env::var("VMN_JAVA").unwrap_or_else(|_| "java".to_string())
}

/// The two Verificatum jars, in the form `java -cp` wants.
pub fn classpath() -> Option<String> {
    let jars = vmn_source()?;
    let vmn = jars.join("verificatum-vmn/verificatum-vmn-3.1.0.jar");
    let vcr = jars.join("verificatum-vcr/verificatum-vcr-3.1.0.jar");
    if !vmn.is_file() || !vcr.is_file() {
        eprintln!("skipping: jars not found under {}", jars.display());
        return None;
    }
    let separator = if cfg!(windows) { ";" } else { ":" };
    Some(format!("{}{separator}{}", vmn.display(), vcr.display()))
}

/// A corpus generated **once per test binary** and shared by every test in it.
///
/// Generation costs about half a minute, so a file with several format tests
/// would otherwise spend minutes regenerating the same thing. Three parties with
/// a threshold of two, which is the smallest shape where α, the Lagrange
/// coefficients and the decryption combination are all non-trivial.
pub fn shared() -> Option<&'static Corpus> {
    static CORPUS: OnceLock<Option<Corpus>> = OnceLock::new();
    CORPUS
        .get_or_init(|| generate(&Shape::new(3, 2, 2, 10)))
        .as_ref()
}

/// Whether a missing toolchain should fail rather than skip.
///
/// With every test dynamic, a machine without VMN runs the whole suite green
/// having verified nothing — false comfort of the kind this crate exists to
/// avoid. Setting `VSVMN_REQUIRE_VMN=1` in CI turns that into a failure.
pub fn required() -> bool {
    matches!(std::env::var("VSVMN_REQUIRE_VMN").as_deref(), Ok("1"))
}

/// Skip, or fail if the toolchain was declared to be present.
///
/// ```ignore
/// let Some(corpus) = common::shared() else { return common::skip("no VMN"); };
/// ```
pub fn skip(why: &str) {
    assert!(
        !required(),
        "VSVMN_REQUIRE_VMN=1 but the toolchain is unavailable: {why}"
    );
    eprintln!("skipping: {why}");
}

/// Serial number for `vmnv` working directories.
///
/// Concurrent runs sharing one delete each other's scratch space, which surfaces
/// as tests that pass alone and fail together — see `they_verify_ours.rs`.
static NEXT_WD: std::sync::atomic::AtomicUsize = std::sync::atomic::AtomicUsize::new(0);

/// The test vectors for [`shared`], computed once per test binary.
///
/// `vmnv -t` costs about as much as verification and several tests want the same
/// values, so running it per test would multiply the cost for nothing.
pub fn shared_vectors() -> Option<&'static TestVectors> {
    static VECTORS: OnceLock<Option<TestVectors>> = OnceLock::new();
    VECTORS
        // Parsed from the single raw invocation rather than running `vmnv -t`
        // again: two concurrent runs collide over their working directories and
        // one comes back empty or truncated, which surfaces as tests that pass
        // alone and fail together, or worse, compare against partial output.
        .get_or_init(|| shared_raw_vectors().map(|text| parse_test_vectors(text)))
        .as_ref()
}

/// The raw `vmnv -t` output for [`shared`], likewise computed once.
pub fn shared_raw_vectors() -> Option<&'static String> {
    static RAW: OnceLock<Option<String>> = OnceLock::new();
    RAW.get_or_init(|| shared().and_then(Corpus::raw_test_vectors))
        .as_ref()
}
