// SPDX-FileCopyrightText: 2026 Sequent Tech <legal@sequentech.io>
//
// SPDX-License-Identifier: AGPL-3.0-only

//! Producing a Verificatum corpus on demand, by running Verificatum.
//!
//! The checked-in corpora under `testdata/` are fixed shapes: one single-party
//! session and two three-party ones. That bounds the ingest side of the interop
//! to whatever someone once generated by hand, which is exactly the restriction
//! the emit side escaped once protocol info files could be synthesized.
//!
//! This runs VMN's own multi-party demo to produce a corpus for a *given* shape,
//! so a test can generate its own input and verify whatever comes back.
//!
//! # It must never substitute
//!
//! [`generate`] returns `None` when the toolchain is absent, and the caller
//! skips. It must not fall back to producing corpus data with our own code: the
//! whole evidentiary value of a corpus is that a different implementation
//! produced it, and a fallback would silently convert every cross-implementation
//! test into a self-consistency one while leaving them green.
//!
//! # What running VMN's prover requires
//!
//! Rather more than running its verifier, and none of it is guessable:
//!
//! - **A Unix host.** `vmni` and `vmn` hardcode `/dev/urandom` and derive a URL
//!   from the machine hostname against a lowercase-only regex, both evaluated
//!   before argument parsing. On Windows we go through WSL, inside an
//!   unprivileged UTS namespace so `hostname localhost` affects nothing outside
//!   the process tree.
//! - **Unix line endings.** The demo scripts come through a Windows checkout
//!   with CRLF, and `/bin/sh` fails on them with a misleading
//!   `./conf: : not found` followed by a syntax error at end of file.
//! - **No X server.** `TERM=./vterm` and `SILENT=-s`, which VMN supports but
//!   documents only in a comment inside `conf`.
//! - **Rewritten launchers.** The shipped `bin/` scripts hardcode
//!   `/usr/local/share/java`; only the `CLASSPATH` line is rewritten, so
//!   everything else about how an operator invokes them is preserved.
//! - **`./delete` between runs.** A second `./mix` against a spent session
//!   blocks *indefinitely* rather than reporting anything.

use std::path::{Path, PathBuf};
use std::process::Command;

/// The session shape to generate.
#[derive(Clone, Debug)]
pub struct Shape {
    pub parties: usize,
    pub threshold: usize,
    pub width: usize,
    pub ciphertexts: usize,
    /// Parties that take part in mixing and decryption. `None` means all of
    /// them; a subset makes the others inactive, so VMN writes its placeholder
    /// decryption material for them.
    pub active: Option<Vec<usize>>,
}

impl Shape {
    #[must_use]
    pub fn new(parties: usize, threshold: usize, width: usize, ciphertexts: usize) -> Self {
        Shape {
            parties,
            threshold,
            width,
            ciphertexts,
            active: None,
        }
    }

    #[must_use]
    pub fn with_active(mut self, active: Vec<usize>) -> Self {
        self.active = Some(active);
        self
    }

    fn label(&self) -> String {
        let active = match &self.active {
            None => "all".to_string(),
            Some(a) => a.iter().map(usize::to_string).collect::<Vec<_>>().join("-"),
        };
        format!(
            "k{}_t{}_w{}_n{}_{active}",
            self.parties, self.threshold, self.width, self.ciphertexts
        )
    }
}

/// A generated corpus: the proof directory and the protocol info file that
/// describes the session it came from.
pub struct Corpus {
    pub nizkp: PathBuf,
    pub protinfo: PathBuf,
}

/// Run VMN to produce a corpus for `shape`, or `None` if it cannot be run here.
///
/// Output is written under the system temporary directory on the *Windows* side
/// when going through WSL, so the caller can read it with ordinary file I/O.
pub fn generate(shape: &Shape) -> Option<Corpus> {
    let source = vmn_source()?;
    let shell = Shell::detect()?;

    let out_host = std::env::temp_dir().join(format!("vsvmn_corpus_{}", shape.label()));
    let _ = std::fs::remove_dir_all(&out_host);
    std::fs::create_dir_all(&out_host).ok()?;

    let script = script(shape, &shell.to_unix(&source), &shell.to_unix(&out_host));
    let script_host = out_host.join("generate.sh");
    std::fs::write(&script_host, script).ok()?;

    let status = shell.run(&format!(
        "tr -d '\\r' < '{}' > /tmp/vsvmn_gen.sh && chmod +x /tmp/vsvmn_gen.sh && \
         unshare -U -u --map-root-user bash -c 'hostname localhost; /tmp/vsvmn_gen.sh'",
        shell.to_unix(&script_host)
    ));

    let corpus = Corpus {
        nizkp: out_host.join("nizkp"),
        protinfo: out_host.join("protInfo.xml"),
    };
    if !status || !corpus.nizkp.is_dir() || !corpus.protinfo.is_file() {
        eprintln!("corpus generation did not produce a proof directory; skipping");
        return None;
    }
    Some(corpus)
}

/// The Verificatum source tree, which holds both the jars and the demo.
fn vmn_source() -> Option<PathBuf> {
    let dir = match std::env::var("VMNV_JAR_DIR") {
        Ok(d) => PathBuf::from(d),
        Err(_) => PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../braid/verificatum"),
    };
    dir.join("verificatum-vmn/demo/mixnet/conf")
        .is_file()
        .then_some(dir)
}

/// How to run a Bourne shell on this host.
enum Shell {
    /// A Unix host: run `bash` directly.
    Native,
    /// Windows: go through a WSL distribution.
    Wsl(String),
}

impl Shell {
    fn detect() -> Option<Self> {
        if cfg!(unix) {
            return Some(Shell::Native);
        }
        // `wsl -l -q` lists installed distributions; take the first that runs.
        let out = Command::new("wsl.exe").args(["-l", "-q"]).output().ok()?;
        let listing = String::from_utf16_lossy(
            &out.stdout
                .chunks_exact(2)
                .map(|p| u16::from_le_bytes([p[0], p[1]]))
                .collect::<Vec<_>>(),
        );
        let distro = listing
            .lines()
            .map(str::trim)
            .find(|l| !l.is_empty() && !l.contains("docker"))?;
        eprintln!("using WSL distribution {distro} to run Verificatum's prover");
        Some(Shell::Wsl(distro.to_string()))
    }

    /// A path as the shell sees it.
    fn to_unix(&self, path: &Path) -> String {
        let text = path.display().to_string().replace('\\', "/");
        match self {
            Shell::Native => text,
            // C:/x -> /mnt/c/x
            Shell::Wsl(_) => match text.split_once(':') {
                Some((drive, rest)) if drive.len() == 1 => {
                    format!("/mnt/{}{}", drive.to_lowercase(), rest)
                }
                _ => text,
            },
        }
    }

    fn run(&self, command: &str) -> bool {
        let mut process = match self {
            Shell::Native => {
                let mut c = Command::new("bash");
                c.arg("-c").arg(command);
                c
            }
            Shell::Wsl(distro) => {
                let mut c = Command::new("wsl.exe");
                c.args(["-d", distro, "--", "bash", "-c", command]);
                c
            }
        };
        match process.status() {
            Ok(s) => s.success(),
            Err(e) => {
                eprintln!("could not run a shell: {e}");
                false
            }
        }
    }
}

/// The setup-and-run script, parameterized by the shape.
fn script(shape: &Shape, source: &str, out: &str) -> String {
    let Shape {
        parties,
        threshold,
        width,
        ciphertexts,
        active,
    } = shape;

    // A subset means: run the full demo first, then restrict and mix again. The
    // spent session must be deleted or ./mix blocks forever.
    let restrict = match active {
        None => String::new(),
        Some(set) => {
            let list = set.iter().map(usize::to_string).collect::<Vec<_>>().join(",");
            format!(
                "for step in \"sact '{{{list}}}'\" delete mix; do\n\
                 \x20   eval \"./$step\" >> \"$WORK/demo.log\" 2>&1 \\\n\
                 \x20       || {{ echo \"restrict step failed: $step\"; tail -30 \"$WORK/demo.log\"; exit 1; }}\n\
                 done\n"
            )
        }
    };

    format!(
        r#"#!/bin/bash
set -e
SRC={source}
OUT={out}
WORK=$(mktemp -d)
JARS="$SRC/verificatum-vmn/verificatum-vmn-3.1.0.jar:$SRC/verificatum-vcr/verificatum-vcr-3.1.0.jar"

mkdir -p "$WORK/bin"
for f in "$SRC"/verificatum-vmn/bin/* "$SRC"/verificatum-vcr/bin/*; do
    [ -f "$f" ] || continue
    sed "s|^export CLASSPATH=.*|export CLASSPATH=$JARS|" "$f" > "$WORK/bin/$(basename "$f")"
done
cp -r "$SRC/verificatum-vmn/demo/mixnet" "$WORK/demo"
find "$WORK/demo" "$WORK/bin" -type f -print0 | while IFS= read -r -d '' f; do
    tr -d '\r' < "$f" > "$f.unix" && mv "$f.unix" "$f"
done
chmod +x "$WORK/bin"/* "$WORK"/demo/* 2>/dev/null || true

cd "$WORK/demo"
sed -i 's|^TERM=xterm$|TERM=./vterm|' conf
sed -i 's|^#SILENT=-s$|SILENT=-s|' conf
sed -i 's|^#WIDTH=2$|WIDTH={width}|' conf
sed -i 's|^NO_MIXSERVERS=3$|NO_MIXSERVERS={parties}|' conf
sed -i 's|^THRESHOLD=2$|THRESHOLD={threshold}|' conf
sed -i 's|^NO_CIPHERTEXTS=100$|NO_CIPHERTEXTS={ciphertexts}|' conf

export PATH="$WORK/bin:$PATH"
export VERIFICATUM_RANDOM_SOURCE="$WORK/random_source"
export VERIFICATUM_RANDOM_SEED="$WORK/random_seed"
vog -rndinit RandomDevice /dev/urandom > /dev/null 2>&1 || true

./demo > "$WORK/demo.log" 2>&1 || {{ tail -20 "$WORK/demo.log"; exit 1; }}
{restrict}
SESSION="$WORK/demo/mydemodir/Party01/dir/nizkp/default"
[ -d "$SESSION" ] || {{ echo "no proof directory at $SESSION"; tail -30 "$WORK/demo.log"; exit 1; }}
# A partially written session would surface later as a confusing "file not
# found" in the test, so insist the directory is complete here.
for required in type width auxsid version FullPublicKey.bt proofs/activethreshold; do
    [ -e "$SESSION/$required" ] || {{ echo "session is missing $required"; ls -R "$SESSION"; exit 1; }}
done
cp -r "$SESSION" "$OUT/nizkp"
cp "$WORK/demo/mydemodir/Party01/protInfo.xml" "$OUT/protInfo.xml"
rm -rf "$WORK"
"#
    )
}
