-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "sequent_backend"."tally_session_execution" add column "document_id" uuid
--  not null;
