-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "sequent_backend"."applicant_attributes" add column "tenant_id" uuid
--  not null;
