# SPDX-FileCopyrightText: 2026 Sequent Tech Inc <legal@sequentech.io>
#
# SPDX-License-Identifier: AGPL-3.0-only
#
# The keys of the development trustee trustee1. Checked in for the dev
# environment only.
signing_key = "isptcFtYL3sGVI5paA0M364rYTEnQok396PkGy38Ig0="
share_encryption_key = "DIAtHXhytfU4/gyrr6LUT8wWFc10tPfVsyzFEwVJeQU="
